--	FAF.004 - 13-jan-2014, Fabio Ferreira, 	Correcção registros duplicados
--*******************************************************************************************************************************************
SELECT 
      OSH.ORDERKEY COD_PEDIDO,
      OSH.WHSEID ARMAZEM,
      'WMS' COD_EVENTO_TERCE,
      MIN(OSH.ADDDATE) DATA_REGISTRO,
      OSH.STATUS COD_SITUACAO
FROM
      WMWHSE1.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY COD_PEDIDO,
      OSH.WHSEID ARMAZEM,
      'WMS' COD_EVENTO_TERCE,
      MIN(OSH.ADDDATE) DATA_REGISTRO,
      OSH.STATUS COD_SITUACAO
FROM
      WMWHSE2.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY COD_PEDIDO,
      OSH.WHSEID ARMAZEM,
      'WMS' COD_EVENTO_TERCE,
      MIN(OSH.ADDDATE) DATA_REGISTRO,
      OSH.STATUS COD_SITUACAO
FROM
      WMWHSE3.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY COD_PEDIDO,
      OSH.WHSEID ARMAZEM,
      'WMS' COD_EVENTO_TERCE,
      MIN(OSH.ADDDATE) DATA_REGISTRO,
      OSH.STATUS COD_SITUACAO
FROM
      WMWHSE4.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY COD_PEDIDO,
      OSH.WHSEID ARMAZEM,
      'WMS' COD_EVENTO_TERCE,
      MIN(OSH.ADDDATE) DATA_REGISTRO,
      OSH.STATUS COD_SITUACAO
FROM
      WMWHSE5.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY COD_PEDIDO,
      OSH.WHSEID ARMAZEM,
      'WMS' COD_EVENTO_TERCE,
      MIN(OSH.ADDDATE) DATA_REGISTRO,
      OSH.STATUS COD_SITUACAO
FROM
      WMWHSE6.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY COD_PEDIDO,
      OSH.WHSEID ARMAZEM,
      'WMS' COD_EVENTO_TERCE,
      MIN(OSH.ADDDATE) DATA_REGISTRO,
      OSH.STATUS COD_SITUACAO
FROM
      WMWHSE7.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY COD_PEDIDO,
      OSH.WHSEID ARMAZEM,
      'WMS' COD_EVENTO_TERCE,
      MIN(OSH.ADDDATE) DATA_REGISTRO,
      OSH.STATUS COD_SITUACAO
FROM
      WMWHSE8.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY COD_PEDIDO,
      OSH.WHSEID ARMAZEM,
      'WMS' COD_EVENTO_TERCE,
      MIN(OSH.ADDDATE) DATA_REGISTRO,
      OSH.STATUS COD_SITUACAO
FROM
      WMWHSE9.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS