-- em 19/02/2015 o Fábio da INFOR informou que podíamos deixar
-- apenas um SELECT pois os códigos e descrições serão unificados
-- pelos usuários. A view original está trazendo códigos iguais 
-- com descrições diferentes - Rosana
SELECT DISTINCT COD_EVENTO as ETRK_ID_EVENTO, NOME_EVENTO as ETRK_NOME 
FROM
		(SELECT    
				  OSS.CODE COD_EVENTO,
				  OSS.DESCRIPTION NOME_EVENTO
		FROM      WMWHSE1.ORDERSTATUSSETUP OSS)
--		UNION SELECT    
--				  OSS.CODE COD_EVENTO,
--				  OSS.DESCRIPTION NOME_EVENTO
--		FROM      WMWHSE2.ORDERSTATUSSETUP OSS
--		UNION SELECT    
--				  OSS.CODE COD_EVENTO,
--				  OSS.DESCRIPTION NOME_EVENTO
--		FROM      WMWHSE3.ORDERSTATUSSETUP OSS
--		UNION SELECT    
--				  OSS.CODE COD_EVENTO,
--				  OSS.DESCRIPTION NOME_EVENTO
--		FROM      WMWHSE4.ORDERSTATUSSETUP OSS
--		UNION SELECT    
--				  OSS.CODE COD_EVENTO,
--				  OSS.DESCRIPTION NOME_EVENTO
--		FROM      WMWHSE5.ORDERSTATUSSETUP OSS
--		UNION SELECT    
--				  OSS.CODE COD_EVENTO,
--				  OSS.DESCRIPTION NOME_EVENTO
--		FROM      WMWHSE6.ORDERSTATUSSETUP OSS
--		UNION SELECT    
--				  OSS.CODE COD_EVENTO,
--				  OSS.DESCRIPTION NOME_EVENTO
--		FROM      WMWHSE7.ORDERSTATUSSETUP OSS
--		UNION SELECT    
--				  OSS.CODE COD_EVENTO,
--				  OSS.DESCRIPTION NOME_EVENTO
--		FROM      WMWHSE8.ORDERSTATUSSETUP OSS
--		UNION SELECT    
--				  OSS.CODE COD_EVENTO,
--				  OSS.DESCRIPTION NOME_EVENTO
--		FROM      WMWHSE9.ORDERSTATUSSETUP OSS)