SELECT
  WAVE.WAVEKEY      CD_ONDA, 
  WAVE.WHSEID       CD_ARMAZEM,
  ' '               CD_PROGRAMA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(WAVE.ADDDATE, 
    'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) 
                    DT_CADASTRO,
  W_COUNT.ORD_COUNT QT_PEDIDOS,
  W_COUNT.SKU_COUNT QT_ITENS,
  WAVE.STATUS       CD_SITUACAO_ONDA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(WAVE.EDITDATE, 
    'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) 
                    DT_ULT_ATUALIZACAO

FROM 	WMWHSE1.WAVE WAVE,

		(SELECT WAVEDETAIL.WAVEKEY, 
            COUNT(DISTINCT WAVEDETAIL.ORDERKEY) ORD_COUNT,
            COUNT(ORDERDETAIL.SKU) SKU_COUNT
      FROM WMWHSE2.WAVEDETAIL WAVEDETAIL, WMWHSE2.ORDERDETAIL ORDERDETAIL
        WHERE ORDERDETAIL.ORDERKEY=WAVEDETAIL.ORDERKEY
          GROUP BY WAVEDETAIL.WAVEKEY) W_COUNT
    
WHERE	W_COUNT.WAVEKEY=WAVE.WAVEKEY

UNION

SELECT
  WAVE.WAVEKEY      CD_ONDA, 
  WAVE.WHSEID       CD_ARMAZEM,
  ' '               CD_PROGRAMA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(WAVE.ADDDATE, 
    'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) 
                    DT_CADASTRO,
  W_COUNT.ORD_COUNT QT_PEDIDOS,
  W_COUNT.SKU_COUNT QT_ITENS,
  WAVE.STATUS       CD_SITUACAO_ONDA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(WAVE.EDITDATE, 
    'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) 
                    DT_ULT_ATUALIZACAO

FROM 	WMWHSE2.WAVE WAVE,

		(SELECT WAVEDETAIL.WAVEKEY, 
            COUNT(DISTINCT WAVEDETAIL.ORDERKEY) ORD_COUNT,
            COUNT(ORDERDETAIL.SKU) SKU_COUNT
      FROM WMWHSE2.WAVEDETAIL WAVEDETAIL, WMWHSE2.ORDERDETAIL ORDERDETAIL
        WHERE ORDERDETAIL.ORDERKEY=WAVEDETAIL.ORDERKEY
          GROUP BY WAVEDETAIL.WAVEKEY) W_COUNT
    
WHERE	W_COUNT.WAVEKEY=WAVE.WAVEKEY

UNION

SELECT
  WAVE.WAVEKEY      CD_ONDA, 
  WAVE.WHSEID       CD_ARMAZEM,
  ' '               CD_PROGRAMA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(WAVE.ADDDATE, 
    'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) 
                    DT_CADASTRO,
  W_COUNT.ORD_COUNT QT_PEDIDOS,
  W_COUNT.SKU_COUNT QT_ITENS,
  WAVE.STATUS       CD_SITUACAO_ONDA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(WAVE.EDITDATE, 
    'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) 
                    DT_ULT_ATUALIZACAO

FROM 	WMWHSE3.WAVE WAVE,

		(SELECT WAVEDETAIL.WAVEKEY, 
            COUNT(DISTINCT WAVEDETAIL.ORDERKEY) ORD_COUNT,
            COUNT(ORDERDETAIL.SKU) SKU_COUNT
      FROM WMWHSE2.WAVEDETAIL WAVEDETAIL, WMWHSE2.ORDERDETAIL ORDERDETAIL
        WHERE ORDERDETAIL.ORDERKEY=WAVEDETAIL.ORDERKEY
          GROUP BY WAVEDETAIL.WAVEKEY) W_COUNT
    
WHERE	W_COUNT.WAVEKEY=WAVE.WAVEKEY

UNION

SELECT 
  WAVE.WAVEKEY      CD_ONDA, 
  WAVE.WHSEID       CD_ARMAZEM,
  ' '               CD_PROGRAMA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(WAVE.ADDDATE, 
    'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) 
                    DT_CADASTRO,
  W_COUNT.ORD_COUNT QT_PEDIDOS,
  W_COUNT.SKU_COUNT QT_ITENS,
  WAVE.STATUS       CD_SITUACAO_ONDA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(WAVE.EDITDATE, 
    'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) 
                    DT_ULT_ATUALIZACAO

FROM 	WMWHSE4.WAVE WAVE,

		(SELECT WAVEDETAIL.WAVEKEY, 
            COUNT(DISTINCT WAVEDETAIL.ORDERKEY) ORD_COUNT,
            COUNT(ORDERDETAIL.SKU) SKU_COUNT
      FROM WMWHSE2.WAVEDETAIL WAVEDETAIL, WMWHSE2.ORDERDETAIL ORDERDETAIL
        WHERE ORDERDETAIL.ORDERKEY=WAVEDETAIL.ORDERKEY
          GROUP BY WAVEDETAIL.WAVEKEY) W_COUNT
    
WHERE	W_COUNT.WAVEKEY=WAVE.WAVEKEY

UNION

SELECT 
  WAVE.WAVEKEY      CD_ONDA, 
  WAVE.WHSEID       CD_ARMAZEM,
  ' '               CD_PROGRAMA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(WAVE.ADDDATE, 
    'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) 
                    DT_CADASTRO,
  W_COUNT.ORD_COUNT QT_PEDIDOS,
  W_COUNT.SKU_COUNT QT_ITENS,
  WAVE.STATUS       CD_SITUACAO_ONDA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(WAVE.EDITDATE, 
    'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) 
                    DT_ULT_ATUALIZACAO

FROM 	WMWHSE5.WAVE WAVE,

		(SELECT WAVEDETAIL.WAVEKEY, 
            COUNT(DISTINCT WAVEDETAIL.ORDERKEY) ORD_COUNT,
            COUNT(ORDERDETAIL.SKU) SKU_COUNT
      FROM WMWHSE2.WAVEDETAIL WAVEDETAIL, WMWHSE2.ORDERDETAIL ORDERDETAIL
        WHERE ORDERDETAIL.ORDERKEY=WAVEDETAIL.ORDERKEY
          GROUP BY WAVEDETAIL.WAVEKEY) W_COUNT
    
WHERE	W_COUNT.WAVEKEY=WAVE.WAVEKEY

UNION

SELECT 
  WAVE.WAVEKEY      CD_ONDA, 
  WAVE.WHSEID       CD_ARMAZEM,
  ' '               CD_PROGRAMA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(WAVE.ADDDATE, 
    'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) 
                    DT_CADASTRO,
  W_COUNT.ORD_COUNT QT_PEDIDOS,
  W_COUNT.SKU_COUNT QT_ITENS,
  WAVE.STATUS       CD_SITUACAO_ONDA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(WAVE.EDITDATE, 
    'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) 
                    DT_ULT_ATUALIZACAO

FROM 	WMWHSE6.WAVE WAVE,

		(SELECT WAVEDETAIL.WAVEKEY, 
            COUNT(DISTINCT WAVEDETAIL.ORDERKEY) ORD_COUNT,
            COUNT(ORDERDETAIL.SKU) SKU_COUNT
      FROM WMWHSE2.WAVEDETAIL WAVEDETAIL, WMWHSE2.ORDERDETAIL ORDERDETAIL
        WHERE ORDERDETAIL.ORDERKEY=WAVEDETAIL.ORDERKEY
          GROUP BY WAVEDETAIL.WAVEKEY) W_COUNT
    
WHERE	W_COUNT.WAVEKEY=WAVE.WAVEKEY

UNION

SELECT 
  WAVE.WAVEKEY      CD_ONDA, 
  WAVE.WHSEID       CD_ARMAZEM,
  ' '               CD_PROGRAMA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(WAVE.ADDDATE, 
    'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) 
                    DT_CADASTRO,
  W_COUNT.ORD_COUNT QT_PEDIDOS,
  W_COUNT.SKU_COUNT QT_ITENS,
  WAVE.STATUS       CD_SITUACAO_ONDA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(WAVE.EDITDATE, 
    'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) 
                    DT_ULT_ATUALIZACAO

FROM 	WMWHSE7.WAVE WAVE,

		(SELECT WAVEDETAIL.WAVEKEY, 
            COUNT(DISTINCT WAVEDETAIL.ORDERKEY) ORD_COUNT,
            COUNT(ORDERDETAIL.SKU) SKU_COUNT
      FROM WMWHSE2.WAVEDETAIL WAVEDETAIL, WMWHSE2.ORDERDETAIL ORDERDETAIL
        WHERE ORDERDETAIL.ORDERKEY=WAVEDETAIL.ORDERKEY
          GROUP BY WAVEDETAIL.WAVEKEY) W_COUNT
    
WHERE	W_COUNT.WAVEKEY=WAVE.WAVEKEY

UNION

SELECT 
  WAVE.WAVEKEY      CD_ONDA, 
  WAVE.WHSEID       CD_ARMAZEM,
  ' '               CD_PROGRAMA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(WAVE.ADDDATE, 
    'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) 
                    DT_CADASTRO,
  W_COUNT.ORD_COUNT QT_PEDIDOS,
  W_COUNT.SKU_COUNT QT_ITENS,
  WAVE.STATUS       CD_SITUACAO_ONDA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(WAVE.EDITDATE, 
    'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) 
                    DT_ULT_ATUALIZACAO

FROM 	WMWHSE8.WAVE WAVE,

		(SELECT WAVEDETAIL.WAVEKEY, 
            COUNT(DISTINCT WAVEDETAIL.ORDERKEY) ORD_COUNT,
            COUNT(ORDERDETAIL.SKU) SKU_COUNT
      FROM WMWHSE2.WAVEDETAIL WAVEDETAIL, WMWHSE2.ORDERDETAIL ORDERDETAIL
        WHERE ORDERDETAIL.ORDERKEY=WAVEDETAIL.ORDERKEY
          GROUP BY WAVEDETAIL.WAVEKEY) W_COUNT
    
WHERE	W_COUNT.WAVEKEY=WAVE.WAVEKEY

UNION

SELECT 
  WAVE.WAVEKEY      CD_ONDA, 
  WAVE.WHSEID       CD_ARMAZEM,
  ' '               CD_PROGRAMA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(WAVE.ADDDATE, 
    'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) 
                    DT_CADASTRO,
  W_COUNT.ORD_COUNT QT_PEDIDOS,
  W_COUNT.SKU_COUNT QT_ITENS,
  WAVE.STATUS       CD_SITUACAO_ONDA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(WAVE.EDITDATE, 
    'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) 
                    DT_ULT_ATUALIZACAO

FROM 	WMWHSE9.WAVE WAVE,

		(SELECT WAVEDETAIL.WAVEKEY, 
            COUNT(DISTINCT WAVEDETAIL.ORDERKEY) ORD_COUNT,
            COUNT(ORDERDETAIL.SKU) SKU_COUNT
      FROM WMWHSE2.WAVEDETAIL WAVEDETAIL, WMWHSE2.ORDERDETAIL ORDERDETAIL
        WHERE ORDERDETAIL.ORDERKEY=WAVEDETAIL.ORDERKEY
          GROUP BY WAVEDETAIL.WAVEKEY) W_COUNT
    
WHERE	W_COUNT.WAVEKEY=WAVE.WAVEKEY
