          SELECT 1 COD_EVENTO, 'WMS' COD_TERCEIRO, 'RECEBIMENTO DO HOST' COD_DESC FROM DUAL
UNION     SELECT 8 COD_EVENTO, 'SEC' COD_TERCEIRO, 'SAIDA EFETIVA DO CAMINHAO' COD_DESC FROM DUAL
UNION     SELECT 32 COD_EVENTO, 'GAI' COD_TERCEIRO, 'FECHAMENTO DE GAIOLA' COD_DESC FROM DUAL