--	FAF.004 - 13-jan-2014, Fabio Ferreira, 	Correcção registros duplicados
--	29/04/2015 - Correção Timezone - Rosana
--*******************************************************************************************************************************************
SELECT 
      OSH.ORDERKEY NR_PEDIDO,
      OSH.WHSEID CD_ARMAZEM,
      'WMS' CD_EVENTO_TERCEIRO,
      CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(MIN(OSH.ADDDATE), 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) DT_REGISTRO,
      OSH.STATUS CD_SITUACAO
FROM
      WMWHSE1.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY NR_PEDIDO,
      OSH.WHSEID CD_ARMAZEM,
      'WMS' CD_EVENTO_TERCEIRO,
      CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(MIN(OSH.ADDDATE), 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) DT_REGISTRO,
      OSH.STATUS CD_SITUACAO
FROM
      WMWHSE2.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY NR_PEDIDO,
      OSH.WHSEID CD_ARMAZEM,
      'WMS' CD_EVENTO_TERCEIRO,
      CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(MIN(OSH.ADDDATE), 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) DT_REGISTRO,
      OSH.STATUS CD_SITUACAO
FROM
      WMWHSE3.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY NR_PEDIDO,
      OSH.WHSEID CD_ARMAZEM,
      'WMS' CD_EVENTO_TERCEIRO,
      CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(MIN(OSH.ADDDATE), 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) DT_REGISTRO,
      OSH.STATUS CD_SITUACAO
FROM
      WMWHSE4.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY NR_PEDIDO,
      OSH.WHSEID CD_ARMAZEM,
      'WMS' CD_EVENTO_TERCEIRO,
      CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(MIN(OSH.ADDDATE), 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) DT_REGISTRO,
      OSH.STATUS CD_SITUACAO
FROM
      WMWHSE5.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY NR_PEDIDO,
      OSH.WHSEID CD_ARMAZEM,
      'WMS' CD_EVENTO_TERCEIRO,
      CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(MIN(OSH.ADDDATE), 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) DT_REGISTRO,
      OSH.STATUS CD_SITUACAO
FROM
      WMWHSE6.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY NR_PEDIDO,
      OSH.WHSEID CD_ARMAZEM,
      'WMS' CD_EVENTO_TERCEIRO,
      CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(MIN(OSH.ADDDATE), 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) DT_REGISTRO,
      OSH.STATUS CD_SITUACAO
FROM
      WMWHSE7.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY NR_PEDIDO,
      OSH.WHSEID CD_ARMAZEM,
      'WMS' CD_EVENTO_TERCEIRO,
      CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(MIN(OSH.ADDDATE), 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) DT_REGISTRO,
      OSH.STATUS CD_SITUACAO
FROM
      WMWHSE8.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY NR_PEDIDO,
      OSH.WHSEID CD_ARMAZEM,
      'WMS' CD_EVENTO_TERCEIRO,
      CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(MIN(OSH.ADDDATE), 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
      AT time zone 'America/Sao_Paulo') AS DATE) DT_REGISTRO,
      OSH.STATUS CD_SITUACAO
FROM
      WMWHSE9.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS