      Select 1 COD_STATUS_ITEM, 'A' NM_STATUS, 'Aberto' DESC_STATUS From Dual 
UNION Select 2 COD_STATUS_ITEM, 'L' NM_STATUS, 'Liquidado' DESC_STATUS From Dual
UNION Select 5 COD_STATUS_ITEM, 'C' NM_STATUS, 'Cancelado' DESC_STATUS From Dual