select 
	a. sku ITEM, 
	a.PACKKEY, 
	b.PALLETTI NUM_CAIXA_BASE_PALETE , 
	b.PALLETHI NUM_CAMADAS_PALETE ,
	CAST((FROM_TZ(CAST(TO_CHAR(a.EDITDATE, 'DD-MON-YYYY HH:MI:SS AM') AS TIMESTAMP), 'GMT') 
			AT time zone sessiontimezone) AS DATE) DT_ATUALIZACAO	
FROM ENTERPRISE.sku a, ENTERPRISE.pack b 
where b.PACKKEY=a.PACKKEY