--	FAF.004 - 13-jan-2014, Fabio Ferreira, 	Correcção registros duplicados
--*******************************************************************************************************************************************
SELECT 
      OSH.ORDERKEY NR_PEDIDO,
      OSH.WHSEID CD_ARMAZEM,
      'WMS' CD_EVENTO_TERCEIRO,
      MIN(OSH.ADDDATE) DT_REGISTRO,
      OSH.STATUS CD_SITUACAO
FROM
      WMWHSE1.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY NR_PEDIDO,
      OSH.WHSEID CD_ARMAZEM,
      'WMS' CD_EVENTO_TERCEIRO,
      MIN(OSH.ADDDATE) DT_REGISTRO,
      OSH.STATUS CD_SITUACAO
FROM
      WMWHSE2.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY NR_PEDIDO,
      OSH.WHSEID CD_ARMAZEM,
      'WMS' CD_EVENTO_TERCEIRO,
      MIN(OSH.ADDDATE) DT_REGISTRO,
      OSH.STATUS CD_SITUACAO
FROM
      WMWHSE3.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY NR_PEDIDO,
      OSH.WHSEID CD_ARMAZEM,
      'WMS' CD_EVENTO_TERCEIRO,
      MIN(OSH.ADDDATE) DT_REGISTRO,
      OSH.STATUS CD_SITUACAO
FROM
      WMWHSE4.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY NR_PEDIDO,
      OSH.WHSEID CD_ARMAZEM,
      'WMS' CD_EVENTO_TERCEIRO,
      MIN(OSH.ADDDATE) DT_REGISTRO,
      OSH.STATUS CD_SITUACAO
FROM
      WMWHSE5.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY NR_PEDIDO,
      OSH.WHSEID CD_ARMAZEM,
      'WMS' CD_EVENTO_TERCEIRO,
      MIN(OSH.ADDDATE) DT_REGISTRO,
      OSH.STATUS CD_SITUACAO
FROM
      WMWHSE6.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY NR_PEDIDO,
      OSH.WHSEID CD_ARMAZEM,
      'WMS' CD_EVENTO_TERCEIRO,
      MIN(OSH.ADDDATE) DT_REGISTRO,
      OSH.STATUS CD_SITUACAO
FROM
      WMWHSE7.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY NR_PEDIDO,
      OSH.WHSEID CD_ARMAZEM,
      'WMS' CD_EVENTO_TERCEIRO,
      MIN(OSH.ADDDATE) DT_REGISTRO,
      OSH.STATUS CD_SITUACAO
FROM
      WMWHSE8.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS
UNION SELECT 
      OSH.ORDERKEY NR_PEDIDO,
      OSH.WHSEID CD_ARMAZEM,
      'WMS' CD_EVENTO_TERCEIRO,
      MIN(OSH.ADDDATE) DT_REGISTRO,
      OSH.STATUS CD_SITUACAO
FROM
      WMWHSE9.ORDERSTATUSHISTORY OSH
GROUP BY OSH.ORDERKEY, OSH.WHSEID, OSH.STATUS