SELECT  OSH.SERIALKEY COD_TRACKING,
        OSH.ORDERKEY COD_PEDIDO_WMS,
		OSH.WHSEID ARMAZEM,
        OSH.STATUS COD_EVENTO,
        'WMS' COD_SIST_HOST,
        OSH.ADDDATE DT_INCL_TRACKING
FROM    WMWHSE1.ORDERSTATUSHISTORY OSH 
UNION SELECT  OSH.SERIALKEY COD_TRACKING,
        OSH.ORDERKEY COD_PEDIDO_WMS,
		OSH.WHSEID ARMAZEM,
        OSH.STATUS COD_EVENTO,
        'WMS' COD_SIST_HOST,
        OSH.ADDDATE DT_INCL_TRACKING
FROM    WMWHSE2.ORDERSTATUSHISTORY OSH 
UNION SELECT  OSH.SERIALKEY COD_TRACKING,
        OSH.ORDERKEY COD_PEDIDO_WMS,
		OSH.WHSEID ARMAZEM,
        OSH.STATUS COD_EVENTO,
        'WMS' COD_SIST_HOST,
        OSH.ADDDATE DT_INCL_TRACKING
FROM    WMWHSE3.ORDERSTATUSHISTORY OSH
UNION SELECT  OSH.SERIALKEY COD_TRACKING,
        OSH.ORDERKEY COD_PEDIDO_WMS,
		OSH.WHSEID ARMAZEM,
        OSH.STATUS COD_EVENTO,
        'WMS' COD_SIST_HOST,
        OSH.ADDDATE DT_INCL_TRACKING
FROM    WMWHSE4.ORDERSTATUSHISTORY OSH
UNION SELECT  OSH.SERIALKEY COD_TRACKING,
        OSH.ORDERKEY COD_PEDIDO_WMS,
		OSH.WHSEID ARMAZEM,
        OSH.STATUS COD_EVENTO,
        'WMS' COD_SIST_HOST,
        OSH.ADDDATE DT_INCL_TRACKING
FROM    WMWHSE5.ORDERSTATUSHISTORY OSH
UNION SELECT  OSH.SERIALKEY COD_TRACKING,
        OSH.ORDERKEY COD_PEDIDO_WMS,
		OSH.WHSEID ARMAZEM,
        OSH.STATUS COD_EVENTO,
        'WMS' COD_SIST_HOST,
        OSH.ADDDATE DT_INCL_TRACKING
FROM    WMWHSE6.ORDERSTATUSHISTORY OSH
UNION SELECT  OSH.SERIALKEY COD_TRACKING,
        OSH.ORDERKEY COD_PEDIDO_WMS,
		OSH.WHSEID ARMAZEM,
        OSH.STATUS COD_EVENTO,
        'WMS' COD_SIST_HOST,
        OSH.ADDDATE DT_INCL_TRACKING
FROM    WMWHSE7.ORDERSTATUSHISTORY OSH
UNION SELECT  OSH.SERIALKEY COD_TRACKING,
        OSH.ORDERKEY COD_PEDIDO_WMS,
		OSH.WHSEID ARMAZEM,
        OSH.STATUS COD_EVENTO,
        'WMS' COD_SIST_HOST,
        OSH.ADDDATE DT_INCL_TRACKING
FROM    WMWHSE8.ORDERSTATUSHISTORY OSH
UNION SELECT  OSH.SERIALKEY COD_TRACKING,
        OSH.ORDERKEY COD_PEDIDO_WMS,
		OSH.WHSEID ARMAZEM,
        OSH.STATUS COD_EVENTO,
        'WMS' COD_SIST_HOST,
        OSH.ADDDATE DT_INCL_TRACKING
FROM    WMWHSE9.ORDERSTATUSHISTORY OSH