SELECT DISTINCT COD_EVENTO, NOME_EVENTO
FROM
		(SELECT    
				  OSS.CODE COD_EVENTO,
				  OSS.DESCRIPTION NOME_EVENTO
		FROM      WMWHSE1.ORDERSTATUSSETUP OSS
		UNION SELECT    
				  OSS.CODE COD_EVENTO,
				  OSS.DESCRIPTION NOME_EVENTO
		FROM      WMWHSE2.ORDERSTATUSSETUP OSS
		UNION SELECT    
				  OSS.CODE COD_EVENTO,
				  OSS.DESCRIPTION NOME_EVENTO
		FROM      WMWHSE3.ORDERSTATUSSETUP OSS
		UNION SELECT    
				  OSS.CODE COD_EVENTO,
				  OSS.DESCRIPTION NOME_EVENTO
		FROM      WMWHSE4.ORDERSTATUSSETUP OSS
		UNION SELECT    
				  OSS.CODE COD_EVENTO,
				  OSS.DESCRIPTION NOME_EVENTO
		FROM      WMWHSE5.ORDERSTATUSSETUP OSS
		UNION SELECT    
				  OSS.CODE COD_EVENTO,
				  OSS.DESCRIPTION NOME_EVENTO
		FROM      WMWHSE6.ORDERSTATUSSETUP OSS
		UNION SELECT    
				  OSS.CODE COD_EVENTO,
				  OSS.DESCRIPTION NOME_EVENTO
		FROM      WMWHSE7.ORDERSTATUSSETUP OSS
		UNION SELECT    
				  OSS.CODE COD_EVENTO,
				  OSS.DESCRIPTION NOME_EVENTO
		FROM      WMWHSE8.ORDERSTATUSSETUP OSS
		UNION SELECT    
				  OSS.CODE COD_EVENTO,
				  OSS.DESCRIPTION NOME_EVENTO
		FROM      WMWHSE9.ORDERSTATUSSETUP OSS)