SELECT
 ZNFMD001.T$FILI$C FILIAL,
 ll.sku CD_SKU,
 ll.sku CD_ITEM,
 CASE WHEN TO_CHAR(ll.holdreason)=' '
  THEN 'WN' 
  ELSE TO_CHAR(ll.holdreason) END CD_BLOQUEIO,
 pz.PUTAWAYZONE CD_CLASSE_LOCAL,
-- pz.DESCR CLAL,
 ll.loc CD_LOCAL,
 subStr(cl.DESCRIPTION,3,6) CD_ARMAZEM,
 sum(llid.qty) QT_PC,
 sum(llid.netwgt) QT_PESO,
 sum(sku.STDCUBE*ll.qty) QT_M3
FROM WMWHSE1.lotxloc ll,
 WMWHSE1.lotxlocxid llid,
 WMWHSE1.sku,
 WMWHSE1.loc
 LEFT JOIN WMWHSE1.PUTAWAYZONE pz on pz.PUTAWAYZONE=loc.PUTAWAYZONE,
 ENTERPRISE.CODELKUP cl
 LEFT JOIN BAANDB.TTCEMM300301@PLN01 TCEMM300 ON  TCEMM300.T$LCTN = CL.LONG_VALUE
                                              AND TCEMM300.T$COMP = 301
                                              AND TCEMM300.T$TYPE = 20
 LEFT JOIN BAANDB.TTCMCS003301@PLN01 TCMCS003 ON  TCMCS003.T$CWAR = TCEMM300.T$CODE
 LEFT JOIN BAANDB.TTCCOM130301@PLN01 TCCOM130 ON  TCCOM130.T$CADR = TCMCS003.T$CADR
 LEFT JOIN BAANDB.TZNFMD001301@PLN01 ZNFMD001 ON  ZNFMD001.T$FOVN$C = TCCOM130.T$FOVN$L
WHERE llid.sku=ll.sku
AND llid.loc=ll.loc
AND sku.SKU=ll.SKU
AND llid.WHSEID=sku.WHSEID
AND ll.loc=loc.loc
AND cl.LISTNAME = 'SCHEMA'
AND UPPER(cl.UDF1)=llid.WHSEID
GROUP BY
 ZNFMD001.T$FILI$C,
 ll.sku,
 ll.sku,
 ll.holdreason,
 pz.PUTAWAYZONE,
 ll.loc,
 cl.DESCRIPTION
--******************************************************************************************
UNION
SELECT
 ZNFMD001.T$FILI$C FILIAL,
 ll.sku CD_SKU,
 ll.sku CD_ITEM,
 CASE WHEN TO_CHAR(ll.holdreason)=' '
  THEN 'WN' 
  ELSE TO_CHAR(ll.holdreason) END CD_BLOQUEIO,
 pz.PUTAWAYZONE CD_CLASSE_LOCAL,
-- pz.DESCR CLAL,
 ll.loc CD_LOCAL,
 subStr(cl.DESCRIPTION,3,6) CD_ARMAZEM,
 sum(llid.qty) QT_PC,
 sum(llid.netwgt) QT_PESO,
 sum(sku.STDCUBE*ll.qty) QT_M3
FROM WMWHSE2.lotxloc ll,
 WMWHSE2.lotxlocxid llid,
 WMWHSE2.sku,
 WMWHSE2.loc
 LEFT JOIN WMWHSE2.PUTAWAYZONE pz on pz.PUTAWAYZONE=loc.PUTAWAYZONE,
 ENTERPRISE.CODELKUP cl
 LEFT JOIN BAANDB.TTCEMM300301@PLN01 TCEMM300 ON  TCEMM300.T$LCTN = CL.LONG_VALUE
                                              AND TCEMM300.T$COMP = 301
                                              AND TCEMM300.T$TYPE = 20
 LEFT JOIN BAANDB.TTCMCS003301@PLN01 TCMCS003 ON  TCMCS003.T$CWAR = TCEMM300.T$CODE
 LEFT JOIN BAANDB.TTCCOM130301@PLN01 TCCOM130 ON  TCCOM130.T$CADR = TCMCS003.T$CADR
 LEFT JOIN BAANDB.TZNFMD001301@PLN01 ZNFMD001 ON  ZNFMD001.T$FOVN$C = TCCOM130.T$FOVN$L
WHERE llid.sku=ll.sku
AND llid.loc=ll.loc
AND sku.SKU=ll.SKU
AND llid.WHSEID=sku.WHSEID
AND ll.loc=loc.loc
AND cl.LISTNAME = 'SCHEMA'
AND UPPER(cl.UDF1)=llid.WHSEID
GROUP BY
 ZNFMD001.T$FILI$C,
 ll.sku,
 ll.sku,
 ll.holdreason,
 pz.PUTAWAYZONE,
 ll.loc,
 cl.DESCRIPTION
--******************************************************************************************
UNION
SELECT
 ZNFMD001.T$FILI$C FILIAL,
 ll.sku CD_SKU,
 ll.sku CD_ITEM,
 CASE WHEN TO_CHAR(ll.holdreason)=' '
  THEN 'WN' 
  ELSE TO_CHAR(ll.holdreason) END CD_BLOQUEIO,
 pz.PUTAWAYZONE CD_CLASSE_LOCAL,
-- pz.DESCR CLAL,
 ll.loc CD_LOCAL,
 subStr(cl.DESCRIPTION,3,6) CD_ARMAZEM,
 sum(llid.qty) QT_PC,
 sum(llid.netwgt) QT_PESO,
 sum(sku.STDCUBE*ll.qty) QT_M3
FROM WMWHSE3.lotxloc ll,
 WMWHSE3.lotxlocxid llid,
 WMWHSE3.sku,
 WMWHSE3.loc
 LEFT JOIN WMWHSE3.PUTAWAYZONE pz on pz.PUTAWAYZONE=loc.PUTAWAYZONE,
 ENTERPRISE.CODELKUP cl
 LEFT JOIN BAANDB.TTCEMM300301@PLN01 TCEMM300 ON  TCEMM300.T$LCTN = CL.LONG_VALUE
                                              AND TCEMM300.T$COMP = 301
                                              AND TCEMM300.T$TYPE = 20
 LEFT JOIN BAANDB.TTCMCS003301@PLN01 TCMCS003 ON  TCMCS003.T$CWAR = TCEMM300.T$CODE
 LEFT JOIN BAANDB.TTCCOM130301@PLN01 TCCOM130 ON  TCCOM130.T$CADR = TCMCS003.T$CADR
 LEFT JOIN BAANDB.TZNFMD001301@PLN01 ZNFMD001 ON  ZNFMD001.T$FOVN$C = TCCOM130.T$FOVN$L
WHERE llid.sku=ll.sku
AND llid.loc=ll.loc
AND sku.SKU=ll.SKU
AND llid.WHSEID=sku.WHSEID
AND ll.loc=loc.loc
AND cl.LISTNAME = 'SCHEMA'
AND UPPER(cl.UDF1)=llid.WHSEID
GROUP BY
 ZNFMD001.T$FILI$C,
 ll.sku,
 ll.sku,
 ll.holdreason,
 pz.PUTAWAYZONE,
 ll.loc,
 cl.DESCRIPTION
--******************************************************************************************
UNION
SELECT
 ZNFMD001.T$FILI$C FILIAL,
 ll.sku CD_SKU,
 ll.sku CD_ITEM,
 CASE WHEN TO_CHAR(ll.holdreason)=' '
  THEN 'WN' 
  ELSE TO_CHAR(ll.holdreason) END CD_BLOQUEIO,
 pz.PUTAWAYZONE CD_CLASSE_LOCAL,
-- pz.DESCR CLAL,
 ll.loc CD_LOCAL,
 subStr(cl.DESCRIPTION,3,6) CD_ARMAZEM,
 sum(llid.qty) QT_PC,
 sum(llid.netwgt) QT_PESO,
 sum(sku.STDCUBE*ll.qty) QT_M3
FROM WMWHSE4.lotxloc ll,
 WMWHSE4.lotxlocxid llid,
 WMWHSE4.sku,
 WMWHSE4.loc
 LEFT JOIN WMWHSE4.PUTAWAYZONE pz on pz.PUTAWAYZONE=loc.PUTAWAYZONE,
 ENTERPRISE.CODELKUP cl
 LEFT JOIN BAANDB.TTCEMM300301@PLN01 TCEMM300 ON  TCEMM300.T$LCTN = CL.LONG_VALUE
                                              AND TCEMM300.T$COMP = 301
                                              AND TCEMM300.T$TYPE = 20
 LEFT JOIN BAANDB.TTCMCS003301@PLN01 TCMCS003 ON  TCMCS003.T$CWAR = TCEMM300.T$CODE
 LEFT JOIN BAANDB.TTCCOM130301@PLN01 TCCOM130 ON  TCCOM130.T$CADR = TCMCS003.T$CADR
 LEFT JOIN BAANDB.TZNFMD001301@PLN01 ZNFMD001 ON  ZNFMD001.T$FOVN$C = TCCOM130.T$FOVN$L
WHERE llid.sku=ll.sku
AND llid.loc=ll.loc
AND sku.SKU=ll.SKU
AND llid.WHSEID=sku.WHSEID
AND ll.loc=loc.loc
AND cl.LISTNAME = 'SCHEMA'
AND UPPER(cl.UDF1)=llid.WHSEID
GROUP BY
 ZNFMD001.T$FILI$C,
 ll.sku,
 ll.sku,
 ll.holdreason,
 pz.PUTAWAYZONE,
 ll.loc,
 cl.DESCRIPTION
 --******************************************************************************************
UNION
SELECT
 ZNFMD001.T$FILI$C FILIAL,
 ll.sku CD_SKU,
 ll.sku CD_ITEM,
 CASE WHEN TO_CHAR(ll.holdreason)=' '
  THEN 'WN' 
  ELSE TO_CHAR(ll.holdreason) END CD_BLOQUEIO,
 pz.PUTAWAYZONE CD_CLASSE_LOCAL,
-- pz.DESCR CLAL,
 ll.loc CD_LOCAL,
 subStr(cl.DESCRIPTION,3,6) CD_ARMAZEM,
 sum(llid.qty) QT_PC,
 sum(llid.netwgt) QT_PESO,
 sum(sku.STDCUBE*ll.qty) QT_M3
FROM WMWHSE5.lotxloc ll,
 WMWHSE5.lotxlocxid llid,
 WMWHSE5.sku,
 WMWHSE5.loc
 LEFT JOIN WMWHSE5.PUTAWAYZONE pz on pz.PUTAWAYZONE=loc.PUTAWAYZONE,
 ENTERPRISE.CODELKUP cl
 LEFT JOIN BAANDB.TTCEMM300301@PLN01 TCEMM300 ON  TCEMM300.T$LCTN = CL.LONG_VALUE
                                              AND TCEMM300.T$COMP = 301
                                              AND TCEMM300.T$TYPE = 20
 LEFT JOIN BAANDB.TTCMCS003301@PLN01 TCMCS003 ON  TCMCS003.T$CWAR = TCEMM300.T$CODE
 LEFT JOIN BAANDB.TTCCOM130301@PLN01 TCCOM130 ON  TCCOM130.T$CADR = TCMCS003.T$CADR
 LEFT JOIN BAANDB.TZNFMD001301@PLN01 ZNFMD001 ON  ZNFMD001.T$FOVN$C = TCCOM130.T$FOVN$L
WHERE llid.sku=ll.sku
AND llid.loc=ll.loc
AND sku.SKU=ll.SKU
AND llid.WHSEID=sku.WHSEID
AND ll.loc=loc.loc
AND cl.LISTNAME = 'SCHEMA'
AND UPPER(cl.UDF1)=llid.WHSEID
GROUP BY
 ZNFMD001.T$FILI$C,
 ll.sku,
 ll.sku,
 ll.holdreason,
 pz.PUTAWAYZONE,
 ll.loc,
 cl.DESCRIPTION
 --******************************************************************************************
UNION
SELECT
 ZNFMD001.T$FILI$C FILIAL,
 ll.sku CD_SKU,
 ll.sku CD_ITEM,
 CASE WHEN TO_CHAR(ll.holdreason)=' '
  THEN 'WN' 
  ELSE TO_CHAR(ll.holdreason) END CD_BLOQUEIO,
 pz.PUTAWAYZONE CD_CLASSE_LOCAL,
-- pz.DESCR CLAL,
 ll.loc CD_LOCAL,
 subStr(cl.DESCRIPTION,3,6) CD_ARMAZEM,
 sum(llid.qty) QT_PC,
 sum(llid.netwgt) QT_PESO,
 sum(sku.STDCUBE*ll.qty) QT_M3
FROM WMWHSE6.lotxloc ll,
 WMWHSE6.lotxlocxid llid,
 WMWHSE6.sku,
 WMWHSE6.loc
 LEFT JOIN WMWHSE6.PUTAWAYZONE pz on pz.PUTAWAYZONE=loc.PUTAWAYZONE,
 ENTERPRISE.CODELKUP cl
 LEFT JOIN BAANDB.TTCEMM300301@PLN01 TCEMM300 ON  TCEMM300.T$LCTN = CL.LONG_VALUE
                                              AND TCEMM300.T$COMP = 301
                                              AND TCEMM300.T$TYPE = 20
 LEFT JOIN BAANDB.TTCMCS003301@PLN01 TCMCS003 ON  TCMCS003.T$CWAR = TCEMM300.T$CODE
 LEFT JOIN BAANDB.TTCCOM130301@PLN01 TCCOM130 ON  TCCOM130.T$CADR = TCMCS003.T$CADR
 LEFT JOIN BAANDB.TZNFMD001301@PLN01 ZNFMD001 ON  ZNFMD001.T$FOVN$C = TCCOM130.T$FOVN$L
WHERE llid.sku=ll.sku
AND llid.loc=ll.loc
AND sku.SKU=ll.SKU
AND llid.WHSEID=sku.WHSEID
AND ll.loc=loc.loc
AND cl.LISTNAME = 'SCHEMA'
AND UPPER(cl.UDF1)=llid.WHSEID
GROUP BY
 ZNFMD001.T$FILI$C,
 ll.sku,
 ll.sku,
 ll.holdreason,
 pz.PUTAWAYZONE,
 ll.loc,
 cl.DESCRIPTION
 --******************************************************************************************
UNION
SELECT
 ZNFMD001.T$FILI$C FILIAL,
 ll.sku CD_SKU,
 ll.sku CD_ITEM,
 CASE WHEN TO_CHAR(ll.holdreason)=' '
  THEN 'WN' 
  ELSE TO_CHAR(ll.holdreason) END CD_BLOQUEIO,
 pz.PUTAWAYZONE CD_CLASSE_LOCAL,
-- pz.DESCR CLAL,
 ll.loc CD_LOCAL,
 subStr(cl.DESCRIPTION,3,6) CD_ARMAZEM,
 sum(llid.qty) QT_PC,
 sum(llid.netwgt) QT_PESO,
 sum(sku.STDCUBE*ll.qty) QT_M3
FROM WMWHSE7.lotxloc ll,
 WMWHSE7.lotxlocxid llid,
 WMWHSE7.sku,
 WMWHSE7.loc
 LEFT JOIN WMWHSE7.PUTAWAYZONE pz on pz.PUTAWAYZONE=loc.PUTAWAYZONE,
 ENTERPRISE.CODELKUP cl
 LEFT JOIN BAANDB.TTCEMM300301@PLN01 TCEMM300 ON  TCEMM300.T$LCTN = CL.LONG_VALUE
                                              AND TCEMM300.T$COMP = 301
                                              AND TCEMM300.T$TYPE = 20
 LEFT JOIN BAANDB.TTCMCS003301@PLN01 TCMCS003 ON  TCMCS003.T$CWAR = TCEMM300.T$CODE
 LEFT JOIN BAANDB.TTCCOM130301@PLN01 TCCOM130 ON  TCCOM130.T$CADR = TCMCS003.T$CADR
 LEFT JOIN BAANDB.TZNFMD001301@PLN01 ZNFMD001 ON  ZNFMD001.T$FOVN$C = TCCOM130.T$FOVN$L
WHERE llid.sku=ll.sku
AND llid.loc=ll.loc
AND sku.SKU=ll.SKU
AND llid.WHSEID=sku.WHSEID
AND ll.loc=loc.loc
AND cl.LISTNAME = 'SCHEMA'
AND UPPER(cl.UDF1)=llid.WHSEID
GROUP BY
 ZNFMD001.T$FILI$C,
 ll.sku,
 ll.sku,
 ll.holdreason,
 pz.PUTAWAYZONE,
 ll.loc,
 cl.DESCRIPTION
 --******************************************************************************************
UNION
SELECT
 ZNFMD001.T$FILI$C FILIAL,
 ll.sku CD_SKU,
 ll.sku CD_ITEM,
 CASE WHEN TO_CHAR(ll.holdreason)=' '
  THEN 'WN' 
  ELSE TO_CHAR(ll.holdreason) END CD_BLOQUEIO,
 pz.PUTAWAYZONE CD_CLASSE_LOCAL,
-- pz.DESCR CLAL,
 ll.loc CD_LOCAL,
 subStr(cl.DESCRIPTION,3,6) CD_ARMAZEM,
 sum(llid.qty) QT_PC,
 sum(llid.netwgt) QT_PESO,
 sum(sku.STDCUBE*ll.qty) QT_M3
FROM WMWHSE8.lotxloc ll,
 WMWHSE8.lotxlocxid llid,
 WMWHSE8.sku,
 WMWHSE8.loc
 LEFT JOIN WMWHSE8.PUTAWAYZONE pz on pz.PUTAWAYZONE=loc.PUTAWAYZONE,
 ENTERPRISE.CODELKUP cl
 LEFT JOIN BAANDB.TTCEMM300301@PLN01 TCEMM300 ON  TCEMM300.T$LCTN = CL.LONG_VALUE
                                              AND TCEMM300.T$COMP = 301
                                              AND TCEMM300.T$TYPE = 20
 LEFT JOIN BAANDB.TTCMCS003301@PLN01 TCMCS003 ON  TCMCS003.T$CWAR = TCEMM300.T$CODE
 LEFT JOIN BAANDB.TTCCOM130301@PLN01 TCCOM130 ON  TCCOM130.T$CADR = TCMCS003.T$CADR
 LEFT JOIN BAANDB.TZNFMD001301@PLN01 ZNFMD001 ON  ZNFMD001.T$FOVN$C = TCCOM130.T$FOVN$L
WHERE llid.sku=ll.sku
AND llid.loc=ll.loc
AND sku.SKU=ll.SKU
AND llid.WHSEID=sku.WHSEID
AND ll.loc=loc.loc
AND cl.LISTNAME = 'SCHEMA'
AND UPPER(cl.UDF1)=llid.WHSEID
GROUP BY
 ZNFMD001.T$FILI$C,
 ll.sku,
 ll.sku,
 ll.holdreason,
 pz.PUTAWAYZONE,
 ll.loc,
 cl.DESCRIPTION
 --******************************************************************************************
UNION
SELECT
 ZNFMD001.T$FILI$C FILIAL,
 ll.sku CD_SKU,
 ll.sku CD_ITEM,
 CASE WHEN TO_CHAR(ll.holdreason)=' '
  THEN 'WN' 
  ELSE TO_CHAR(ll.holdreason) END CD_BLOQUEIO,
 pz.PUTAWAYZONE CD_CLASSE_LOCAL,
-- pz.DESCR CLAL,
 ll.loc CD_LOCAL,
 subStr(cl.DESCRIPTION,3,6) CD_ARMAZEM,
 sum(llid.qty) QT_PC,
 sum(llid.netwgt) QT_PESO,
 sum(sku.STDCUBE*ll.qty) QT_M3
FROM WMWHSE9.lotxloc ll,
 WMWHSE9.lotxlocxid llid,
 WMWHSE9.sku,
 WMWHSE9.loc
 LEFT JOIN WMWHSE9.PUTAWAYZONE pz on pz.PUTAWAYZONE=loc.PUTAWAYZONE,
 ENTERPRISE.CODELKUP cl
 LEFT JOIN BAANDB.TTCEMM300301@PLN01 TCEMM300 ON  TCEMM300.T$LCTN = CL.LONG_VALUE
                                              AND TCEMM300.T$COMP = 301
                                              AND TCEMM300.T$TYPE = 20
 LEFT JOIN BAANDB.TTCMCS003301@PLN01 TCMCS003 ON  TCMCS003.T$CWAR = TCEMM300.T$CODE
 LEFT JOIN BAANDB.TTCCOM130301@PLN01 TCCOM130 ON  TCCOM130.T$CADR = TCMCS003.T$CADR
 LEFT JOIN BAANDB.TZNFMD001301@PLN01 ZNFMD001 ON  ZNFMD001.T$FOVN$C = TCCOM130.T$FOVN$L
WHERE llid.sku=ll.sku
AND llid.loc=ll.loc
AND sku.SKU=ll.SKU
AND llid.WHSEID=sku.WHSEID
AND ll.loc=loc.loc
AND cl.LISTNAME = 'SCHEMA'
AND UPPER(cl.UDF1)=llid.WHSEID
GROUP BY
 ZNFMD001.T$FILI$C,
 ll.sku,
 ll.sku,
 ll.holdreason,
 pz.PUTAWAYZONE,
 ll.loc,
 cl.DESCRIPTION