SELECT  OSH.SERIALKEY CD_TRACKING,
        OSH.ORDERKEY NR_PEDIDO_WMS,
		OSH.WHSEID CD_ARMAZEM,
        OSH.STATUS CD_OCORRENCIA,
        'WMS' CD_SISTEMA_HOST,
        OSH.ADDDATE DT_INCLUSAO_TRACKING
FROM    WMWHSE1.ORDERSTATUSHISTORY OSH 
UNION SELECT  OSH.SERIALKEY CD_TRACKING,
        OSH.ORDERKEY NR_PEDIDO_WMS,
		OSH.WHSEID CD_ARMAZEM,
        OSH.STATUS CD_OCORRENCIA,
        'WMS' CD_SISTEMA_HOST,
        OSH.ADDDATE DT_INCLUSAO_TRACKING
FROM    WMWHSE2.ORDERSTATUSHISTORY OSH 
UNION SELECT  OSH.SERIALKEY CD_TRACKING,
        OSH.ORDERKEY NR_PEDIDO_WMS,
		OSH.WHSEID CD_ARMAZEM,
        OSH.STATUS CD_OCORRENCIA,
        'WMS' CD_SISTEMA_HOST,
        OSH.ADDDATE DT_INCLUSAO_TRACKING
FROM    WMWHSE3.ORDERSTATUSHISTORY OSH
UNION SELECT  OSH.SERIALKEY CD_TRACKING,
        OSH.ORDERKEY NR_PEDIDO_WMS,
		OSH.WHSEID CD_ARMAZEM,
        OSH.STATUS CD_OCORRENCIA,
        'WMS' CD_SISTEMA_HOST,
        OSH.ADDDATE DT_INCLUSAO_TRACKING
FROM    WMWHSE4.ORDERSTATUSHISTORY OSH
UNION SELECT  OSH.SERIALKEY CD_TRACKING,
        OSH.ORDERKEY NR_PEDIDO_WMS,
		OSH.WHSEID CD_ARMAZEM,
        OSH.STATUS CD_OCORRENCIA,
        'WMS' CD_SISTEMA_HOST,
        OSH.ADDDATE DT_INCLUSAO_TRACKING
FROM    WMWHSE5.ORDERSTATUSHISTORY OSH
UNION SELECT  OSH.SERIALKEY CD_TRACKING,
        OSH.ORDERKEY NR_PEDIDO_WMS,
		OSH.WHSEID CD_ARMAZEM,
        OSH.STATUS CD_OCORRENCIA,
        'WMS' CD_SISTEMA_HOST,
        OSH.ADDDATE DT_INCLUSAO_TRACKING
FROM    WMWHSE6.ORDERSTATUSHISTORY OSH
UNION SELECT  OSH.SERIALKEY CD_TRACKING,
        OSH.ORDERKEY NR_PEDIDO_WMS,
		OSH.WHSEID CD_ARMAZEM,
        OSH.STATUS CD_OCORRENCIA,
        'WMS' CD_SISTEMA_HOST,
        OSH.ADDDATE DT_INCLUSAO_TRACKING
FROM    WMWHSE7.ORDERSTATUSHISTORY OSH
UNION SELECT  OSH.SERIALKEY CD_TRACKING,
        OSH.ORDERKEY NR_PEDIDO_WMS,
		OSH.WHSEID CD_ARMAZEM,
        OSH.STATUS CD_OCORRENCIA,
        'WMS' CD_SISTEMA_HOST,
        OSH.ADDDATE DT_INCLUSAO_TRACKING
FROM    WMWHSE8.ORDERSTATUSHISTORY OSH
UNION SELECT  OSH.SERIALKEY CD_TRACKING,
        OSH.ORDERKEY NR_PEDIDO_WMS,
		OSH.WHSEID CD_ARMAZEM,
        OSH.STATUS CD_OCORRENCIA,
        'WMS' CD_SISTEMA_HOST,
        OSH.ADDDATE DT_INCLUSAO_TRACKING
FROM    WMWHSE9.ORDERSTATUSHISTORY OSH