--	FAF.004 - 13-jan-2014, Fabio Ferreira, 	Correção timezone
--									
--*******************************************************************************************************************************************
SELECT
      OD.ORDERKEY COD_PEDIDO_WMS, O.WHSEID ARMAZEM,
      SUM(O.TOTALQTY) NUM_VOLUME,
      (SELECT MIN(OSH.ADDDATE) FROM WMWHSE1.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.STATUS>=51) DT_INICIO_PICKING,
      SUM(OD.QTYPICKED) NUM_VOL_FINALIZADOS,
      SUM(OD.SHIPPEDQTY) NUM_VOL_CONFERIDOS,
      (SELECT OSH.STATUS FROM WMWHSE1.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.ADDDATE=(SELECT MAX(OSH2.ADDDATE) FROM WMWHSE1.ORDERSTATUSHISTORY OSH2 
                                                       WHERE OSH2.ORDERKEY=OSH.ORDERKEY)
       AND ROWNUM=1) COD_ULTIMO_EVENTO,
      (SELECT 
		CAST((FROM_TZ(CAST(TO_CHAR(MIN(OSH.ADDDATE), 'DD-MON-YYYY HH:MI:SS AM') AS TIMESTAMP), 'GMT')
		AT time zone sessiontimezone) AS DATE)	  
		FROM WMWHSE1.ORDERSTATUSHISTORY OSH 
		WHERE OSH.ORDERKEY=OD.ORDERKEY) DT_ULTIMO_EVENTO,
       O.EXTERNORDERKEY,
       O.CARRIERCODE,
      (SELECT OSH.SERIALKEY FROM WMWHSE1.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.ADDDATE=(SELECT MAX(OSH2.ADDDATE) FROM WMWHSE1.ORDERSTATUSHISTORY OSH2 
                                                       WHERE OSH2.ORDERKEY=OSH.ORDERKEY)
       AND ROWNUM=1) COD_ULTIMO_TRACKING      
FROM
      WMWHSE1.ORDERDETAIL OD,
      WMWHSE1.ORDERS O
WHERE O.ORDERKEY=OD.ORDERKEY
GROUP BY OD.ORDERKEY, O.EXTERNORDERKEY, O.CARRIERCODE, O.WHSEID
UNION SELECT
      OD.ORDERKEY COD_PEDIDO_WMS, O.WHSEID ARMAZEM,
      SUM(O.TOTALQTY) NUM_VOLUME,
      (SELECT MIN(OSH.ADDDATE) FROM WMWHSE2.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.STATUS>=51) DT_INICIO_PICKING,
      SUM(OD.QTYPICKED) NUM_VOL_FINALIZADOS,
      SUM(OD.SHIPPEDQTY) NUM_VOL_CONFERIDOS,
      (SELECT OSH.STATUS FROM WMWHSE2.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.ADDDATE=(SELECT MAX(OSH2.ADDDATE) FROM WMWHSE2.ORDERSTATUSHISTORY OSH2 
                                                       WHERE OSH2.ORDERKEY=OSH.ORDERKEY)
       AND ROWNUM=1) COD_ULTIMO_EVENTO,
      (SELECT 
		CAST((FROM_TZ(CAST(TO_CHAR(MIN(OSH.ADDDATE), 'DD-MON-YYYY HH:MI:SS AM') AS TIMESTAMP), 'GMT')
		AT time zone sessiontimezone) AS DATE)	  
		FROM WMWHSE1.ORDERSTATUSHISTORY OSH 
		WHERE OSH.ORDERKEY=OD.ORDERKEY) DT_ULTIMO_EVENTO,
       O.EXTERNORDERKEY,
       O.CARRIERCODE,
      (SELECT OSH.SERIALKEY FROM WMWHSE2.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.ADDDATE=(SELECT MAX(OSH2.ADDDATE) FROM WMWHSE2.ORDERSTATUSHISTORY OSH2 
                                                       WHERE OSH2.ORDERKEY=OSH.ORDERKEY)
       AND ROWNUM=1) COD_ULTIMO_TRACKING      
FROM
      WMWHSE2.ORDERDETAIL OD,
      WMWHSE2.ORDERS O
WHERE O.ORDERKEY=OD.ORDERKEY
GROUP BY OD.ORDERKEY, O.EXTERNORDERKEY, O.CARRIERCODE, O.WHSEID
UNION SELECT
      OD.ORDERKEY COD_PEDIDO_WMS, O.WHSEID ARMAZEM,
      SUM(O.TOTALQTY) NUM_VOLUME,
      (SELECT MIN(OSH.ADDDATE) FROM WMWHSE3.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.STATUS>=51) DT_INICIO_PICKING,
      SUM(OD.QTYPICKED) NUM_VOL_FINALIZADOS,
      SUM(OD.SHIPPEDQTY) NUM_VOL_CONFERIDOS,
      (SELECT OSH.STATUS FROM WMWHSE3.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.ADDDATE=(SELECT MAX(OSH2.ADDDATE) FROM WMWHSE3.ORDERSTATUSHISTORY OSH2 
                                                       WHERE OSH2.ORDERKEY=OSH.ORDERKEY)
       AND ROWNUM=1) COD_ULTIMO_EVENTO,
      (SELECT 
		CAST((FROM_TZ(CAST(TO_CHAR(MIN(OSH.ADDDATE), 'DD-MON-YYYY HH:MI:SS AM') AS TIMESTAMP), 'GMT')
		AT time zone sessiontimezone) AS DATE)	  
		FROM WMWHSE1.ORDERSTATUSHISTORY OSH 
		WHERE OSH.ORDERKEY=OD.ORDERKEY) DT_ULTIMO_EVENTO,
       O.EXTERNORDERKEY,
       O.CARRIERCODE,
      (SELECT OSH.SERIALKEY FROM WMWHSE3.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.ADDDATE=(SELECT MAX(OSH2.ADDDATE) FROM WMWHSE3.ORDERSTATUSHISTORY OSH2 
                                                       WHERE OSH2.ORDERKEY=OSH.ORDERKEY)
       AND ROWNUM=1) COD_ULTIMO_TRACKING      
FROM
      WMWHSE3.ORDERDETAIL OD,
      WMWHSE3.ORDERS O
WHERE O.ORDERKEY=OD.ORDERKEY
GROUP BY OD.ORDERKEY, O.EXTERNORDERKEY, O.CARRIERCODE, O.WHSEID
UNION SELECT
      OD.ORDERKEY COD_PEDIDO_WMS, O.WHSEID ARMAZEM,
      SUM(O.TOTALQTY) NUM_VOLUME,
      (SELECT MIN(OSH.ADDDATE) FROM WMWHSE4.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.STATUS>=51) DT_INICIO_PICKING,
      SUM(OD.QTYPICKED) NUM_VOL_FINALIZADOS,
      SUM(OD.SHIPPEDQTY) NUM_VOL_CONFERIDOS,
      (SELECT OSH.STATUS FROM WMWHSE4.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.ADDDATE=(SELECT MAX(OSH2.ADDDATE) FROM WMWHSE4.ORDERSTATUSHISTORY OSH2 
                                                       WHERE OSH2.ORDERKEY=OSH.ORDERKEY)
       AND ROWNUM=1) COD_ULTIMO_EVENTO,
      (SELECT 
		CAST((FROM_TZ(CAST(TO_CHAR(MIN(OSH.ADDDATE), 'DD-MON-YYYY HH:MI:SS AM') AS TIMESTAMP), 'GMT')
		AT time zone sessiontimezone) AS DATE)	  
		FROM WMWHSE1.ORDERSTATUSHISTORY OSH 
		WHERE OSH.ORDERKEY=OD.ORDERKEY) DT_ULTIMO_EVENTO,
       O.EXTERNORDERKEY,
       O.CARRIERCODE,
      (SELECT OSH.SERIALKEY FROM WMWHSE4.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.ADDDATE=(SELECT MAX(OSH2.ADDDATE) FROM WMWHSE4.ORDERSTATUSHISTORY OSH2 
                                                       WHERE OSH2.ORDERKEY=OSH.ORDERKEY)
       AND ROWNUM=1) COD_ULTIMO_TRACKING      
FROM
      WMWHSE4.ORDERDETAIL OD,
      WMWHSE4.ORDERS O
WHERE O.ORDERKEY=OD.ORDERKEY
GROUP BY OD.ORDERKEY, O.EXTERNORDERKEY, O.CARRIERCODE, O.WHSEID
UNION SELECT
      OD.ORDERKEY COD_PEDIDO_WMS, O.WHSEID ARMAZEM,
      SUM(O.TOTALQTY) NUM_VOLUME,
      (SELECT MIN(OSH.ADDDATE) FROM WMWHSE5.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.STATUS>=51) DT_INICIO_PICKING,
      SUM(OD.QTYPICKED) NUM_VOL_FINALIZADOS,
      SUM(OD.SHIPPEDQTY) NUM_VOL_CONFERIDOS,
      (SELECT OSH.STATUS FROM WMWHSE5.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.ADDDATE=(SELECT MAX(OSH2.ADDDATE) FROM WMWHSE5.ORDERSTATUSHISTORY OSH2 
                                                       WHERE OSH2.ORDERKEY=OSH.ORDERKEY)
       AND ROWNUM=1) COD_ULTIMO_EVENTO,
      (SELECT 
		CAST((FROM_TZ(CAST(TO_CHAR(MIN(OSH.ADDDATE), 'DD-MON-YYYY HH:MI:SS AM') AS TIMESTAMP), 'GMT')
		AT time zone sessiontimezone) AS DATE)	  
		FROM WMWHSE1.ORDERSTATUSHISTORY OSH 
		WHERE OSH.ORDERKEY=OD.ORDERKEY) DT_ULTIMO_EVENTO,
       O.EXTERNORDERKEY,
       O.CARRIERCODE,
      (SELECT OSH.SERIALKEY FROM WMWHSE5.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.ADDDATE=(SELECT MAX(OSH2.ADDDATE) FROM WMWHSE5.ORDERSTATUSHISTORY OSH2 
                                                       WHERE OSH2.ORDERKEY=OSH.ORDERKEY)
       AND ROWNUM=1) COD_ULTIMO_TRACKING      
FROM
      WMWHSE5.ORDERDETAIL OD,
      WMWHSE5.ORDERS O
WHERE O.ORDERKEY=OD.ORDERKEY
GROUP BY OD.ORDERKEY, O.EXTERNORDERKEY, O.CARRIERCODE, O.WHSEID
UNION SELECT
      OD.ORDERKEY COD_PEDIDO_WMS, O.WHSEID ARMAZEM,
      SUM(O.TOTALQTY) NUM_VOLUME,
      (SELECT MIN(OSH.ADDDATE) FROM WMWHSE6.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.STATUS>=51) DT_INICIO_PICKING,
      SUM(OD.QTYPICKED) NUM_VOL_FINALIZADOS,
      SUM(OD.SHIPPEDQTY) NUM_VOL_CONFERIDOS,
      (SELECT OSH.STATUS FROM WMWHSE6.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.ADDDATE=(SELECT MAX(OSH2.ADDDATE) FROM WMWHSE6.ORDERSTATUSHISTORY OSH2 
                                                       WHERE OSH2.ORDERKEY=OSH.ORDERKEY)
       AND ROWNUM=1) COD_ULTIMO_EVENTO,
      (SELECT 
		CAST((FROM_TZ(CAST(TO_CHAR(MIN(OSH.ADDDATE), 'DD-MON-YYYY HH:MI:SS AM') AS TIMESTAMP), 'GMT')
		AT time zone sessiontimezone) AS DATE)	  
		FROM WMWHSE1.ORDERSTATUSHISTORY OSH 
		WHERE OSH.ORDERKEY=OD.ORDERKEY) DT_ULTIMO_EVENTO,
       O.EXTERNORDERKEY,
       O.CARRIERCODE,
      (SELECT OSH.SERIALKEY FROM WMWHSE6.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.ADDDATE=(SELECT MAX(OSH2.ADDDATE) FROM WMWHSE6.ORDERSTATUSHISTORY OSH2 
                                                       WHERE OSH2.ORDERKEY=OSH.ORDERKEY)
       AND ROWNUM=1) COD_ULTIMO_TRACKING      
FROM
      WMWHSE6.ORDERDETAIL OD,
      WMWHSE6.ORDERS O
WHERE O.ORDERKEY=OD.ORDERKEY
GROUP BY OD.ORDERKEY, O.EXTERNORDERKEY, O.CARRIERCODE, O.WHSEID
UNION SELECT
      OD.ORDERKEY COD_PEDIDO_WMS, O.WHSEID ARMAZEM,
      SUM(O.TOTALQTY) NUM_VOLUME,
      (SELECT MIN(OSH.ADDDATE) FROM WMWHSE7.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.STATUS>=51) DT_INICIO_PICKING,
      SUM(OD.QTYPICKED) NUM_VOL_FINALIZADOS,
      SUM(OD.SHIPPEDQTY) NUM_VOL_CONFERIDOS,
      (SELECT OSH.STATUS FROM WMWHSE7.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.ADDDATE=(SELECT MAX(OSH2.ADDDATE) FROM WMWHSE7.ORDERSTATUSHISTORY OSH2 
                                                       WHERE OSH2.ORDERKEY=OSH.ORDERKEY)
       AND ROWNUM=1) COD_ULTIMO_EVENTO,
      (SELECT 
		CAST((FROM_TZ(CAST(TO_CHAR(MIN(OSH.ADDDATE), 'DD-MON-YYYY HH:MI:SS AM') AS TIMESTAMP), 'GMT')
		AT time zone sessiontimezone) AS DATE)	  
		FROM WMWHSE1.ORDERSTATUSHISTORY OSH 
		WHERE OSH.ORDERKEY=OD.ORDERKEY) DT_ULTIMO_EVENTO,
       O.EXTERNORDERKEY,
       O.CARRIERCODE,
      (SELECT OSH.SERIALKEY FROM WMWHSE7.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.ADDDATE=(SELECT MAX(OSH2.ADDDATE) FROM WMWHSE7.ORDERSTATUSHISTORY OSH2 
                                                       WHERE OSH2.ORDERKEY=OSH.ORDERKEY)
       AND ROWNUM=1) COD_ULTIMO_TRACKING      
FROM
      WMWHSE7.ORDERDETAIL OD,
      WMWHSE7.ORDERS O
WHERE O.ORDERKEY=OD.ORDERKEY
GROUP BY OD.ORDERKEY, O.EXTERNORDERKEY, O.CARRIERCODE, O.WHSEID
UNION SELECT
      OD.ORDERKEY COD_PEDIDO_WMS, O.WHSEID ARMAZEM,
      SUM(O.TOTALQTY) NUM_VOLUME,
      (SELECT MIN(OSH.ADDDATE) FROM WMWHSE8.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.STATUS>=51) DT_INICIO_PICKING,
      SUM(OD.QTYPICKED) NUM_VOL_FINALIZADOS,
      SUM(OD.SHIPPEDQTY) NUM_VOL_CONFERIDOS,
      (SELECT OSH.STATUS FROM WMWHSE8.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.ADDDATE=(SELECT MAX(OSH2.ADDDATE) FROM WMWHSE8.ORDERSTATUSHISTORY OSH2 
                                                       WHERE OSH2.ORDERKEY=OSH.ORDERKEY)
       AND ROWNUM=1) COD_ULTIMO_EVENTO,
      (SELECT 
		CAST((FROM_TZ(CAST(TO_CHAR(MIN(OSH.ADDDATE), 'DD-MON-YYYY HH:MI:SS AM') AS TIMESTAMP), 'GMT')
		AT time zone sessiontimezone) AS DATE)	  
		FROM WMWHSE1.ORDERSTATUSHISTORY OSH 
		WHERE OSH.ORDERKEY=OD.ORDERKEY) DT_ULTIMO_EVENTO,
       O.EXTERNORDERKEY,
       O.CARRIERCODE,
      (SELECT OSH.SERIALKEY FROM WMWHSE8.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.ADDDATE=(SELECT MAX(OSH2.ADDDATE) FROM WMWHSE8.ORDERSTATUSHISTORY OSH2 
                                                       WHERE OSH2.ORDERKEY=OSH.ORDERKEY)
       AND ROWNUM=1) COD_ULTIMO_TRACKING      
FROM
      WMWHSE8.ORDERDETAIL OD,
      WMWHSE8.ORDERS O
WHERE O.ORDERKEY=OD.ORDERKEY
GROUP BY OD.ORDERKEY, O.EXTERNORDERKEY, O.CARRIERCODE, O.WHSEID
UNION SELECT
      OD.ORDERKEY COD_PEDIDO_WMS, O.WHSEID ARMAZEM,
      SUM(O.TOTALQTY) NUM_VOLUME,
      (SELECT MIN(OSH.ADDDATE) FROM WMWHSE9.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.STATUS>=51) DT_INICIO_PICKING,
      SUM(OD.QTYPICKED) NUM_VOL_FINALIZADOS,
      SUM(OD.SHIPPEDQTY) NUM_VOL_CONFERIDOS,
      (SELECT OSH.STATUS FROM WMWHSE9.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.ADDDATE=(SELECT MAX(OSH2.ADDDATE) FROM WMWHSE9.ORDERSTATUSHISTORY OSH2 
                                                       WHERE OSH2.ORDERKEY=OSH.ORDERKEY)
       AND ROWNUM=1) COD_ULTIMO_EVENTO,
      (SELECT 
		CAST((FROM_TZ(CAST(TO_CHAR(MIN(OSH.ADDDATE), 'DD-MON-YYYY HH:MI:SS AM') AS TIMESTAMP), 'GMT')
		AT time zone sessiontimezone) AS DATE)	  
		FROM WMWHSE1.ORDERSTATUSHISTORY OSH 
		WHERE OSH.ORDERKEY=OD.ORDERKEY) DT_ULTIMO_EVENTO,
       O.EXTERNORDERKEY,
       O.CARRIERCODE,
      (SELECT OSH.SERIALKEY FROM WMWHSE9.ORDERSTATUSHISTORY OSH 
       WHERE OSH.ORDERKEY=OD.ORDERKEY AND OSH.ADDDATE=(SELECT MAX(OSH2.ADDDATE) FROM WMWHSE9.ORDERSTATUSHISTORY OSH2 
                                                       WHERE OSH2.ORDERKEY=OSH.ORDERKEY)
       AND ROWNUM=1) COD_ULTIMO_TRACKING      
FROM
      WMWHSE9.ORDERDETAIL OD,
      WMWHSE9.ORDERS O
WHERE O.ORDERKEY=OD.ORDERKEY
GROUP BY OD.ORDERKEY, O.EXTERNORDERKEY, O.CARRIERCODE, O.WHSEID