SELECT  OSH.SERIALKEY CD_TRACKING,
        OSH.ORDERKEY NR_PEDIDO_WMS,
        OSH.WHSEID CD_ARMAZEM,
        OSH.STATUS CD_OCORRENCIA,
        'WMS' CD_SISTEMA_HOST,
        CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(OSH.ADDDATE, 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT') 
          AT time zone 'America/Sao_Paulo') AS DATE) DT_INCLUSAO_TRACKING         
FROM    WMWHSE1.ORDERSTATUSHISTORY OSH
where   OSH.ORDERLINENUMBER != ' '
UNION SELECT  OSH.SERIALKEY CD_TRACKING,
        OSH.ORDERKEY NR_PEDIDO_WMS,
        OSH.WHSEID CD_ARMAZEM,
        OSH.STATUS CD_OCORRENCIA,
        'WMS' CD_SISTEMA_HOST,
        CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(OSH.ADDDATE, 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT') 
          AT time zone 'America/Sao_Paulo') AS DATE) DT_INCLUSAO_TRACKING         
FROM    WMWHSE2.ORDERSTATUSHISTORY OSH 
where   OSH.ORDERLINENUMBER != ' '
UNION SELECT  OSH.SERIALKEY CD_TRACKING,
        OSH.ORDERKEY NR_PEDIDO_WMS,
        OSH.WHSEID CD_ARMAZEM,
        OSH.STATUS CD_OCORRENCIA,
        'WMS' CD_SISTEMA_HOST,
        CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(OSH.ADDDATE, 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT') 
          AT time zone 'America/Sao_Paulo') AS DATE) DT_INCLUSAO_TRACKING         
FROM    WMWHSE3.ORDERSTATUSHISTORY OSH
where   OSH.ORDERLINENUMBER != ' '
UNION SELECT  OSH.SERIALKEY CD_TRACKING,
        OSH.ORDERKEY NR_PEDIDO_WMS,
        OSH.WHSEID CD_ARMAZEM,
        OSH.STATUS CD_OCORRENCIA,
        'WMS' CD_SISTEMA_HOST,
        CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(OSH.ADDDATE, 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT') 
          AT time zone 'America/Sao_Paulo') AS DATE) DT_INCLUSAO_TRACKING         
FROM    WMWHSE4.ORDERSTATUSHISTORY OSH
where   OSH.ORDERLINENUMBER != ' '
UNION SELECT  OSH.SERIALKEY CD_TRACKING,
        OSH.ORDERKEY NR_PEDIDO_WMS,
        OSH.WHSEID CD_ARMAZEM,
        OSH.STATUS CD_OCORRENCIA,
        'WMS' CD_SISTEMA_HOST,
        CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(OSH.ADDDATE, 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT') 
          AT time zone 'America/Sao_Paulo') AS DATE) DT_INCLUSAO_TRACKING         
FROM    WMWHSE5.ORDERSTATUSHISTORY OSH
where   OSH.ORDERLINENUMBER != ' '
UNION SELECT  OSH.SERIALKEY CD_TRACKING,
        OSH.ORDERKEY NR_PEDIDO_WMS,
        OSH.WHSEID CD_ARMAZEM,
        OSH.STATUS CD_OCORRENCIA,
        'WMS' CD_SISTEMA_HOST,
        CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(OSH.ADDDATE, 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT') 
          AT time zone 'America/Sao_Paulo') AS DATE) DT_INCLUSAO_TRACKING         
FROM    WMWHSE6.ORDERSTATUSHISTORY OSH
where   OSH.ORDERLINENUMBER != ' '
UNION SELECT  OSH.SERIALKEY CD_TRACKING,
        OSH.ORDERKEY NR_PEDIDO_WMS,
        OSH.WHSEID CD_ARMAZEM,
        OSH.STATUS CD_OCORRENCIA,
        'WMS' CD_SISTEMA_HOST,
        CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(OSH.ADDDATE, 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT') 
          AT time zone 'America/Sao_Paulo') AS DATE) DT_INCLUSAO_TRACKING         
FROM    WMWHSE7.ORDERSTATUSHISTORY OSH
where   OSH.ORDERLINENUMBER != ' '
UNION SELECT  OSH.SERIALKEY CD_TRACKING,
        OSH.ORDERKEY NR_PEDIDO_WMS,
        OSH.WHSEID CD_ARMAZEM,
        OSH.STATUS CD_OCORRENCIA,
        'WMS' CD_SISTEMA_HOST,
        CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(OSH.ADDDATE, 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT') 
          AT time zone 'America/Sao_Paulo') AS DATE) DT_INCLUSAO_TRACKING         
FROM    WMWHSE8.ORDERSTATUSHISTORY OSH
where   OSH.ORDERLINENUMBER != ' '
UNION SELECT  OSH.SERIALKEY CD_TRACKING,
        OSH.ORDERKEY NR_PEDIDO_WMS,
        OSH.WHSEID CD_ARMAZEM,
        OSH.STATUS CD_OCORRENCIA,
        'WMS' CD_SISTEMA_HOST,
        CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(OSH.ADDDATE, 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT') 
          AT time zone 'America/Sao_Paulo') AS DATE) DT_INCLUSAO_TRACKING         
FROM    WMWHSE9.ORDERSTATUSHISTORY OSH
where   OSH.ORDERLINENUMBER != ' '
