--	FAF.004 - 13-jan-2014, Fabio Ferreira, 	Correção situação do item e data da situação
--											Correção QT cancelada
--*******************************************************************************************************************************************
SELECT
	ORDERDETAIL.orderkey NR_PEDIDO_WMS, 
	ORDERDETAIL.WHSEID CD_ARMAZEM,
	ORDERDETAIL.sku CD_ITEM,
	ORDERDETAIL.ORDERLINENUMBER SQ_PEDIDO,
	ORDERDETAIL.lot CD_LOTE,
	ORDERDETAIL.ORIGINALQTY QT_PEDIDA,
	ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.OPENQTY QT_ATENDIDA,
	ORDERDETAIL.STATUS CD_SITUACAO_ITEM,	
	ORDERDETAIL.SHIPPEDQTY QT_LIQUIDADA,									
  nvl((select min(orderstatushistory.ADDDATE) from WMWHSE1.orderstatushistory orderstatushistory
  where orderstatushistory.ORDERKEY=ORDERDETAIL.ORDERKEY
  and orderstatushistory.ORDERLINENUMBER=ORDERDETAIL.ORDERLINENUMBER
  and orderstatushistory.STATUS=ORDERDETAIL.STATUS), ORDERDETAIL.ADDDATE) DT_SITUACAO_ITEM,
	CASE WHEN ORDERDETAIL.ADJUSTEDQTY!=0 THEN ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.ADJUSTEDQTY 
	ELSE 0 
	END QT_CANCELADA,
	ORDERDETAIL.editdate DT_ATUALIZACAO
FROM WMWHSE1.ORDERDETAIL ORDERDETAIL, WMWHSE1.SKU SKU
WHERE SKU.SKU=ORDERDETAIL.SKU
UNION
SELECT
	ORDERDETAIL.orderkey NR_PEDIDO_WMS, 
	ORDERDETAIL.WHSEID CD_ARMAZEM,
	ORDERDETAIL.sku CD_ITEM,
	ORDERDETAIL.ORDERLINENUMBER SQ_PEDIDO,
	ORDERDETAIL.lot CD_LOTE,
	ORDERDETAIL.ORIGINALQTY QT_PEDIDA,
	ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.OPENQTY QT_ATENDIDA,
	ORDERDETAIL.STATUS CD_SITUACAO_ITEM,	
	ORDERDETAIL.SHIPPEDQTY QT_LIQUIDADA,									
  nvl((select min(orderstatushistory.ADDDATE) from WMWHSE2.orderstatushistory orderstatushistory
  where orderstatushistory.ORDERKEY=ORDERDETAIL.ORDERKEY
  and orderstatushistory.ORDERLINENUMBER=ORDERDETAIL.ORDERLINENUMBER
  and orderstatushistory.STATUS=ORDERDETAIL.STATUS), ORDERDETAIL.ADDDATE) DT_SITUACAO_ITEM,
	CASE WHEN ORDERDETAIL.ADJUSTEDQTY!=0 THEN ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.ADJUSTEDQTY 
	ELSE 0 
	END QT_CANCELADA,
	ORDERDETAIL.editdate DT_ATUALIZACAO
FROM WMWHSE2.ORDERDETAIL ORDERDETAIL, WMWHSE2.SKU SKU
WHERE SKU.SKU=ORDERDETAIL.SKU
UNION
SELECT
	ORDERDETAIL.orderkey NR_PEDIDO_WMS, 
	ORDERDETAIL.WHSEID CD_ARMAZEM,
	ORDERDETAIL.sku CD_ITEM,
	ORDERDETAIL.ORDERLINENUMBER SQ_PEDIDO,
	ORDERDETAIL.lot CD_LOTE,
	ORDERDETAIL.ORIGINALQTY QT_PEDIDA,
	ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.OPENQTY QT_ATENDIDA,
	ORDERDETAIL.STATUS CD_SITUACAO_ITEM,	
	ORDERDETAIL.SHIPPEDQTY QT_LIQUIDADA,									
  nvl((select min(orderstatushistory.ADDDATE) from WMWHSE3.orderstatushistory orderstatushistory
  where orderstatushistory.ORDERKEY=ORDERDETAIL.ORDERKEY
  and orderstatushistory.ORDERLINENUMBER=ORDERDETAIL.ORDERLINENUMBER
  and orderstatushistory.STATUS=ORDERDETAIL.STATUS), ORDERDETAIL.ADDDATE) DT_SITUACAO_ITEM,
	CASE WHEN ORDERDETAIL.ADJUSTEDQTY!=0 THEN ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.ADJUSTEDQTY 
	ELSE 0 
	END QT_CANCELADA,
	ORDERDETAIL.editdate DT_ATUALIZACAO
FROM WMWHSE3.ORDERDETAIL ORDERDETAIL, WMWHSE3.SKU SKU
WHERE SKU.SKU=ORDERDETAIL.SKU
UNION
SELECT
	ORDERDETAIL.orderkey NR_PEDIDO_WMS, 
	ORDERDETAIL.WHSEID CD_ARMAZEM,
	ORDERDETAIL.sku CD_ITEM,
	ORDERDETAIL.ORDERLINENUMBER SQ_PEDIDO,
	ORDERDETAIL.lot CD_LOTE,
	ORDERDETAIL.ORIGINALQTY QT_PEDIDA,
	ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.OPENQTY QT_ATENDIDA,
	ORDERDETAIL.STATUS CD_SITUACAO_ITEM,	
	ORDERDETAIL.SHIPPEDQTY QT_LIQUIDADA,									
  nvl((select min(orderstatushistory.ADDDATE) from WMWHSE4.orderstatushistory orderstatushistory
  where orderstatushistory.ORDERKEY=ORDERDETAIL.ORDERKEY
  and orderstatushistory.ORDERLINENUMBER=ORDERDETAIL.ORDERLINENUMBER
  and orderstatushistory.STATUS=ORDERDETAIL.STATUS), ORDERDETAIL.ADDDATE) DT_SITUACAO_ITEM,
	CASE WHEN ORDERDETAIL.ADJUSTEDQTY!=0 THEN ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.ADJUSTEDQTY 
	ELSE 0 
	END QT_CANCELADA,
	ORDERDETAIL.editdate DT_ATUALIZACAO
FROM WMWHSE4.ORDERDETAIL ORDERDETAIL, WMWHSE4.SKU SKU
WHERE SKU.SKU=ORDERDETAIL.SKU
UNION
SELECT
	ORDERDETAIL.orderkey NR_PEDIDO_WMS, 
	ORDERDETAIL.WHSEID CD_ARMAZEM,
	ORDERDETAIL.sku CD_ITEM,
	ORDERDETAIL.ORDERLINENUMBER SQ_PEDIDO,
	ORDERDETAIL.lot CD_LOTE,
	ORDERDETAIL.ORIGINALQTY QT_PEDIDA,
	ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.OPENQTY QT_ATENDIDA,
	ORDERDETAIL.STATUS CD_SITUACAO_ITEM,	
	ORDERDETAIL.SHIPPEDQTY QT_LIQUIDADA,									
  nvl((select min(orderstatushistory.ADDDATE) from WMWHSE5.orderstatushistory orderstatushistory
  where orderstatushistory.ORDERKEY=ORDERDETAIL.ORDERKEY
  and orderstatushistory.ORDERLINENUMBER=ORDERDETAIL.ORDERLINENUMBER
  and orderstatushistory.STATUS=ORDERDETAIL.STATUS), ORDERDETAIL.ADDDATE) DT_SITUACAO_ITEM,
	CASE WHEN ORDERDETAIL.ADJUSTEDQTY!=0 THEN ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.ADJUSTEDQTY 
	ELSE 0 
	END QT_CANCELADA,
	ORDERDETAIL.editdate DT_ATUALIZACAO
FROM WMWHSE5.ORDERDETAIL ORDERDETAIL, WMWHSE5.SKU SKU
WHERE SKU.SKU=ORDERDETAIL.SKU
UNION
SELECT
	ORDERDETAIL.orderkey NR_PEDIDO_WMS, 
	ORDERDETAIL.WHSEID CD_ARMAZEM,
	ORDERDETAIL.sku CD_ITEM,
	ORDERDETAIL.ORDERLINENUMBER SQ_PEDIDO,
	ORDERDETAIL.lot CD_LOTE,
	ORDERDETAIL.ORIGINALQTY QT_PEDIDA,
	ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.OPENQTY QT_ATENDIDA,
	ORDERDETAIL.STATUS CD_SITUACAO_ITEM,	
	ORDERDETAIL.SHIPPEDQTY QT_LIQUIDADA,									
  nvl((select min(orderstatushistory.ADDDATE) from WMWHSE6.orderstatushistory orderstatushistory
  where orderstatushistory.ORDERKEY=ORDERDETAIL.ORDERKEY
  and orderstatushistory.ORDERLINENUMBER=ORDERDETAIL.ORDERLINENUMBER
  and orderstatushistory.STATUS=ORDERDETAIL.STATUS), ORDERDETAIL.ADDDATE) DT_SITUACAO_ITEM,
	CASE WHEN ORDERDETAIL.ADJUSTEDQTY!=0 THEN ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.ADJUSTEDQTY 
	ELSE 0 
	END QT_CANCELADA,
	ORDERDETAIL.editdate DT_ATUALIZACAO
FROM WMWHSE6.ORDERDETAIL ORDERDETAIL, WMWHSE6.SKU SKU
WHERE SKU.SKU=ORDERDETAIL.SKU
UNION
SELECT
	ORDERDETAIL.orderkey NR_PEDIDO_WMS, 
	ORDERDETAIL.WHSEID CD_ARMAZEM,
	ORDERDETAIL.sku CD_ITEM,
	ORDERDETAIL.ORDERLINENUMBER SQ_PEDIDO,
	ORDERDETAIL.lot CD_LOTE,
	ORDERDETAIL.ORIGINALQTY QT_PEDIDA,
	ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.OPENQTY QT_ATENDIDA,
	ORDERDETAIL.STATUS CD_SITUACAO_ITEM,	
	ORDERDETAIL.SHIPPEDQTY QT_LIQUIDADA,									
  nvl((select min(orderstatushistory.ADDDATE) from WMWHSE7.orderstatushistory orderstatushistory
  where orderstatushistory.ORDERKEY=ORDERDETAIL.ORDERKEY
  and orderstatushistory.ORDERLINENUMBER=ORDERDETAIL.ORDERLINENUMBER
  and orderstatushistory.STATUS=ORDERDETAIL.STATUS), ORDERDETAIL.ADDDATE) DT_SITUACAO_ITEM,
	CASE WHEN ORDERDETAIL.ADJUSTEDQTY!=0 THEN ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.ADJUSTEDQTY 
	ELSE 0 
	END QT_CANCELADA,
	ORDERDETAIL.editdate DT_ATUALIZACAO
FROM WMWHSE7.ORDERDETAIL ORDERDETAIL, WMWHSE7.SKU SKU
WHERE SKU.SKU=ORDERDETAIL.SKU
UNION
SELECT
	ORDERDETAIL.orderkey NR_PEDIDO_WMS, 
	ORDERDETAIL.WHSEID CD_ARMAZEM,
	ORDERDETAIL.sku CD_ITEM,
	ORDERDETAIL.ORDERLINENUMBER SQ_PEDIDO,
	ORDERDETAIL.lot CD_LOTE,
	ORDERDETAIL.ORIGINALQTY QT_PEDIDA,
	ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.OPENQTY QT_ATENDIDA,
	ORDERDETAIL.STATUS CD_SITUACAO_ITEM,	
	ORDERDETAIL.SHIPPEDQTY QT_LIQUIDADA,									
  nvl((select min(orderstatushistory.ADDDATE) from WMWHSE8.orderstatushistory orderstatushistory
  where orderstatushistory.ORDERKEY=ORDERDETAIL.ORDERKEY
  and orderstatushistory.ORDERLINENUMBER=ORDERDETAIL.ORDERLINENUMBER
  and orderstatushistory.STATUS=ORDERDETAIL.STATUS), ORDERDETAIL.ADDDATE) DT_SITUACAO_ITEM,
	CASE WHEN ORDERDETAIL.ADJUSTEDQTY!=0 THEN ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.ADJUSTEDQTY 
	ELSE 0 
	END QT_CANCELADA,
	ORDERDETAIL.editdate DT_ATUALIZACAO
FROM WMWHSE8.ORDERDETAIL ORDERDETAIL, WMWHSE8.SKU SKU
WHERE SKU.SKU=ORDERDETAIL.SKU
UNION
SELECT
	ORDERDETAIL.orderkey NR_PEDIDO_WMS, 
	ORDERDETAIL.WHSEID CD_ARMAZEM,
	ORDERDETAIL.sku CD_ITEM,
	ORDERDETAIL.ORDERLINENUMBER SQ_PEDIDO,
	ORDERDETAIL.lot CD_LOTE,
	ORDERDETAIL.ORIGINALQTY QT_PEDIDA,
	ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.OPENQTY QT_ATENDIDA,
	ORDERDETAIL.STATUS CD_SITUACAO_ITEM,	
	ORDERDETAIL.SHIPPEDQTY QT_LIQUIDADA,									
  nvl((select min(orderstatushistory.ADDDATE) from WMWHSE9.orderstatushistory orderstatushistory
  where orderstatushistory.ORDERKEY=ORDERDETAIL.ORDERKEY
  and orderstatushistory.ORDERLINENUMBER=ORDERDETAIL.ORDERLINENUMBER
  and orderstatushistory.STATUS=ORDERDETAIL.STATUS), ORDERDETAIL.ADDDATE) DT_SITUACAO_ITEM,
	CASE WHEN ORDERDETAIL.ADJUSTEDQTY!=0 THEN ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.ADJUSTEDQTY 
	ELSE 0 
	END QT_CANCELADA,
	ORDERDETAIL.editdate DT_ATUALIZACAO
FROM WMWHSE9.ORDERDETAIL ORDERDETAIL, WMWHSE9.SKU SKU
WHERE SKU.SKU=ORDERDETAIL.SKU