--	FAF.004 - 13-jan-2014, Fabio Ferreira, 	Correção situação do item e data da situação
--											Correção QT cancelada
--*******************************************************************************************************************************************
SELECT
	ORDERDETAIL.orderkey NR_PEDIDO_WMS, 
	ORDERDETAIL.WHSEID CD_ARMAZEM,
	ORDERDETAIL.sku CD_ITEM,
	ORDERDETAIL.ORDERLINENUMBER SQ_PEDIDO,
	PKD.lot CD_LOTE,
	ORDERDETAIL.ORIGINALQTY QT_PEDIDA,
	ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.OPENQTY QT_ATENDIDA,
	ORDERDETAIL.STATUS CD_SITUACAO_ITEM,	
	ORDERDETAIL.SHIPPEDQTY QT_LIQUIDADA,									
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(nvl((select min(orderstatushistory.ADDDATE) from WMWHSE1.orderstatushistory orderstatushistory
  where orderstatushistory.ORDERKEY=ORDERDETAIL.ORDERKEY
  and orderstatushistory.ORDERLINENUMBER=ORDERDETAIL.ORDERLINENUMBER
  and orderstatushistory.STATUS=ORDERDETAIL.STATUS), ORDERDETAIL.ADDDATE), 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
  AT time zone 'America/Sao_Paulo') AS DATE) DT_SITUACAO_ITEM,  
	CASE WHEN ORDERDETAIL.ADJUSTEDQTY!=0 THEN ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.ADJUSTEDQTY 
	ELSE 0 
	END QT_CANCELADA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ORDERDETAIL.editdate, 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
  AT time zone 'America/Sao_Paulo') AS DATE) DT_ULT_ATUALIZACAO
FROM WMWHSE1.ORDERDETAIL ORDERDETAIL
INNER JOIN WMWHSE1.SKU SKU
        ON SKU.SKU=ORDERDETAIL.SKU
LEFT JOIN WMWHSE1.PICKDETAIL PKD
        ON  PKD.ORDERKEY = ORDERDETAIL.ORDERKEY
        AND PKD.ORDERLINENUMBER = ORDERDETAIL.ORDERLINENUMBER
-----------------------------------------------------------------------------------------------------------------------------------------
UNION
SELECT
	ORDERDETAIL.orderkey NR_PEDIDO_WMS, 
	ORDERDETAIL.WHSEID CD_ARMAZEM,
	ORDERDETAIL.sku CD_ITEM,
	ORDERDETAIL.ORDERLINENUMBER SQ_PEDIDO,
	PKD.lot CD_LOTE,
	ORDERDETAIL.ORIGINALQTY QT_PEDIDA,
	ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.OPENQTY QT_ATENDIDA,
	ORDERDETAIL.STATUS CD_SITUACAO_ITEM,	
	ORDERDETAIL.SHIPPEDQTY QT_LIQUIDADA,									
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(nvl((select min(orderstatushistory.ADDDATE) from WMWHSE2.orderstatushistory orderstatushistory
  where orderstatushistory.ORDERKEY=ORDERDETAIL.ORDERKEY
  and orderstatushistory.ORDERLINENUMBER=ORDERDETAIL.ORDERLINENUMBER
  and orderstatushistory.STATUS=ORDERDETAIL.STATUS), ORDERDETAIL.ADDDATE), 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
  AT time zone 'America/Sao_Paulo') AS DATE) DT_SITUACAO_ITEM,  
	CASE WHEN ORDERDETAIL.ADJUSTEDQTY!=0 THEN ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.ADJUSTEDQTY 
	ELSE 0 
	END QT_CANCELADA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ORDERDETAIL.editdate, 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
  AT time zone 'America/Sao_Paulo') AS DATE) DT_ULT_ATUALIZACAO
FROM WMWHSE2.ORDERDETAIL ORDERDETAIL
INNER JOIN WMWHSE2.SKU SKU
        ON SKU.SKU=ORDERDETAIL.SKU
LEFT JOIN WMWHSE2.PICKDETAIL PKD
        ON  PKD.ORDERKEY = ORDERDETAIL.ORDERKEY
        AND PKD.ORDERLINENUMBER = ORDERDETAIL.ORDERLINENUMBER
-----------------------------------------------------------------------------------------------------------------------------------------
UNION
SELECT
	ORDERDETAIL.orderkey NR_PEDIDO_WMS, 
	ORDERDETAIL.WHSEID CD_ARMAZEM,
	ORDERDETAIL.sku CD_ITEM,
	ORDERDETAIL.ORDERLINENUMBER SQ_PEDIDO,
	PKD.lot CD_LOTE,
	ORDERDETAIL.ORIGINALQTY QT_PEDIDA,
	ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.OPENQTY QT_ATENDIDA,
	ORDERDETAIL.STATUS CD_SITUACAO_ITEM,	
	ORDERDETAIL.SHIPPEDQTY QT_LIQUIDADA,									
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(nvl((select min(orderstatushistory.ADDDATE) from WMWHSE3.orderstatushistory orderstatushistory
  where orderstatushistory.ORDERKEY=ORDERDETAIL.ORDERKEY
  and orderstatushistory.ORDERLINENUMBER=ORDERDETAIL.ORDERLINENUMBER
  and orderstatushistory.STATUS=ORDERDETAIL.STATUS), ORDERDETAIL.ADDDATE), 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
  AT time zone 'America/Sao_Paulo') AS DATE) DT_SITUACAO_ITEM,  
	CASE WHEN ORDERDETAIL.ADJUSTEDQTY!=0 THEN ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.ADJUSTEDQTY 
	ELSE 0 
	END QT_CANCELADA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ORDERDETAIL.editdate, 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
  AT time zone 'America/Sao_Paulo') AS DATE) DT_ULT_ATUALIZACAO
FROM WMWHSE3.ORDERDETAIL ORDERDETAIL
INNER JOIN WMWHSE3.SKU SKU
        ON SKU.SKU=ORDERDETAIL.SKU
LEFT JOIN WMWHSE3.PICKDETAIL PKD
        ON  PKD.ORDERKEY = ORDERDETAIL.ORDERKEY
        AND PKD.ORDERLINENUMBER = ORDERDETAIL.ORDERLINENUMBER
-----------------------------------------------------------------------------------------------------------------------------------------
UNION
SELECT
	ORDERDETAIL.orderkey NR_PEDIDO_WMS, 
	ORDERDETAIL.WHSEID CD_ARMAZEM,
	ORDERDETAIL.sku CD_ITEM,
	ORDERDETAIL.ORDERLINENUMBER SQ_PEDIDO,
	PKD.lot CD_LOTE,
	ORDERDETAIL.ORIGINALQTY QT_PEDIDA,
	ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.OPENQTY QT_ATENDIDA,
	ORDERDETAIL.STATUS CD_SITUACAO_ITEM,	
	ORDERDETAIL.SHIPPEDQTY QT_LIQUIDADA,									
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(nvl((select min(orderstatushistory.ADDDATE) from WMWHSE4.orderstatushistory orderstatushistory
  where orderstatushistory.ORDERKEY=ORDERDETAIL.ORDERKEY
  and orderstatushistory.ORDERLINENUMBER=ORDERDETAIL.ORDERLINENUMBER
  and orderstatushistory.STATUS=ORDERDETAIL.STATUS), ORDERDETAIL.ADDDATE), 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
  AT time zone 'America/Sao_Paulo') AS DATE) DT_SITUACAO_ITEM,  
	CASE WHEN ORDERDETAIL.ADJUSTEDQTY!=0 THEN ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.ADJUSTEDQTY 
	ELSE 0 
	END QT_CANCELADA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ORDERDETAIL.editdate, 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
  AT time zone 'America/Sao_Paulo') AS DATE) DT_ULT_ATUALIZACAO
FROM WMWHSE4.ORDERDETAIL ORDERDETAIL
INNER JOIN WMWHSE4.SKU SKU
        ON SKU.SKU=ORDERDETAIL.SKU
LEFT JOIN WMWHSE4.PICKDETAIL PKD
        ON  PKD.ORDERKEY = ORDERDETAIL.ORDERKEY
        AND PKD.ORDERLINENUMBER = ORDERDETAIL.ORDERLINENUMBER		
-----------------------------------------------------------------------------------------------------------------------------------------
UNION
SELECT
	ORDERDETAIL.orderkey NR_PEDIDO_WMS, 
	ORDERDETAIL.WHSEID CD_ARMAZEM,
	ORDERDETAIL.sku CD_ITEM,
	ORDERDETAIL.ORDERLINENUMBER SQ_PEDIDO,
	PKD.lot CD_LOTE,
	ORDERDETAIL.ORIGINALQTY QT_PEDIDA,
	ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.OPENQTY QT_ATENDIDA,
	ORDERDETAIL.STATUS CD_SITUACAO_ITEM,	
	ORDERDETAIL.SHIPPEDQTY QT_LIQUIDADA,									
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(nvl((select min(orderstatushistory.ADDDATE) from WMWHSE5.orderstatushistory orderstatushistory
  where orderstatushistory.ORDERKEY=ORDERDETAIL.ORDERKEY
  and orderstatushistory.ORDERLINENUMBER=ORDERDETAIL.ORDERLINENUMBER
  and orderstatushistory.STATUS=ORDERDETAIL.STATUS), ORDERDETAIL.ADDDATE), 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
  AT time zone 'America/Sao_Paulo') AS DATE) DT_SITUACAO_ITEM,  
	CASE WHEN ORDERDETAIL.ADJUSTEDQTY!=0 THEN ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.ADJUSTEDQTY 
	ELSE 0 
	END QT_CANCELADA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ORDERDETAIL.editdate, 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
  AT time zone 'America/Sao_Paulo') AS DATE) DT_ULT_ATUALIZACAO
FROM WMWHSE5.ORDERDETAIL ORDERDETAIL
INNER JOIN WMWHSE5.SKU SKU
        ON SKU.SKU=ORDERDETAIL.SKU
LEFT JOIN WMWHSE5.PICKDETAIL PKD
        ON  PKD.ORDERKEY = ORDERDETAIL.ORDERKEY
        AND PKD.ORDERLINENUMBER = ORDERDETAIL.ORDERLINENUMBER		
-----------------------------------------------------------------------------------------------------------------------------------------
UNION
SELECT
	ORDERDETAIL.orderkey NR_PEDIDO_WMS, 
	ORDERDETAIL.WHSEID CD_ARMAZEM,
	ORDERDETAIL.sku CD_ITEM,
	ORDERDETAIL.ORDERLINENUMBER SQ_PEDIDO,
	PKD.lot CD_LOTE,
	ORDERDETAIL.ORIGINALQTY QT_PEDIDA,
	ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.OPENQTY QT_ATENDIDA,
	ORDERDETAIL.STATUS CD_SITUACAO_ITEM,	
	ORDERDETAIL.SHIPPEDQTY QT_LIQUIDADA,									
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(nvl((select min(orderstatushistory.ADDDATE) from WMWHSE6.orderstatushistory orderstatushistory
  where orderstatushistory.ORDERKEY=ORDERDETAIL.ORDERKEY
  and orderstatushistory.ORDERLINENUMBER=ORDERDETAIL.ORDERLINENUMBER
  and orderstatushistory.STATUS=ORDERDETAIL.STATUS), ORDERDETAIL.ADDDATE), 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
  AT time zone 'America/Sao_Paulo') AS DATE) DT_SITUACAO_ITEM,  
	CASE WHEN ORDERDETAIL.ADJUSTEDQTY!=0 THEN ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.ADJUSTEDQTY 
	ELSE 0 
	END QT_CANCELADA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ORDERDETAIL.editdate, 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
  AT time zone 'America/Sao_Paulo') AS DATE) DT_ULT_ATUALIZACAO
FROM WMWHSE6.ORDERDETAIL ORDERDETAIL
INNER JOIN WMWHSE6.SKU SKU
        ON SKU.SKU=ORDERDETAIL.SKU
LEFT JOIN WMWHSE6.PICKDETAIL PKD
        ON  PKD.ORDERKEY = ORDERDETAIL.ORDERKEY
        AND PKD.ORDERLINENUMBER = ORDERDETAIL.ORDERLINENUMBER		
-----------------------------------------------------------------------------------------------------------------------------------------
UNION
SELECT
	ORDERDETAIL.orderkey NR_PEDIDO_WMS, 
	ORDERDETAIL.WHSEID CD_ARMAZEM,
	ORDERDETAIL.sku CD_ITEM,
	ORDERDETAIL.ORDERLINENUMBER SQ_PEDIDO,
	PKD.lot CD_LOTE,
	ORDERDETAIL.ORIGINALQTY QT_PEDIDA,
	ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.OPENQTY QT_ATENDIDA,
	ORDERDETAIL.STATUS CD_SITUACAO_ITEM,	
	ORDERDETAIL.SHIPPEDQTY QT_LIQUIDADA,									
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(nvl((select min(orderstatushistory.ADDDATE) from WMWHSE7.orderstatushistory orderstatushistory
  where orderstatushistory.ORDERKEY=ORDERDETAIL.ORDERKEY
  and orderstatushistory.ORDERLINENUMBER=ORDERDETAIL.ORDERLINENUMBER
  and orderstatushistory.STATUS=ORDERDETAIL.STATUS), ORDERDETAIL.ADDDATE), 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
  AT time zone 'America/Sao_Paulo') AS DATE) DT_SITUACAO_ITEM,  
	CASE WHEN ORDERDETAIL.ADJUSTEDQTY!=0 THEN ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.ADJUSTEDQTY 
	ELSE 0 
	END QT_CANCELADA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ORDERDETAIL.editdate, 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
  AT time zone 'America/Sao_Paulo') AS DATE) DT_ULT_ATUALIZACAO
FROM WMWHSE7.ORDERDETAIL ORDERDETAIL
INNER JOIN WMWHSE7.SKU SKU
        ON SKU.SKU=ORDERDETAIL.SKU
LEFT JOIN WMWHSE7.PICKDETAIL PKD
        ON  PKD.ORDERKEY = ORDERDETAIL.ORDERKEY
        AND PKD.ORDERLINENUMBER = ORDERDETAIL.ORDERLINENUMBER		
-----------------------------------------------------------------------------------------------------------------------------------------
UNION
SELECT
	ORDERDETAIL.orderkey NR_PEDIDO_WMS, 
	ORDERDETAIL.WHSEID CD_ARMAZEM,
	ORDERDETAIL.sku CD_ITEM,
	ORDERDETAIL.ORDERLINENUMBER SQ_PEDIDO,
	PKD.lot CD_LOTE,
	ORDERDETAIL.ORIGINALQTY QT_PEDIDA,
	ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.OPENQTY QT_ATENDIDA,
	ORDERDETAIL.STATUS CD_SITUACAO_ITEM,	
	ORDERDETAIL.SHIPPEDQTY QT_LIQUIDADA,									
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(nvl((select min(orderstatushistory.ADDDATE) from WMWHSE8.orderstatushistory orderstatushistory
  where orderstatushistory.ORDERKEY=ORDERDETAIL.ORDERKEY
  and orderstatushistory.ORDERLINENUMBER=ORDERDETAIL.ORDERLINENUMBER
  and orderstatushistory.STATUS=ORDERDETAIL.STATUS), ORDERDETAIL.ADDDATE), 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
  AT time zone 'America/Sao_Paulo') AS DATE) DT_SITUACAO_ITEM,  
	CASE WHEN ORDERDETAIL.ADJUSTEDQTY!=0 THEN ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.ADJUSTEDQTY 
	ELSE 0 
	END QT_CANCELADA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ORDERDETAIL.editdate, 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
  AT time zone 'America/Sao_Paulo') AS DATE) DT_ULT_ATUALIZACAO
FROM WMWHSE8.ORDERDETAIL ORDERDETAIL
INNER JOIN WMWHSE8.SKU SKU
        ON SKU.SKU=ORDERDETAIL.SKU
LEFT JOIN WMWHSE8.PICKDETAIL PKD
        ON  PKD.ORDERKEY = ORDERDETAIL.ORDERKEY
        AND PKD.ORDERLINENUMBER = ORDERDETAIL.ORDERLINENUMBER
-----------------------------------------------------------------------------------------------------------------------------------------
UNION
SELECT
	ORDERDETAIL.orderkey NR_PEDIDO_WMS, 
	ORDERDETAIL.WHSEID CD_ARMAZEM,
	ORDERDETAIL.sku CD_ITEM,
	ORDERDETAIL.ORDERLINENUMBER SQ_PEDIDO,
	PKD.lot CD_LOTE,
	ORDERDETAIL.ORIGINALQTY QT_PEDIDA,
	ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.OPENQTY QT_ATENDIDA,
	ORDERDETAIL.STATUS CD_SITUACAO_ITEM,	
	ORDERDETAIL.SHIPPEDQTY QT_LIQUIDADA,									
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(nvl((select min(orderstatushistory.ADDDATE) from WMWHSE9.orderstatushistory orderstatushistory
  where orderstatushistory.ORDERKEY=ORDERDETAIL.ORDERKEY
  and orderstatushistory.ORDERLINENUMBER=ORDERDETAIL.ORDERLINENUMBER
  and orderstatushistory.STATUS=ORDERDETAIL.STATUS), ORDERDETAIL.ADDDATE), 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
  AT time zone 'America/Sao_Paulo') AS DATE) DT_SITUACAO_ITEM,  
	CASE WHEN ORDERDETAIL.ADJUSTEDQTY!=0 THEN ORDERDETAIL.ORIGINALQTY-ORDERDETAIL.ADJUSTEDQTY 
	ELSE 0 
	END QT_CANCELADA,
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ORDERDETAIL.editdate, 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
  AT time zone 'America/Sao_Paulo') AS DATE) DT_ULT_ATUALIZACAO
FROM WMWHSE9.ORDERDETAIL ORDERDETAIL
INNER JOIN WMWHSE9.SKU SKU
        ON SKU.SKU=ORDERDETAIL.SKU
LEFT JOIN WMWHSE9.PICKDETAIL PKD
        ON  PKD.ORDERKEY = ORDERDETAIL.ORDERKEY
        AND PKD.ORDERLINENUMBER = ORDERDETAIL.ORDERLINENUMBER		