SELECT SERIALKEY,
  WHSEID COD_PLANTA,
  a.DB_ALIAS DESCR_PLANTA,
  ADDDATE DT_CADASTRO,
  EDITDATE DT_ATUALIZACAO
FROM WMWHSE1.FACILITYNEST, wmsadmin.PL_DB a
WHERE Upper(a.db_logid)=upper(FACILITYNEST.WHSEID)
AND a.ISACTIVE=1
UNION
SELECT SERIALKEY,
  WHSEID COD_PLANTA,
  a.DB_ALIAS DESCR_PLANTA,
  ADDDATE DT_CADASTRO,
  EDITDATE DT_ATUALIZACAO
FROM WMWHSE2.FACILITYNEST, wmsadmin.PL_DB a
WHERE Upper(a.db_logid)=upper(FACILITYNEST.WHSEID)
AND a.ISACTIVE=1
UNION
SELECT SERIALKEY,
  WHSEID COD_PLANTA,
  a.DB_ALIAS DESCR_PLANTA,
  ADDDATE DT_CADASTRO,
  EDITDATE DT_ATUALIZACAO
FROM WMWHSE3.FACILITYNEST, wmsadmin.PL_DB a
WHERE Upper(a.db_logid)=upper(FACILITYNEST.WHSEID)
AND a.ISACTIVE=1
UNION
SELECT SERIALKEY,
  WHSEID COD_PLANTA,
  a.DB_ALIAS DESCR_PLANTA,
  ADDDATE DT_CADASTRO,
  EDITDATE DT_ATUALIZACAO
FROM WMWHSE4.FACILITYNEST, wmsadmin.PL_DB a
WHERE Upper(a.db_logid)=upper(FACILITYNEST.WHSEID)
AND a.ISACTIVE=1
UNION
SELECT SERIALKEY,
  WHSEID COD_PLANTA,
  a.DB_ALIAS DESCR_PLANTA,
  ADDDATE DT_CADASTRO,
  EDITDATE DT_ATUALIZACAO
FROM WMWHSE5.FACILITYNEST, wmsadmin.PL_DB a
WHERE Upper(a.db_logid)=upper(FACILITYNEST.WHSEID)
AND a.ISACTIVE=1
UNION
SELECT SERIALKEY,
  WHSEID COD_PLANTA,
  a.DB_ALIAS DESCR_PLANTA,
  ADDDATE DT_CADASTRO,
  EDITDATE DT_ATUALIZACAO
FROM WMWHSE6.FACILITYNEST, wmsadmin.PL_DB a
WHERE Upper(a.db_logid)=upper(FACILITYNEST.WHSEID)
AND a.ISACTIVE=1
UNION
SELECT SERIALKEY,
  WHSEID COD_PLANTA,
  a.DB_ALIAS DESCR_PLANTA,
  ADDDATE DT_CADASTRO,
  EDITDATE DT_ATUALIZACAO
FROM WMWHSE7.FACILITYNEST, wmsadmin.PL_DB a
WHERE Upper(a.db_logid)=upper(FACILITYNEST.WHSEID)
AND a.ISACTIVE=1
UNION
SELECT SERIALKEY,
  WHSEID COD_PLANTA,
  a.DB_ALIAS DESCR_PLANTA,
  ADDDATE DT_CADASTRO,
  EDITDATE DT_ATUALIZACAO
FROM WMWHSE8.FACILITYNEST, wmsadmin.PL_DB a
WHERE Upper(a.db_logid)=upper(FACILITYNEST.WHSEID)
AND a.ISACTIVE=1
UNION
SELECT SERIALKEY,
  WHSEID COD_PLANTA,
  a.DB_ALIAS DESCR_PLANTA,
  ADDDATE DT_CADASTRO,
  EDITDATE DT_ATUALIZACAO
FROM WMWHSE9.FACILITYNEST, wmsadmin.PL_DB a
WHERE Upper(a.db_logid)=upper(FACILITYNEST.WHSEID)
AND a.ISACTIVE=1