SELECT DISTINCT
  SHO.WHSEID             ID_PLANTA,  
  CL.UDF2                NOME_PLANTA,  
  ZNFMD630.T$FILI$C      ID_FILIAL,
  ZNFMD001.T$DSCA$C      DESCR_FILIAL,
  ZNSLS401.T$UNEG$C      ID_UNEG,
  ZNINT002.T$DESC$C      DESCR_UNEG,
  ZNSLS401.T$ENTR$C      ENTREGA,
  ZNSLS401.T$PECL$C      PEDIDO,
  SHO.INVOICENUMBER      NOTA,
  SHO.LANE               SERIE,
  OXV.NOTES1             ETIQUETA,
  ZNSLS401.T$NOME$C      CLIENTE,
  ZNSLS401.T$ICLE$C      CPF_CNPJ,
  ZNSLS401.T$LOGE$C      ENDERECO,
  ZNSLS401.T$NUME$C      NUMERO,
  ZNSLS401.T$BAIE$C      BAIRRO,
  ZNSLS401.T$REFE$C      REFERENCIA,
  ZNSLS401.T$EMAE$C      EMAIL,
  ZNSLS401.T$TELE$C      TELEFONE_1,
  ZNSLS401.T$TE1E$C      TELEFONE_2,
  ZNSLS401.T$TE2E$C      TELEFONE_3,
  ZNSLS410.T$CONO$C      CONTRATO,
  SHD.ORIGINALQTY        QTD_VOL,
  ZNSLS401.T$ITPE$C      ID_TIPO_ENFTREGA,
  ZNSLS002.T$DSCA$C      DESCR_TIPO_ENTREGA,
  SHD.PRODUCT_WEIGHT     PESO,
  SHD.PRODUCT_CUBE       VOLUME,
  ZNSLS401.T$VLUN$C*
  SHD.ORIGINALQTY        VL_SEM_FRETE,
  ZNFMD630.T$VLFC$C      FRETE,
  ZNSLS401.T$VLFR$C      FRETE_SITE,
  (ZNSLS401.T$VLUN$C*
  SHD.ORIGINALQTY)+
  ZNSLS401.T$VLFR$C+
  ZNSLS401.T$VLDE$C-
  ZNSLS401.T$VLDI$C      VL_TOTAL,
  TCMCS080.T$DSCA        TRANSPORTADORA,
  TCMCS080.T$SEAK        APELIDO,
  ZNSLS401.T$CEPE$C      CEP,
  ZNSLS401.T$CIDE$C      CIDADE,
  ZNSLS401.T$UFEN$C      UF,
  ZNSLS400.T$IDCA$C      CANAL,
  ZNFMD630.T$CFRW$C      ID_TRANSP,     
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS401.T$DTEP$C-
    ZNSLS401.T$PZCD$C,'DD-MON-YYYY HH24:MI:SS'), 
      'DD-MON-YYYY HH24:MI:SS'), 'GMT') AT time zone 
     'America/Sao_Paulo') AS DATE)  DT_LIMITE,
  ZNSLS401.T$PZCD$C      PZ_CD,
  ZNSLS401.T$PZTR$C      PZ_TRANSIT,  
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS401.T$DTEP$C, 
    'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 
   'GMT') AT time zone 'America/Sao_Paulo') AS DATE)
                         DT_PROMET,  
  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS410.T$DTOC$C, 
    'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 
   'GMT') AT time zone 'America/Sao_Paulo') AS DATE)
                         DT_ETR,
  ZNFMD630.T$NCAR$C      CARGA,
  ZNSLS401.T$MGRT$C      CAPITAL_INTERIOR,
  SKU.DESCR              DESCRICAO
FROM       WMWHSE5.ORDERDETAIL SHD
INNER JOIN WMWHSE5.ORDERDETAILXVAS OXV 
        ON OXV.ORDERKEY = SHD.ORDERKEY
       AND OXV.ORDERLINENUMBER = SHD.ORDERLINENUMBER
INNER JOIN WMWHSE5.ORDERS SHO 
        ON SHO.ORDERKEY = SHD.ORDERKEY
INNER JOIN WMWHSE5.SKU SKU 
        ON SKU.SKU = SHD.SKU
 LEFT JOIN BAANDB.TWHINH431201@dLN01 WHINH431 
        ON WHINH431.T$SHPM = SUBSTR(SHD.EXTERNORDERKEY,5,9)
       AND TO_CHAR(WHINH431.T$PONO) = TO_CHAR(SHD.EXTERNLINENO)
 LEFT JOIN BAANDB.TZNSLS004201@dLN01 ZNSLS004 
        ON ZNSLS004.T$ORNO$C = WHINH431.T$WORN
       AND ZNSLS004.T$PONO$C = WHINH431.T$WPON
 LEFT JOIN BAANDB.TZNSLS401201@dLN01 ZNSLS401 
        ON ZNSLS401.T$NCIA$C = ZNSLS004.T$NCIA$C
       AND ZNSLS401.T$UNEG$C = ZNSLS004.T$UNEG$C
       AND ZNSLS401.T$PECL$C = ZNSLS004.T$PECL$C
       AND ZNSLS401.T$SQPD$C = ZNSLS004.T$SQPD$C
       AND ZNSLS401.T$ENTR$C = ZNSLS004.T$ENTR$C
       AND ZNSLS401.T$SEQU$C = ZNSLS004.T$SEQU$C
 LEFT JOIN BAANDB.TZNSLS400201@dLN01 ZNSLS400 
        ON ZNSLS400.T$NCIA$C = ZNSLS004.T$NCIA$C
       AND ZNSLS400.T$UNEG$C = ZNSLS004.T$UNEG$C
       AND ZNSLS400.T$PECL$C = ZNSLS004.T$PECL$C
       AND ZNSLS400.T$SQPD$C = ZNSLS004.T$SQPD$C
 LEFT JOIN ( SELECT A.T$NCIA$C, A.T$UNEG$C, A.T$PECL$C,
                    A.T$SQPD$C, A.T$ENTR$C, 
                    MIN(A.T$DTOC$C) T$DTOC$C, 
                    MIN(A.T$CONO$C) T$CONO$C
               FROM BAANDB.TZNSLS410201@dLN01 A
              WHERE A.T$POCO$C = 'ETR'
           GROUP BY A.T$NCIA$C, A.T$UNEG$C, A.T$PECL$C, 
                    A.T$SQPD$C, A.T$ENTR$C) ZNSLS410 
        ON ZNSLS410.T$NCIA$C = ZNSLS004.T$NCIA$C
       AND ZNSLS410.T$UNEG$C = ZNSLS004.T$UNEG$C
       AND ZNSLS410.T$PECL$C = ZNSLS004.T$PECL$C
       AND ZNSLS410.T$SQPD$C = ZNSLS004.T$SQPD$C
       AND ZNSLS410.T$ENTR$C = ZNSLS004.T$ENTR$C
 LEFT JOIN BAANDB.TZNFMD630201@dLN01 ZNFMD630 
        ON ZNFMD630.T$ORNO$C = WHINH431.T$WORN
 LEFT JOIN BAANDB.TZNFMD001201@dLN01 ZNFMD001 
        ON ZNFMD001.T$FILI$C = ZNFMD630.T$FILI$C
 LEFT JOIN BAANDB.TZNINT002201@dLN01 ZNINT002 
        ON ZNINT002.T$NCIA$C = ZNSLS401.T$NCIA$C
       AND ZNINT002.T$UNEG$C = ZNSLS401.T$UNEG$C
 LEFT JOIN BAANDB.TZNSLS002201@dLN01 ZNSLS002 
        ON ZNSLS002.T$TPEN$C = ZNSLS401.T$ITPE$C
 LEFT JOIN BAANDB.TTCMCS080201@dLN01 TCMCS080 
        ON TCMCS080.T$CFRW = ZNFMD630.T$CFRW$C
INNER JOIN ENTERPRISE.CODELKUP CL      
        ON UPPER(CL.UDF1) = SHO.WHSEID    
       AND CL.LISTNAME = 'SCHEMA'          
WHERE ZNSLS410.T$DTOC$C IS NOT NULL 
  AND OXV.NOTES1 IS NOT NULL
  AND NVL(TCMCS080.t$cfrw, 'N/A') IN (:Transportadora)
  AND TRUNC(CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS410.T$DTOC$C, 
            'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 
            'GMT') AT time zone 'America/Sao_Paulo') AS DATE))
      BETWEEN :DataETRDe
          AND :DataETRAte
ORDER BY DT_ETR, ZNINT002.T$DESC$C



=IIF(Parameters!Table.Value <> "AAA",                         
"SELECT  " &
"  SHO.WHSEID             ID_PLANTA,  " &  
"  CL.UDF2                NOME_PLANTA,  " &  
"  ZNFMD630.T$FILI$C      ID_FILIAL,  " &
"  ZNFMD001.T$DSCA$C      DESCR_FILIAL,  " &
"  ZNSLS401.T$UNEG$C      ID_UNEG,  " &
"  ZNINT002.T$DESC$C      DESCR_UNEG,  " &
"  ZNSLS401.T$ENTR$C      ENTREGA,  " &
"  ZNSLS401.T$PECL$C      PEDIDO,  " &
"  SHO.INVOICENUMBER      NOTA,  " &
"  SHO.LANE               SERIE,  " &
"  OXV.NOTES1             ETIQUETA,  " &
"  ZNSLS401.T$NOME$C      CLIENTE,  " &
"  ZNSLS401.T$ICLE$C      CPF_CNPJ,  " &
"  ZNSLS401.T$LOGE$C      ENDERECO,  " &
"  ZNSLS401.T$NUME$C      NUMERO,  " &
"  ZNSLS401.T$BAIE$C      BAIRRO,  " &
"  ZNSLS401.T$REFE$C      REFERENCIA,  " &
"  ZNSLS401.T$EMAE$C      EMAIL,  " &
"  ZNSLS401.T$TELE$C      TELEFONE_1,  " &
"  ZNSLS401.T$TE1E$C      TELEFONE_2,  " &
"  ZNSLS401.T$TE2E$C      TELEFONE_3,  " &
"  ZNSLS410.T$CONO$C      CONTRATO,  " &
"  SHD.ORIGINALQTY        QTD_VOL,  " &
"  ZNSLS401.T$ITPE$C      ID_TIPO_ENFTREGA,  " &
"  ZNSLS002.T$DSCA$C      DESCR_TIPO_ENTREGA,  " &
"  SHD.PRODUCT_WEIGHT     PESO,  " &
"  SHD.PRODUCT_CUBE       VOLUME,  " &
"  ZNSLS401.T$VLUN$C*  " &
"  SHD.ORIGINALQTY        VL_SEM_FRETE,  " &
"  ZNFMD630.T$VLFC$C      FRETE,  " &
"  ZNSLS401.T$VLFR$C      FRETE_SITE,  " &
"  (ZNSLS401.T$VLUN$C*  " &
"  SHD.ORIGINALQTY)+  " &
"  ZNSLS401.T$VLFR$C+  " &
"  ZNSLS401.T$VLDE$C-  " &
"  ZNSLS401.T$VLDI$C      VL_TOTAL,  " &
"  TCMCS080.T$DSCA        TRANSPORTADORA,  " &
"  TCMCS080.T$SEAK        APELIDO,  " &
"  ZNSLS401.T$CEPE$C      CEP,  " &
"  ZNSLS401.T$CIDE$C      CIDADE,  " &
"  ZNSLS401.T$UFEN$C      UF,  " &
"  ZNSLS400.T$IDCA$C      CANAL,  " &
"  ZNFMD630.T$CFRW$C      ID_TRANSP,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS401.T$DTEP$C-  " &
"  ZNSLS401.T$PZCD$C,'DD-MON-YYYY HH24:MI:SS'),  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'GMT') AT time zone  " &
"     'America/Sao_Paulo') AS DATE)  DT_LIMITE,     "&
"  ZNSLS401.T$PZCD$C      PZ_CD,  " &
"  ZNSLS401.T$PZTR$C      PZ_TRANSIT,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS401.T$DTEP$C,  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'),  " &
"  'GMT') AT time zone 'America/Sao_Paulo') AS DATE)  " &
"                         DT_PROMET,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS410.T$DTOC$C,  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'),  " &
"  'GMT') AT time zone 'America/Sao_Paulo') AS DATE)  " &
"                         DT_ETR,  " &
"  ZNFMD630.T$NCAR$C      CARGA,  " &
"  ZNSLS401.T$MGRT$C      CAPITAL_INTERIOR,  " &
"  SKU.DESCR              DESCRICAO  " &
"FROM       " + Parameters!Table.Value + ".ORDERDETAIL SHD  " &
"INNER JOIN " + Parameters!Table.Value + ".ORDERDETAILXVAS OXV  " &
"        ON OXV.ORDERKEY = SHD.ORDERKEY  " &
"AND OXV.ORDERLINENUMBER = SHD.ORDERLINENUMBER  " &
"INNER JOIN " + Parameters!Table.Value + ".ORDERS SHO  " &
"        ON SHO.ORDERKEY = SHD.ORDERKEY  " &
"INNER JOIN " + Parameters!Table.Value + ".SKU SKU  " &
"         ON SKU.SKU = SHD.SKU  " &
" LEFT JOIN BAANDB.TWHINH431201@dLN01 WHINH431  " &
" ON WHINH431.T$SHPM = SUBSTR(SHD.EXTERNORDERKEY,5,9)  " &
"AND TO_CHAR(WHINH431.T$PONO) = TO_CHAR(SHD.EXTERNLINENO)  " &
" LEFT JOIN BAANDB.TZNSLS004201@dLN01 ZNSLS004  " &
"        ON ZNSLS004.T$ORNO$C = WHINH431.T$WORN  " &
"       AND ZNSLS004.T$PONO$C = WHINH431.T$WPON  " &
" LEFT JOIN BAANDB.TZNSLS401201@dLN01 ZNSLS401  " &
"        ON ZNSLS401.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS401.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS401.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS401.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
"       AND ZNSLS401.T$ENTR$C = ZNSLS004.T$ENTR$C  " &
"       AND ZNSLS401.T$SEQU$C = ZNSLS004.T$SEQU$C  " &
" LEFT JOIN BAANDB.TZNSLS400201@dLN01 ZNSLS400  " &
"        ON ZNSLS400.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS400.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS400.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS400.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
" LEFT JOIN ( SELECT A.T$NCIA$C, A.T$UNEG$C, A.T$PECL$C,  " &
"                    A.T$SQPD$C, A.T$ENTR$C,  " &
"                    MIN(A.T$DTOC$C) T$DTOC$C,  " &
"                    MIN(A.T$CONO$C) T$CONO$C  " &
"               FROM BAANDB.TZNSLS410201@dLN01 A  " &
"              WHERE A.T$POCO$C = 'ETR'  " &
"           GROUP BY A.T$NCIA$C, A.T$UNEG$C, A.T$PECL$C,  " &
"                    A.T$SQPD$C, A.T$ENTR$C) ZNSLS410  " &
"        ON ZNSLS410.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS410.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS410.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS410.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
"       AND ZNSLS410.T$ENTR$C = ZNSLS004.T$ENTR$C  " &
" LEFT JOIN BAANDB.TZNFMD630201@dLN01 ZNFMD630  " &
"        ON ZNFMD630.T$ORNO$C = WHINH431.T$WORN  " &
" LEFT JOIN BAANDB.TZNFMD001201@dLN01 ZNFMD001  " &
"        ON ZNFMD001.T$FILI$C = ZNFMD630.T$FILI$C  " &
" LEFT JOIN BAANDB.TZNINT002201@dLN01 ZNINT002  " &
"        ON ZNINT002.T$NCIA$C = ZNSLS401.T$NCIA$C  " &
"       AND ZNINT002.T$UNEG$C = ZNSLS401.T$UNEG$C  " &
" LEFT JOIN BAANDB.TZNSLS002201@dLN01 ZNSLS002  " &
"        ON ZNSLS002.T$TPEN$C = ZNSLS401.T$ITPE$C  " &
" LEFT JOIN BAANDB.TTCMCS080201@dLN01 TCMCS080  " &
"        ON TCMCS080.T$CFRW = ZNFMD630.T$CFRW$C  " &
"INNER JOIN ENTERPRISE.CODELKUP CL  " &   
"        ON UPPER(CL.UDF1) = SHO.WHSEID  " &    
"       AND CL.LISTNAME = 'SCHEMA'  " &        
"WHERE ZNSLS410.T$DTOC$C IS NOT NULL  " &
"  AND OXV.NOTES1 IS NOT NULL  " &
"AND NVL(TCMCS080.t$cfrw, 'N/A') IN (" + Replace(("'" + JOIN(Parameters!Transportadora.Value, "',") + "'"),",",",'") + ")  " &
"  AND Trunc(CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS410.T$DTOC$C,  " &
"              'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')  " &
"                AT time zone 'America/Sao_Paulo') AS DATE))  " &
"      Between '" + Parameters!DataETRDe.Value + "'  " &
"          And '" + Parameters!DataETRAte.Value + "'  " &
"ORDER BY DT_ETR, DESCR_UNEG  "
,
"SELECT  " &
"  SHO.WHSEID             ID_PLANTA,  " &  
"  CL.UDF2                NOME_PLANTA,  " &  
"  ZNFMD630.T$FILI$C      ID_FILIAL,  " &
"  ZNFMD001.T$DSCA$C      DESCR_FILIAL,  " &
"  ZNSLS401.T$UNEG$C      ID_UNEG,  " &
"  ZNINT002.T$DESC$C      DESCR_UNEG,  " &
"  ZNSLS401.T$ENTR$C      ENTREGA,  " &
"  ZNSLS401.T$PECL$C      PEDIDO,  " &
"  SHO.INVOICENUMBER      NOTA,  " &
"  SHO.LANE               SERIE,  " &
"  OXV.NOTES1             ETIQUETA,  " &
"  ZNSLS401.T$NOME$C      CLIENTE,  " &
"  ZNSLS401.T$ICLE$C      CPF_CNPJ,  " &
"  ZNSLS401.T$LOGE$C      ENDERECO,  " &
"  ZNSLS401.T$NUME$C      NUMERO,  " &
"  ZNSLS401.T$BAIE$C      BAIRRO,  " &
"  ZNSLS401.T$REFE$C      REFERENCIA,  " &
"  ZNSLS401.T$EMAE$C      EMAIL,  " &
"  ZNSLS401.T$TELE$C      TELEFONE_1,  " &
"  ZNSLS401.T$TE1E$C      TELEFONE_2,  " &
"  ZNSLS401.T$TE2E$C      TELEFONE_3,  " &
"  ZNSLS410.T$CONO$C      CONTRATO,  " &
"  SHD.ORIGINALQTY        QTD_VOL,  " &
"  ZNSLS401.T$ITPE$C      ID_TIPO_ENFTREGA,  " &
"  ZNSLS002.T$DSCA$C      DESCR_TIPO_ENTREGA,  " &
"  SHD.PRODUCT_WEIGHT     PESO,  " &
"  SHD.PRODUCT_CUBE       VOLUME,  " &
"  ZNSLS401.T$VLUN$C*  " &
"  SHD.ORIGINALQTY        VL_SEM_FRETE,  " &
"  ZNFMD630.T$VLFC$C      FRETE,  " &
"  ZNSLS401.T$VLFR$C      FRETE_SITE,  " &
"  (ZNSLS401.T$VLUN$C*  " &
"  SHD.ORIGINALQTY)+  " &
"  ZNSLS401.T$VLFR$C+  " &
"  ZNSLS401.T$VLDE$C-  " &
"  ZNSLS401.T$VLDI$C      VL_TOTAL,  " &
"  TCMCS080.T$DSCA        TRANSPORTADORA,  " &
"  TCMCS080.T$SEAK        APELIDO,  " &
"  ZNSLS401.T$CEPE$C      CEP,  " &
"  ZNSLS401.T$CIDE$C      CIDADE,  " &
"  ZNSLS401.T$UFEN$C      UF,  " &
"  ZNSLS400.T$IDCA$C      CANAL,  " &
"  ZNFMD630.T$CFRW$C      ID_TRANSP,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS401.T$DTEP$C-  " &
"  ZNSLS401.T$PZCD$C,'DD-MON-YYYY HH24:MI:SS'),  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'GMT') AT time zone  " &
"     'America/Sao_Paulo') AS DATE)  DT_LIMITE,  " &
"  ZNSLS401.T$PZCD$C      PZ_CD,  " &
"  ZNSLS401.T$PZTR$C      PZ_TRANSIT,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS401.T$DTEP$C,  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'),  " &
"  'GMT') AT time zone 'America/Sao_Paulo') AS DATE)  " &
"                         DT_PROMET,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS410.T$DTOC$C,  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'),  " &
"  'GMT') AT time zone 'America/Sao_Paulo') AS DATE)  " &
"                         DT_ETR,  " &
"  ZNFMD630.T$NCAR$C      CARGA,  " &
"  ZNSLS401.T$MGRT$C      CAPITAL_INTERIOR,  " &
"  SKU.DESCR              DESCRICAO  " &
"FROM       WMWHSE1.ORDERDETAIL SHD  " &
"INNER JOIN WMWHSE1.ORDERDETAILXVAS OXV  " &
"        ON OXV.ORDERKEY = SHD.ORDERKEY  " &
"AND OXV.ORDERLINENUMBER = SHD.ORDERLINENUMBER  " &
"INNER JOIN WMWHSE1.ORDERS SHO  " &
"        ON SHO.ORDERKEY = SHD.ORDERKEY  " &
"INNER JOIN WMWHSE1.SKU SKU  " &
"         ON SKU.SKU = SHD.SKU  " &
" LEFT JOIN BAANDB.TWHINH431201@dLN01 WHINH431  " &
" ON WHINH431.T$SHPM = SUBSTR(SHD.EXTERNORDERKEY,5,9)  " &
"AND TO_CHAR(WHINH431.T$PONO) = TO_CHAR(SHD.EXTERNLINENO)  " &
" LEFT JOIN BAANDB.TZNSLS004201@dLN01 ZNSLS004  " &
"        ON ZNSLS004.T$ORNO$C = WHINH431.T$WORN  " &
"       AND ZNSLS004.T$PONO$C = WHINH431.T$WPON  " &
" LEFT JOIN BAANDB.TZNSLS401201@dLN01 ZNSLS401  " &
"        ON ZNSLS401.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS401.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS401.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS401.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
"       AND ZNSLS401.T$ENTR$C = ZNSLS004.T$ENTR$C  " &
"       AND ZNSLS401.T$SEQU$C = ZNSLS004.T$SEQU$C  " &
" LEFT JOIN BAANDB.TZNSLS400201@dLN01 ZNSLS400  " &
"        ON ZNSLS400.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS400.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS400.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS400.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
" LEFT JOIN ( SELECT A.T$NCIA$C, A.T$UNEG$C, A.T$PECL$C,  " &
"                    A.T$SQPD$C, A.T$ENTR$C,  " &
"                    MIN(A.T$DTOC$C) T$DTOC$C,  " &
"                    MIN(A.T$CONO$C) T$CONO$C  " &
"               FROM BAANDB.TZNSLS410201@dLN01 A  " &
"              WHERE A.T$POCO$C = 'ETR'  " &
"           GROUP BY A.T$NCIA$C, A.T$UNEG$C, A.T$PECL$C,  " &
"                    A.T$SQPD$C, A.T$ENTR$C) ZNSLS410  " &
"        ON ZNSLS410.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS410.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS410.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS410.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
"       AND ZNSLS410.T$ENTR$C = ZNSLS004.T$ENTR$C  " &
" LEFT JOIN BAANDB.TZNFMD630201@dLN01 ZNFMD630  " &
"        ON ZNFMD630.T$ORNO$C = WHINH431.T$WORN  " &
" LEFT JOIN BAANDB.TZNFMD001201@dLN01 ZNFMD001  " &
"        ON ZNFMD001.T$FILI$C = ZNFMD630.T$FILI$C  " &
" LEFT JOIN BAANDB.TZNINT002201@dLN01 ZNINT002  " &
"        ON ZNINT002.T$NCIA$C = ZNSLS401.T$NCIA$C  " &
"       AND ZNINT002.T$UNEG$C = ZNSLS401.T$UNEG$C  " &
" LEFT JOIN BAANDB.TZNSLS002201@dLN01 ZNSLS002  " &
"        ON ZNSLS002.T$TPEN$C = ZNSLS401.T$ITPE$C  " &
" LEFT JOIN BAANDB.TTCMCS080201@dLN01 TCMCS080  " &
"        ON TCMCS080.T$CFRW = ZNFMD630.T$CFRW$C  " &
"INNER JOIN ENTERPRISE.CODELKUP CL  " &   
"        ON UPPER(CL.UDF1) = SHO.WHSEID  " &    
"       AND CL.LISTNAME = 'SCHEMA'  " &        
"WHERE ZNSLS410.T$DTOC$C IS NOT NULL  " &
"  AND OXV.NOTES1 IS NOT NULL  " &
"AND NVL(TCMCS080.t$cfrw, 'N/A') IN (" + Replace(("'" + JOIN(Parameters!Transportadora.Value, "',") + "'"),",",",'") + ")  " &
"  AND Trunc(CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS410.T$DTOC$C,  " &
"              'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')  " &
"                AT time zone 'America/Sao_Paulo') AS DATE))  " &
"      Between '" + Parameters!DataETRDe.Value + "'  " &
"          And '" + Parameters!DataETRAte.Value + "'  " &
"  " &
"UNION  " &
"  " &
"SELECT  " &
"  SHO.WHSEID             ID_PLANTA,  " &  
"  CL.UDF2                NOME_PLANTA,  " &  
"  ZNFMD630.T$FILI$C      ID_FILIAL,  " &
"  ZNFMD001.T$DSCA$C      DESCR_FILIAL,  " &
"  ZNSLS401.T$UNEG$C      ID_UNEG,  " &
"  ZNINT002.T$DESC$C      DESCR_UNEG,  " &
"  ZNSLS401.T$ENTR$C      ENTREGA,  " &
"  ZNSLS401.T$PECL$C      PEDIDO,  " &
"  SHO.INVOICENUMBER      NOTA,  " &
"  SHO.LANE               SERIE,  " &
"  OXV.NOTES1             ETIQUETA,  " &
"  ZNSLS401.T$NOME$C      CLIENTE,  " &
"  ZNSLS401.T$ICLE$C      CPF_CNPJ,  " &
"  ZNSLS401.T$LOGE$C      ENDERECO,  " &
"  ZNSLS401.T$NUME$C      NUMERO,  " &
"  ZNSLS401.T$BAIE$C      BAIRRO,  " &
"  ZNSLS401.T$REFE$C      REFERENCIA,  " &
"  ZNSLS401.T$EMAE$C      EMAIL,  " &
"  ZNSLS401.T$TELE$C      TELEFONE_1,  " &
"  ZNSLS401.T$TE1E$C      TELEFONE_2,  " &
"  ZNSLS401.T$TE2E$C      TELEFONE_3,  " &
"  ZNSLS410.T$CONO$C      CONTRATO,  " &
"  SHD.ORIGINALQTY        QTD_VOL,  " &
"  ZNSLS401.T$ITPE$C      ID_TIPO_ENFTREGA,  " &
"  ZNSLS002.T$DSCA$C      DESCR_TIPO_ENTREGA,  " &
"  SHD.PRODUCT_WEIGHT     PESO,  " &
"  SHD.PRODUCT_CUBE       VOLUME,  " &
"  ZNSLS401.T$VLUN$C*  " &
"  SHD.ORIGINALQTY        VL_SEM_FRETE,  " &
"  ZNFMD630.T$VLFC$C      FRETE,  " &
"  ZNSLS401.T$VLFR$C      FRETE_SITE,  " &
"  (ZNSLS401.T$VLUN$C*  " &
"  SHD.ORIGINALQTY)+  " &
"  ZNSLS401.T$VLFR$C+  " &
"  ZNSLS401.T$VLDE$C-  " &
"  ZNSLS401.T$VLDI$C      VL_TOTAL,  " &
"  TCMCS080.T$DSCA        TRANSPORTADORA,  " &
"  TCMCS080.T$SEAK        APELIDO,  " &
"  ZNSLS401.T$CEPE$C      CEP,  " &
"  ZNSLS401.T$CIDE$C      CIDADE,  " &
"  ZNSLS401.T$UFEN$C      UF,  " &
"  ZNSLS400.T$IDCA$C      CANAL,  " &
"  ZNFMD630.T$CFRW$C      ID_TRANSP,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS401.T$DTEP$C-  " &
"  ZNSLS401.T$PZCD$C,'DD-MON-YYYY HH24:MI:SS'),  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'GMT') AT time zone  " &
"     'America/Sao_Paulo') AS DATE)  DT_LIMITE,  " &
"  ZNSLS401.T$PZCD$C      PZ_CD,  " &
"  ZNSLS401.T$PZTR$C      PZ_TRANSIT,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS401.T$DTEP$C,  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'),  " &
"  'GMT') AT time zone 'America/Sao_Paulo') AS DATE)  " &
"                         DT_PROMET,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS410.T$DTOC$C,  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'),  " &
"  'GMT') AT time zone 'America/Sao_Paulo') AS DATE)  " &
"                         DT_ETR,  " &
"  ZNFMD630.T$NCAR$C      CARGA,  " &
"  ZNSLS401.T$MGRT$C      CAPITAL_INTERIOR,  " &
"  SKU.DESCR              DESCRICAO  " &
"FROM       WMWHSE2.ORDERDETAIL SHD  " &
"INNER JOIN WMWHSE2.ORDERDETAILXVAS OXV  " &
"        ON OXV.ORDERKEY = SHD.ORDERKEY  " &
"AND OXV.ORDERLINENUMBER = SHD.ORDERLINENUMBER  " &
"INNER JOIN WMWHSE2.ORDERS SHO  " &
"        ON SHO.ORDERKEY = SHD.ORDERKEY  " &
"INNER JOIN WMWHSE2.SKU SKU  " &
"         ON SKU.SKU = SHD.SKU  " &
" LEFT JOIN BAANDB.TWHINH431201@dLN01 WHINH431  " &
" ON WHINH431.T$SHPM = SUBSTR(SHD.EXTERNORDERKEY,5,9)  " &
"AND TO_CHAR(WHINH431.T$PONO) = TO_CHAR(SHD.EXTERNLINENO)  " &
" LEFT JOIN BAANDB.TZNSLS004201@dLN01 ZNSLS004  " &
"        ON ZNSLS004.T$ORNO$C = WHINH431.T$WORN  " &
"       AND ZNSLS004.T$PONO$C = WHINH431.T$WPON  " &
" LEFT JOIN BAANDB.TZNSLS401201@dLN01 ZNSLS401  " &
"        ON ZNSLS401.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS401.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS401.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS401.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
"       AND ZNSLS401.T$ENTR$C = ZNSLS004.T$ENTR$C  " &
"       AND ZNSLS401.T$SEQU$C = ZNSLS004.T$SEQU$C  " &
" LEFT JOIN BAANDB.TZNSLS400201@dLN01 ZNSLS400  " &
"        ON ZNSLS400.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS400.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS400.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS400.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
" LEFT JOIN ( SELECT A.T$NCIA$C, A.T$UNEG$C, A.T$PECL$C,  " &
"                    A.T$SQPD$C, A.T$ENTR$C,  " &
"                    MIN(A.T$DTOC$C) T$DTOC$C,  " &
"                    MIN(A.T$CONO$C) T$CONO$C  " &
"               FROM BAANDB.TZNSLS410201@dLN01 A  " &
"              WHERE A.T$POCO$C = 'ETR'  " &
"           GROUP BY A.T$NCIA$C, A.T$UNEG$C, A.T$PECL$C,  " &
"                    A.T$SQPD$C, A.T$ENTR$C) ZNSLS410  " &
"        ON ZNSLS410.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS410.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS410.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS410.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
"       AND ZNSLS410.T$ENTR$C = ZNSLS004.T$ENTR$C  " &
" LEFT JOIN BAANDB.TZNFMD630201@dLN01 ZNFMD630  " &
"        ON ZNFMD630.T$ORNO$C = WHINH431.T$WORN  " &
" LEFT JOIN BAANDB.TZNFMD001201@dLN01 ZNFMD001  " &
"        ON ZNFMD001.T$FILI$C = ZNFMD630.T$FILI$C  " &
" LEFT JOIN BAANDB.TZNINT002201@dLN01 ZNINT002  " &
"        ON ZNINT002.T$NCIA$C = ZNSLS401.T$NCIA$C  " &
"       AND ZNINT002.T$UNEG$C = ZNSLS401.T$UNEG$C  " &
" LEFT JOIN BAANDB.TZNSLS002201@dLN01 ZNSLS002  " &
"        ON ZNSLS002.T$TPEN$C = ZNSLS401.T$ITPE$C  " &
" LEFT JOIN BAANDB.TTCMCS080201@dLN01 TCMCS080  " &
"        ON TCMCS080.T$CFRW = ZNFMD630.T$CFRW$C  " &
"INNER JOIN ENTERPRISE.CODELKUP CL  " &   
"        ON UPPER(CL.UDF1) = SHO.WHSEID  " &    
"       AND CL.LISTNAME = 'SCHEMA'  " &        
"WHERE ZNSLS410.T$DTOC$C IS NOT NULL  " &
"  AND OXV.NOTES1 IS NOT NULL  " &
"AND NVL(TCMCS080.t$cfrw, 'N/A') IN (" + Replace(("'" + JOIN(Parameters!Transportadora.Value, "',") + "'"),",",",'") + ")  " &
"  AND Trunc(CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS410.T$DTOC$C,  " &
"              'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')  " &
"                AT time zone 'America/Sao_Paulo') AS DATE))  " &
"      Between '" + Parameters!DataETRDe.Value + "'  " &
"          And '" + Parameters!DataETRAte.Value + "'  " &
"  " &
"UNION  " &
"  " &
"SELECT  " &
"  SHO.WHSEID             ID_PLANTA,  " &  
"  CL.UDF2                NOME_PLANTA,  " &  
"  ZNFMD630.T$FILI$C      ID_FILIAL,  " &
"  ZNFMD001.T$DSCA$C      DESCR_FILIAL,  " &
"  ZNSLS401.T$UNEG$C      ID_UNEG,  " &
"  ZNINT002.T$DESC$C      DESCR_UNEG,  " &
"  ZNSLS401.T$ENTR$C      ENTREGA,  " &
"  ZNSLS401.T$PECL$C      PEDIDO,  " &
"  SHO.INVOICENUMBER      NOTA,  " &
"  SHO.LANE               SERIE,  " &
"  OXV.NOTES1             ETIQUETA,  " &
"  ZNSLS401.T$NOME$C      CLIENTE,  " &
"  ZNSLS401.T$ICLE$C      CPF_CNPJ,  " &
"  ZNSLS401.T$LOGE$C      ENDERECO,  " &
"  ZNSLS401.T$NUME$C      NUMERO,  " &
"  ZNSLS401.T$BAIE$C      BAIRRO,  " &
"  ZNSLS401.T$REFE$C      REFERENCIA,  " &
"  ZNSLS401.T$EMAE$C      EMAIL,  " &
"  ZNSLS401.T$TELE$C      TELEFONE_1,  " &
"  ZNSLS401.T$TE1E$C      TELEFONE_2,  " &
"  ZNSLS401.T$TE2E$C      TELEFONE_3,  " &
"  ZNSLS410.T$CONO$C      CONTRATO,  " &
"  SHD.ORIGINALQTY        QTD_VOL,  " &
"  ZNSLS401.T$ITPE$C      ID_TIPO_ENFTREGA,  " &
"  ZNSLS002.T$DSCA$C      DESCR_TIPO_ENTREGA,  " &
"  SHD.PRODUCT_WEIGHT     PESO,  " &
"  SHD.PRODUCT_CUBE       VOLUME,  " &
"  ZNSLS401.T$VLUN$C*  " &
"  SHD.ORIGINALQTY        VL_SEM_FRETE,  " &
"  ZNFMD630.T$VLFC$C      FRETE,  " &
"  ZNSLS401.T$VLFR$C      FRETE_SITE,  " &
"  (ZNSLS401.T$VLUN$C*  " &
"  SHD.ORIGINALQTY)+  " &
"  ZNSLS401.T$VLFR$C+  " &
"  ZNSLS401.T$VLDE$C-  " &
"  ZNSLS401.T$VLDI$C      VL_TOTAL,  " &
"  TCMCS080.T$DSCA        TRANSPORTADORA,  " &
"  TCMCS080.T$SEAK        APELIDO,  " &
"  ZNSLS401.T$CEPE$C      CEP,  " &
"  ZNSLS401.T$CIDE$C      CIDADE,  " &
"  ZNSLS401.T$UFEN$C      UF,  " &
"  ZNSLS400.T$IDCA$C      CANAL,  " &
"  ZNFMD630.T$CFRW$C      ID_TRANSP,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS401.T$DTEP$C-  " &
"  ZNSLS401.T$PZCD$C,'DD-MON-YYYY HH24:MI:SS'),  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'GMT') AT time zone  " &
"     'America/Sao_Paulo') AS DATE)  DT_LIMITE,  " &
"  ZNSLS401.T$PZCD$C      PZ_CD,  " &
"  ZNSLS401.T$PZTR$C      PZ_TRANSIT,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS401.T$DTEP$C,  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'),  " &
"  'GMT') AT time zone 'America/Sao_Paulo') AS DATE)  " &
"                         DT_PROMET,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS410.T$DTOC$C,  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'),  " &
"  'GMT') AT time zone 'America/Sao_Paulo') AS DATE)  " &
"                         DT_ETR,  " &
"  ZNFMD630.T$NCAR$C      CARGA,  " &
"  ZNSLS401.T$MGRT$C      CAPITAL_INTERIOR,  " &
"  SKU.DESCR              DESCRICAO  " &
"FROM       WMWHSE3.ORDERDETAIL SHD  " &
"INNER JOIN WMWHSE3.ORDERDETAILXVAS OXV  " &
"        ON OXV.ORDERKEY = SHD.ORDERKEY  " &
"AND OXV.ORDERLINENUMBER = SHD.ORDERLINENUMBER  " &
"INNER JOIN WMWHSE3.ORDERS SHO  " &
"        ON SHO.ORDERKEY = SHD.ORDERKEY  " &
"INNER JOIN WMWHSE3.SKU SKU  " &
"         ON SKU.SKU = SHD.SKU  " &
" LEFT JOIN BAANDB.TWHINH431201@dLN01 WHINH431  " &
" ON WHINH431.T$SHPM = SUBSTR(SHD.EXTERNORDERKEY,5,9)  " &
"AND TO_CHAR(WHINH431.T$PONO) = TO_CHAR(SHD.EXTERNLINENO)  " &
" LEFT JOIN BAANDB.TZNSLS004201@dLN01 ZNSLS004  " &
"        ON ZNSLS004.T$ORNO$C = WHINH431.T$WORN  " &
"       AND ZNSLS004.T$PONO$C = WHINH431.T$WPON  " &
" LEFT JOIN BAANDB.TZNSLS401201@dLN01 ZNSLS401  " &
"        ON ZNSLS401.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS401.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS401.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS401.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
"       AND ZNSLS401.T$ENTR$C = ZNSLS004.T$ENTR$C  " &
"       AND ZNSLS401.T$SEQU$C = ZNSLS004.T$SEQU$C  " &
" LEFT JOIN BAANDB.TZNSLS400201@dLN01 ZNSLS400  " &
"        ON ZNSLS400.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS400.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS400.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS400.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
" LEFT JOIN ( SELECT A.T$NCIA$C, A.T$UNEG$C, A.T$PECL$C,  " &
"                    A.T$SQPD$C, A.T$ENTR$C,  " &
"                    MIN(A.T$DTOC$C) T$DTOC$C,  " &
"                    MIN(A.T$CONO$C) T$CONO$C  " &
"               FROM BAANDB.TZNSLS410201@dLN01 A  " &
"              WHERE A.T$POCO$C = 'ETR'  " &
"           GROUP BY A.T$NCIA$C, A.T$UNEG$C, A.T$PECL$C,  " &
"                    A.T$SQPD$C, A.T$ENTR$C) ZNSLS410  " &
"        ON ZNSLS410.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS410.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS410.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS410.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
"       AND ZNSLS410.T$ENTR$C = ZNSLS004.T$ENTR$C  " &
" LEFT JOIN BAANDB.TZNFMD630201@dLN01 ZNFMD630  " &
"        ON ZNFMD630.T$ORNO$C = WHINH431.T$WORN  " &
" LEFT JOIN BAANDB.TZNFMD001201@dLN01 ZNFMD001  " &
"        ON ZNFMD001.T$FILI$C = ZNFMD630.T$FILI$C  " &
" LEFT JOIN BAANDB.TZNINT002201@dLN01 ZNINT002  " &
"        ON ZNINT002.T$NCIA$C = ZNSLS401.T$NCIA$C  " &
"       AND ZNINT002.T$UNEG$C = ZNSLS401.T$UNEG$C  " &
" LEFT JOIN BAANDB.TZNSLS002201@dLN01 ZNSLS002  " &
"        ON ZNSLS002.T$TPEN$C = ZNSLS401.T$ITPE$C  " &
" LEFT JOIN BAANDB.TTCMCS080201@dLN01 TCMCS080  " &
"        ON TCMCS080.T$CFRW = ZNFMD630.T$CFRW$C  " &
"INNER JOIN ENTERPRISE.CODELKUP CL  " &   
"        ON UPPER(CL.UDF1) = SHO.WHSEID  " &    
"       AND CL.LISTNAME = 'SCHEMA'  " &        
"WHERE ZNSLS410.T$DTOC$C IS NOT NULL  " &
"  AND OXV.NOTES1 IS NOT NULL  " &
"AND NVL(TCMCS080.t$cfrw, 'N/A') IN (" + Replace(("'" + JOIN(Parameters!Transportadora.Value, "',") + "'"),",",",'") + ")  " &
"  AND Trunc(CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS410.T$DTOC$C,  " &
"              'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')  " &
"                AT time zone 'America/Sao_Paulo') AS DATE))  " &
"      Between '" + Parameters!DataETRDe.Value + "'  " &
"          And '" + Parameters!DataETRAte.Value + "'  " &
"  " &
"UNION  " &
"  " &
"SELECT  " &
"  SHO.WHSEID             ID_PLANTA,  " &  
"  CL.UDF2                NOME_PLANTA,  " &  
"  ZNFMD630.T$FILI$C      ID_FILIAL,  " &
"  ZNFMD001.T$DSCA$C      DESCR_FILIAL,  " &
"  ZNSLS401.T$UNEG$C      ID_UNEG,  " &
"  ZNINT002.T$DESC$C      DESCR_UNEG,  " &
"  ZNSLS401.T$ENTR$C      ENTREGA,  " &
"  ZNSLS401.T$PECL$C      PEDIDO,  " &
"  SHO.INVOICENUMBER      NOTA,  " &
"  SHO.LANE               SERIE,  " &
"  OXV.NOTES1             ETIQUETA,  " &
"  ZNSLS401.T$NOME$C      CLIENTE,  " &
"  ZNSLS401.T$ICLE$C      CPF_CNPJ,  " &
"  ZNSLS401.T$LOGE$C      ENDERECO,  " &
"  ZNSLS401.T$NUME$C      NUMERO,  " &
"  ZNSLS401.T$BAIE$C      BAIRRO,  " &
"  ZNSLS401.T$REFE$C      REFERENCIA,  " &
"  ZNSLS401.T$EMAE$C      EMAIL,  " &
"  ZNSLS401.T$TELE$C      TELEFONE_1,  " &
"  ZNSLS401.T$TE1E$C      TELEFONE_2,  " &
"  ZNSLS401.T$TE2E$C      TELEFONE_3,  " &
"  ZNSLS410.T$CONO$C      CONTRATO,  " &
"  SHD.ORIGINALQTY        QTD_VOL,  " &
"  ZNSLS401.T$ITPE$C      ID_TIPO_ENFTREGA,  " &
"  ZNSLS002.T$DSCA$C      DESCR_TIPO_ENTREGA,  " &
"  SHD.PRODUCT_WEIGHT     PESO,  " &
"  SHD.PRODUCT_CUBE       VOLUME,  " &
"  ZNSLS401.T$VLUN$C*  " &
"  SHD.ORIGINALQTY        VL_SEM_FRETE,  " &
"  ZNFMD630.T$VLFC$C      FRETE,  " &
"  ZNSLS401.T$VLFR$C      FRETE_SITE,  " &
"  (ZNSLS401.T$VLUN$C*  " &
"  SHD.ORIGINALQTY)+  " &
"  ZNSLS401.T$VLFR$C+  " &
"  ZNSLS401.T$VLDE$C-  " &
"  ZNSLS401.T$VLDI$C      VL_TOTAL,  " &
"  TCMCS080.T$DSCA        TRANSPORTADORA,  " &
"  TCMCS080.T$SEAK        APELIDO,  " &
"  ZNSLS401.T$CEPE$C      CEP,  " &
"  ZNSLS401.T$CIDE$C      CIDADE,  " &
"  ZNSLS401.T$UFEN$C      UF,  " &
"  ZNSLS400.T$IDCA$C      CANAL,  " &
"  ZNFMD630.T$CFRW$C      ID_TRANSP,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS401.T$DTEP$C-  " &
"  ZNSLS401.T$PZCD$C,'DD-MON-YYYY HH24:MI:SS'),  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'GMT') AT time zone  " &
"     'America/Sao_Paulo') AS DATE)  DT_LIMITE,  " &
"  ZNSLS401.T$PZCD$C      PZ_CD,  " &
"  ZNSLS401.T$PZTR$C      PZ_TRANSIT,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS401.T$DTEP$C,  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'),  " &
"  'GMT') AT time zone 'America/Sao_Paulo') AS DATE)  " &
"                         DT_PROMET,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS410.T$DTOC$C,  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'),  " &
"  'GMT') AT time zone 'America/Sao_Paulo') AS DATE)  " &
"                         DT_ETR,  " &
"  ZNFMD630.T$NCAR$C      CARGA,  " &
"  ZNSLS401.T$MGRT$C      CAPITAL_INTERIOR,  " &
"  SKU.DESCR              DESCRICAO  " &
"FROM       WMWHSE4.ORDERDETAIL SHD  " &
"INNER JOIN WMWHSE4.ORDERDETAILXVAS OXV  " &
"        ON OXV.ORDERKEY = SHD.ORDERKEY  " &
"AND OXV.ORDERLINENUMBER = SHD.ORDERLINENUMBER  " &
"INNER JOIN WMWHSE4.ORDERS SHO  " &
"        ON SHO.ORDERKEY = SHD.ORDERKEY  " &
"INNER JOIN WMWHSE4.SKU SKU  " &
"         ON SKU.SKU = SHD.SKU  " &
" LEFT JOIN BAANDB.TWHINH431201@dLN01 WHINH431  " &
" ON WHINH431.T$SHPM = SUBSTR(SHD.EXTERNORDERKEY,5,9)  " &
"AND TO_CHAR(WHINH431.T$PONO) = TO_CHAR(SHD.EXTERNLINENO)  " &
" LEFT JOIN BAANDB.TZNSLS004201@dLN01 ZNSLS004  " &
"        ON ZNSLS004.T$ORNO$C = WHINH431.T$WORN  " &
"       AND ZNSLS004.T$PONO$C = WHINH431.T$WPON  " &
" LEFT JOIN BAANDB.TZNSLS401201@dLN01 ZNSLS401  " &
"        ON ZNSLS401.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS401.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS401.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS401.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
"       AND ZNSLS401.T$ENTR$C = ZNSLS004.T$ENTR$C  " &
"       AND ZNSLS401.T$SEQU$C = ZNSLS004.T$SEQU$C  " &
" LEFT JOIN BAANDB.TZNSLS400201@dLN01 ZNSLS400  " &
"        ON ZNSLS400.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS400.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS400.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS400.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
" LEFT JOIN ( SELECT A.T$NCIA$C, A.T$UNEG$C, A.T$PECL$C,  " &
"                    A.T$SQPD$C, A.T$ENTR$C,  " &
"                    MIN(A.T$DTOC$C) T$DTOC$C,  " &
"                    MIN(A.T$CONO$C) T$CONO$C  " &
"               FROM BAANDB.TZNSLS410201@dLN01 A  " &
"              WHERE A.T$POCO$C = 'ETR'  " &
"           GROUP BY A.T$NCIA$C, A.T$UNEG$C, A.T$PECL$C,  " &
"                    A.T$SQPD$C, A.T$ENTR$C) ZNSLS410  " &
"        ON ZNSLS410.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS410.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS410.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS410.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
"       AND ZNSLS410.T$ENTR$C = ZNSLS004.T$ENTR$C  " &
" LEFT JOIN BAANDB.TZNFMD630201@dLN01 ZNFMD630  " &
"        ON ZNFMD630.T$ORNO$C = WHINH431.T$WORN  " &
" LEFT JOIN BAANDB.TZNFMD001201@dLN01 ZNFMD001  " &
"        ON ZNFMD001.T$FILI$C = ZNFMD630.T$FILI$C  " &
" LEFT JOIN BAANDB.TZNINT002201@dLN01 ZNINT002  " &
"        ON ZNINT002.T$NCIA$C = ZNSLS401.T$NCIA$C  " &
"       AND ZNINT002.T$UNEG$C = ZNSLS401.T$UNEG$C  " &
" LEFT JOIN BAANDB.TZNSLS002201@dLN01 ZNSLS002  " &
"        ON ZNSLS002.T$TPEN$C = ZNSLS401.T$ITPE$C  " &
" LEFT JOIN BAANDB.TTCMCS080201@dLN01 TCMCS080  " &
"        ON TCMCS080.T$CFRW = ZNFMD630.T$CFRW$C  " &
"INNER JOIN ENTERPRISE.CODELKUP CL  " &   
"        ON UPPER(CL.UDF1) = SHO.WHSEID  " &    
"       AND CL.LISTNAME = 'SCHEMA'  " &        
"WHERE ZNSLS410.T$DTOC$C IS NOT NULL  " &
"  AND OXV.NOTES1 IS NOT NULL  " &
"AND NVL(TCMCS080.t$cfrw, 'N/A') IN (" + Replace(("'" + JOIN(Parameters!Transportadora.Value, "',") + "'"),",",",'") + ")  " &
"  AND Trunc(CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS410.T$DTOC$C,  " &
"              'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')  " &
"                AT time zone 'America/Sao_Paulo') AS DATE))  " &
"      Between '" + Parameters!DataETRDe.Value + "'  " &
"          And '" + Parameters!DataETRAte.Value + "'  " &
"  " &
"UNION  " &
"  " &
"SELECT  " &
"  SHO.WHSEID             ID_PLANTA,  " &  
"  CL.UDF2                NOME_PLANTA,  " &  
"  ZNFMD630.T$FILI$C      ID_FILIAL,  " &
"  ZNFMD001.T$DSCA$C      DESCR_FILIAL,  " &
"  ZNSLS401.T$UNEG$C      ID_UNEG,  " &
"  ZNINT002.T$DESC$C      DESCR_UNEG,  " &
"  ZNSLS401.T$ENTR$C      ENTREGA,  " &
"  ZNSLS401.T$PECL$C      PEDIDO,  " &
"  SHO.INVOICENUMBER      NOTA,  " &
"  SHO.LANE               SERIE,  " &
"  OXV.NOTES1             ETIQUETA,  " &
"  ZNSLS401.T$NOME$C      CLIENTE,  " &
"  ZNSLS401.T$ICLE$C      CPF_CNPJ,  " &
"  ZNSLS401.T$LOGE$C      ENDERECO,  " &
"  ZNSLS401.T$NUME$C      NUMERO,  " &
"  ZNSLS401.T$BAIE$C      BAIRRO,  " &
"  ZNSLS401.T$REFE$C      REFERENCIA,  " &
"  ZNSLS401.T$EMAE$C      EMAIL,  " &
"  ZNSLS401.T$TELE$C      TELEFONE_1,  " &
"  ZNSLS401.T$TE1E$C      TELEFONE_2,  " &
"  ZNSLS401.T$TE2E$C      TELEFONE_3,  " &
"  ZNSLS410.T$CONO$C      CONTRATO,  " &
"  SHD.ORIGINALQTY        QTD_VOL,  " &
"  ZNSLS401.T$ITPE$C      ID_TIPO_ENFTREGA,  " &
"  ZNSLS002.T$DSCA$C      DESCR_TIPO_ENTREGA,  " &
"  SHD.PRODUCT_WEIGHT     PESO,  " &
"  SHD.PRODUCT_CUBE       VOLUME,  " &
"  ZNSLS401.T$VLUN$C*  " &
"  SHD.ORIGINALQTY        VL_SEM_FRETE,  " &
"  ZNFMD630.T$VLFC$C      FRETE,  " &
"  ZNSLS401.T$VLFR$C      FRETE_SITE,  " &
"  (ZNSLS401.T$VLUN$C*  " &
"  SHD.ORIGINALQTY)+  " &
"  ZNSLS401.T$VLFR$C+  " &
"  ZNSLS401.T$VLDE$C-  " &
"  ZNSLS401.T$VLDI$C      VL_TOTAL,  " &
"  TCMCS080.T$DSCA        TRANSPORTADORA,  " &
"  TCMCS080.T$SEAK        APELIDO,  " &
"  ZNSLS401.T$CEPE$C      CEP,  " &
"  ZNSLS401.T$CIDE$C      CIDADE,  " &
"  ZNSLS401.T$UFEN$C      UF,  " &
"  ZNSLS400.T$IDCA$C      CANAL,  " &
"  ZNFMD630.T$CFRW$C      ID_TRANSP,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS401.T$DTEP$C-  " &
"  ZNSLS401.T$PZCD$C,'DD-MON-YYYY HH24:MI:SS'),  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'GMT') AT time zone  " &
"     'America/Sao_Paulo') AS DATE)  DT_LIMITE,  " &
"  ZNSLS401.T$PZCD$C      PZ_CD,  " &
"  ZNSLS401.T$PZTR$C      PZ_TRANSIT,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS401.T$DTEP$C,  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'),  " &
"  'GMT') AT time zone 'America/Sao_Paulo') AS DATE)  " &
"                         DT_PROMET,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS410.T$DTOC$C,  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'),  " &
"  'GMT') AT time zone 'America/Sao_Paulo') AS DATE)  " &
"                         DT_ETR,  " &
"  ZNFMD630.T$NCAR$C      CARGA,  " &
"  ZNSLS401.T$MGRT$C      CAPITAL_INTERIOR,  " &
"  SKU.DESCR              DESCRICAO  " &
"FROM       WMWHSE5.ORDERDETAIL SHD  " &
"INNER JOIN WMWHSE5.ORDERDETAILXVAS OXV  " &
"        ON OXV.ORDERKEY = SHD.ORDERKEY  " &
"AND OXV.ORDERLINENUMBER = SHD.ORDERLINENUMBER  " &
"INNER JOIN WMWHSE5.ORDERS SHO  " &
"        ON SHO.ORDERKEY = SHD.ORDERKEY  " &
"INNER JOIN WMWHSE5.SKU SKU  " &
"         ON SKU.SKU = SHD.SKU  " &
" LEFT JOIN BAANDB.TWHINH431201@dLN01 WHINH431  " &
" ON WHINH431.T$SHPM = SUBSTR(SHD.EXTERNORDERKEY,5,9)  " &
"AND TO_CHAR(WHINH431.T$PONO) = TO_CHAR(SHD.EXTERNLINENO)  " &
" LEFT JOIN BAANDB.TZNSLS004201@dLN01 ZNSLS004  " &
"        ON ZNSLS004.T$ORNO$C = WHINH431.T$WORN  " &
"       AND ZNSLS004.T$PONO$C = WHINH431.T$WPON  " &
" LEFT JOIN BAANDB.TZNSLS401201@dLN01 ZNSLS401  " &
"        ON ZNSLS401.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS401.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS401.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS401.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
"       AND ZNSLS401.T$ENTR$C = ZNSLS004.T$ENTR$C  " &
"       AND ZNSLS401.T$SEQU$C = ZNSLS004.T$SEQU$C  " &
" LEFT JOIN BAANDB.TZNSLS400201@dLN01 ZNSLS400  " &
"        ON ZNSLS400.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS400.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS400.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS400.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
" LEFT JOIN ( SELECT A.T$NCIA$C, A.T$UNEG$C, A.T$PECL$C,  " &
"                    A.T$SQPD$C, A.T$ENTR$C,  " &
"                    MIN(A.T$DTOC$C) T$DTOC$C,  " &
"                    MIN(A.T$CONO$C) T$CONO$C  " &
"               FROM BAANDB.TZNSLS410201@dLN01 A  " &
"              WHERE A.T$POCO$C = 'ETR'  " &
"           GROUP BY A.T$NCIA$C, A.T$UNEG$C, A.T$PECL$C,  " &
"                    A.T$SQPD$C, A.T$ENTR$C) ZNSLS410  " &
"        ON ZNSLS410.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS410.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS410.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS410.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
"       AND ZNSLS410.T$ENTR$C = ZNSLS004.T$ENTR$C  " &
" LEFT JOIN BAANDB.TZNFMD630201@dLN01 ZNFMD630  " &
"        ON ZNFMD630.T$ORNO$C = WHINH431.T$WORN  " &
" LEFT JOIN BAANDB.TZNFMD001201@dLN01 ZNFMD001  " &
"        ON ZNFMD001.T$FILI$C = ZNFMD630.T$FILI$C  " &
" LEFT JOIN BAANDB.TZNINT002201@dLN01 ZNINT002  " &
"        ON ZNINT002.T$NCIA$C = ZNSLS401.T$NCIA$C  " &
"       AND ZNINT002.T$UNEG$C = ZNSLS401.T$UNEG$C  " &
" LEFT JOIN BAANDB.TZNSLS002201@dLN01 ZNSLS002  " &
"        ON ZNSLS002.T$TPEN$C = ZNSLS401.T$ITPE$C  " &
" LEFT JOIN BAANDB.TTCMCS080201@dLN01 TCMCS080  " &
"        ON TCMCS080.T$CFRW = ZNFMD630.T$CFRW$C  " &
"INNER JOIN ENTERPRISE.CODELKUP CL  " &   
"        ON UPPER(CL.UDF1) = SHO.WHSEID  " &    
"       AND CL.LISTNAME = 'SCHEMA'  " &        
"WHERE ZNSLS410.T$DTOC$C IS NOT NULL  " &
"  AND OXV.NOTES1 IS NOT NULL  " &
"AND NVL(TCMCS080.t$cfrw, 'N/A') IN (" + Replace(("'" + JOIN(Parameters!Transportadora.Value, "',") + "'"),",",",'") + ")  " &
"  AND Trunc(CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS410.T$DTOC$C,  " &
"              'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')  " &
"                AT time zone 'America/Sao_Paulo') AS DATE))  " &
"      Between '" + Parameters!DataETRDe.Value + "'  " &
"          And '" + Parameters!DataETRAte.Value + "'  " &
"  " &
"UNION  " &
"  " &
"SELECT  " &
"  SHO.WHSEID             ID_PLANTA,  " &  
"  CL.UDF2                NOME_PLANTA,  " &  
"  ZNFMD630.T$FILI$C      ID_FILIAL,  " &
"  ZNFMD001.T$DSCA$C      DESCR_FILIAL,  " &
"  ZNSLS401.T$UNEG$C      ID_UNEG,  " &
"  ZNINT002.T$DESC$C      DESCR_UNEG,  " &
"  ZNSLS401.T$ENTR$C      ENTREGA,  " &
"  ZNSLS401.T$PECL$C      PEDIDO,  " &
"  SHO.INVOICENUMBER      NOTA,  " &
"  SHO.LANE               SERIE,  " &
"  OXV.NOTES1             ETIQUETA,  " &
"  ZNSLS401.T$NOME$C      CLIENTE,  " &
"  ZNSLS401.T$ICLE$C      CPF_CNPJ,  " &
"  ZNSLS401.T$LOGE$C      ENDERECO,  " &
"  ZNSLS401.T$NUME$C      NUMERO,  " &
"  ZNSLS401.T$BAIE$C      BAIRRO,  " &
"  ZNSLS401.T$REFE$C      REFERENCIA,  " &
"  ZNSLS401.T$EMAE$C      EMAIL,  " &
"  ZNSLS401.T$TELE$C      TELEFONE_1,  " &
"  ZNSLS401.T$TE1E$C      TELEFONE_2,  " &
"  ZNSLS401.T$TE2E$C      TELEFONE_3,  " &
"  ZNSLS410.T$CONO$C      CONTRATO,  " &
"  SHD.ORIGINALQTY        QTD_VOL,  " &
"  ZNSLS401.T$ITPE$C      ID_TIPO_ENFTREGA,  " &
"  ZNSLS002.T$DSCA$C      DESCR_TIPO_ENTREGA,  " &
"  SHD.PRODUCT_WEIGHT     PESO,  " &
"  SHD.PRODUCT_CUBE       VOLUME,  " &
"  ZNSLS401.T$VLUN$C*  " &
"  SHD.ORIGINALQTY        VL_SEM_FRETE,  " &
"  ZNFMD630.T$VLFC$C      FRETE,  " &
"  ZNSLS401.T$VLFR$C      FRETE_SITE,  " &
"  (ZNSLS401.T$VLUN$C*  " &
"  SHD.ORIGINALQTY)+  " &
"  ZNSLS401.T$VLFR$C+  " &
"  ZNSLS401.T$VLDE$C-  " &
"  ZNSLS401.T$VLDI$C      VL_TOTAL,  " &
"  TCMCS080.T$DSCA        TRANSPORTADORA,  " &
"  TCMCS080.T$SEAK        APELIDO,  " &
"  ZNSLS401.T$CEPE$C      CEP,  " &
"  ZNSLS401.T$CIDE$C      CIDADE,  " &
"  ZNSLS401.T$UFEN$C      UF,  " &
"  ZNSLS400.T$IDCA$C      CANAL,  " &
"  ZNFMD630.T$CFRW$C      ID_TRANSP,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS401.T$DTEP$C-  " &
"  ZNSLS401.T$PZCD$C,'DD-MON-YYYY HH24:MI:SS'),  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'GMT') AT time zone  " &
"     'America/Sao_Paulo') AS DATE)  DT_LIMITE,  " &
"  ZNSLS401.T$PZCD$C      PZ_CD,  " &
"  ZNSLS401.T$PZTR$C      PZ_TRANSIT,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS401.T$DTEP$C,  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'),  " &
"  'GMT') AT time zone 'America/Sao_Paulo') AS DATE)  " &
"                         DT_PROMET,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS410.T$DTOC$C,  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'),  " &
"  'GMT') AT time zone 'America/Sao_Paulo') AS DATE)  " &
"                         DT_ETR,  " &
"  ZNFMD630.T$NCAR$C      CARGA,  " &
"  ZNSLS401.T$MGRT$C      CAPITAL_INTERIOR,  " &
"  SKU.DESCR              DESCRICAO  " &
"FROM       WMWHSE6.ORDERDETAIL SHD  " &
"INNER JOIN WMWHSE6.ORDERDETAILXVAS OXV  " &
"        ON OXV.ORDERKEY = SHD.ORDERKEY  " &
"AND OXV.ORDERLINENUMBER = SHD.ORDERLINENUMBER  " &
"INNER JOIN WMWHSE6.ORDERS SHO  " &
"        ON SHO.ORDERKEY = SHD.ORDERKEY  " &
"INNER JOIN WMWHSE6.SKU SKU  " &
"         ON SKU.SKU = SHD.SKU  " &
" LEFT JOIN BAANDB.TWHINH431201@dLN01 WHINH431  " &
" ON WHINH431.T$SHPM = SUBSTR(SHD.EXTERNORDERKEY,5,9)  " &
"AND TO_CHAR(WHINH431.T$PONO) = TO_CHAR(SHD.EXTERNLINENO)  " &
" LEFT JOIN BAANDB.TZNSLS004201@dLN01 ZNSLS004  " &
"        ON ZNSLS004.T$ORNO$C = WHINH431.T$WORN  " &
"       AND ZNSLS004.T$PONO$C = WHINH431.T$WPON  " &
" LEFT JOIN BAANDB.TZNSLS401201@dLN01 ZNSLS401  " &
"        ON ZNSLS401.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS401.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS401.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS401.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
"       AND ZNSLS401.T$ENTR$C = ZNSLS004.T$ENTR$C  " &
"       AND ZNSLS401.T$SEQU$C = ZNSLS004.T$SEQU$C  " &
" LEFT JOIN BAANDB.TZNSLS400201@dLN01 ZNSLS400  " &
"        ON ZNSLS400.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS400.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS400.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS400.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
" LEFT JOIN ( SELECT A.T$NCIA$C, A.T$UNEG$C, A.T$PECL$C,  " &
"                    A.T$SQPD$C, A.T$ENTR$C,  " &
"                    MIN(A.T$DTOC$C) T$DTOC$C,  " &
"                    MIN(A.T$CONO$C) T$CONO$C  " &
"               FROM BAANDB.TZNSLS410201@dLN01 A  " &
"              WHERE A.T$POCO$C = 'ETR'  " &
"           GROUP BY A.T$NCIA$C, A.T$UNEG$C, A.T$PECL$C,  " &
"                    A.T$SQPD$C, A.T$ENTR$C) ZNSLS410  " &
"        ON ZNSLS410.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS410.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS410.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS410.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
"       AND ZNSLS410.T$ENTR$C = ZNSLS004.T$ENTR$C  " &
" LEFT JOIN BAANDB.TZNFMD630201@dLN01 ZNFMD630  " &
"        ON ZNFMD630.T$ORNO$C = WHINH431.T$WORN  " &
" LEFT JOIN BAANDB.TZNFMD001201@dLN01 ZNFMD001  " &
"        ON ZNFMD001.T$FILI$C = ZNFMD630.T$FILI$C  " &
" LEFT JOIN BAANDB.TZNINT002201@dLN01 ZNINT002  " &
"        ON ZNINT002.T$NCIA$C = ZNSLS401.T$NCIA$C  " &
"       AND ZNINT002.T$UNEG$C = ZNSLS401.T$UNEG$C  " &
" LEFT JOIN BAANDB.TZNSLS002201@dLN01 ZNSLS002  " &
"        ON ZNSLS002.T$TPEN$C = ZNSLS401.T$ITPE$C  " &
" LEFT JOIN BAANDB.TTCMCS080201@dLN01 TCMCS080  " &
"        ON TCMCS080.T$CFRW = ZNFMD630.T$CFRW$C  " &
"INNER JOIN ENTERPRISE.CODELKUP CL  " &   
"        ON UPPER(CL.UDF1) = SHO.WHSEID  " &    
"       AND CL.LISTNAME = 'SCHEMA'  " &        
"WHERE ZNSLS410.T$DTOC$C IS NOT NULL  " &
"  AND OXV.NOTES1 IS NOT NULL  " &
"AND NVL(TCMCS080.t$cfrw, 'N/A') IN (" + Replace(("'" + JOIN(Parameters!Transportadora.Value, "',") + "'"),",",",'") + ")  " &
"  AND Trunc(CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS410.T$DTOC$C,  " &
"              'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')  " &
"                AT time zone 'America/Sao_Paulo') AS DATE))  " &
"      Between '" + Parameters!DataETRDe.Value + "'  " &
"          And '" + Parameters!DataETRAte.Value + "'  " &
"  " &
"UNION  " &
"  " &
"SELECT  " &
"  SHO.WHSEID             ID_PLANTA,  " &  
"  CL.UDF2                NOME_PLANTA,  " &  
"  ZNFMD630.T$FILI$C      ID_FILIAL,  " &
"  ZNFMD001.T$DSCA$C      DESCR_FILIAL,  " &
"  ZNSLS401.T$UNEG$C      ID_UNEG,  " &
"  ZNINT002.T$DESC$C      DESCR_UNEG,  " &
"  ZNSLS401.T$ENTR$C      ENTREGA,  " &
"  ZNSLS401.T$PECL$C      PEDIDO,  " &
"  SHO.INVOICENUMBER      NOTA,  " &
"  SHO.LANE               SERIE,  " &
"  OXV.NOTES1             ETIQUETA,  " &
"  ZNSLS401.T$NOME$C      CLIENTE,  " &
"  ZNSLS401.T$ICLE$C      CPF_CNPJ,  " &
"  ZNSLS401.T$LOGE$C      ENDERECO,  " &
"  ZNSLS401.T$NUME$C      NUMERO,  " &
"  ZNSLS401.T$BAIE$C      BAIRRO,  " &
"  ZNSLS401.T$REFE$C      REFERENCIA,  " &
"  ZNSLS401.T$EMAE$C      EMAIL,  " &
"  ZNSLS401.T$TELE$C      TELEFONE_1,  " &
"  ZNSLS401.T$TE1E$C      TELEFONE_2,  " &
"  ZNSLS401.T$TE2E$C      TELEFONE_3,  " &
"  ZNSLS410.T$CONO$C      CONTRATO,  " &
"  SHD.ORIGINALQTY        QTD_VOL,  " &
"  ZNSLS401.T$ITPE$C      ID_TIPO_ENFTREGA,  " &
"  ZNSLS002.T$DSCA$C      DESCR_TIPO_ENTREGA,  " &
"  SHD.PRODUCT_WEIGHT     PESO,  " &
"  SHD.PRODUCT_CUBE       VOLUME,  " &
"  ZNSLS401.T$VLUN$C*  " &
"  SHD.ORIGINALQTY        VL_SEM_FRETE,  " &
"  ZNFMD630.T$VLFC$C      FRETE,  " &
"  ZNSLS401.T$VLFR$C      FRETE_SITE,  " &
"  (ZNSLS401.T$VLUN$C*  " &
"  SHD.ORIGINALQTY)+  " &
"  ZNSLS401.T$VLFR$C+  " &
"  ZNSLS401.T$VLDE$C-  " &
"  ZNSLS401.T$VLDI$C      VL_TOTAL,  " &
"  TCMCS080.T$DSCA        TRANSPORTADORA,  " &
"  TCMCS080.T$SEAK        APELIDO,  " &
"  ZNSLS401.T$CEPE$C      CEP,  " &
"  ZNSLS401.T$CIDE$C      CIDADE,  " &
"  ZNSLS401.T$UFEN$C      UF,  " &
"  ZNSLS400.T$IDCA$C      CANAL,  " &
"  ZNFMD630.T$CFRW$C      ID_TRANSP,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS401.T$DTEP$C-  " &
"  ZNSLS401.T$PZCD$C,'DD-MON-YYYY HH24:MI:SS'),  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'GMT') AT time zone  " &
"     'America/Sao_Paulo') AS DATE)  DT_LIMITE,  " &
"  ZNSLS401.T$PZCD$C      PZ_CD,  " &
"  ZNSLS401.T$PZTR$C      PZ_TRANSIT,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS401.T$DTEP$C,  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'),  " &
"  'GMT') AT time zone 'America/Sao_Paulo') AS DATE)  " &
"                         DT_PROMET,  " &
"  CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS410.T$DTOC$C,  " &
"  'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'),  " &
"  'GMT') AT time zone 'America/Sao_Paulo') AS DATE)  " &
"                         DT_ETR,  " &
"  ZNFMD630.T$NCAR$C      CARGA,  " &
"  ZNSLS401.T$MGRT$C      CAPITAL_INTERIOR,  " &
"  SKU.DESCR              DESCRICAO  " &
"FROM       WMWHSE7.ORDERDETAIL SHD  " &
"INNER JOIN WMWHSE7.ORDERDETAILXVAS OXV  " &
"        ON OXV.ORDERKEY = SHD.ORDERKEY  " &
"AND OXV.ORDERLINENUMBER = SHD.ORDERLINENUMBER  " &
"INNER JOIN WMWHSE7.ORDERS SHO  " &
"        ON SHO.ORDERKEY = SHD.ORDERKEY  " &
"INNER JOIN WMWHSE7.SKU SKU  " &
"         ON SKU.SKU = SHD.SKU  " &
" LEFT JOIN BAANDB.TWHINH431201@dLN01 WHINH431  " &
" ON WHINH431.T$SHPM = SUBSTR(SHD.EXTERNORDERKEY,5,9)  " &
"AND TO_CHAR(WHINH431.T$PONO) = TO_CHAR(SHD.EXTERNLINENO)  " &
" LEFT JOIN BAANDB.TZNSLS004201@dLN01 ZNSLS004  " &
"        ON ZNSLS004.T$ORNO$C = WHINH431.T$WORN  " &
"       AND ZNSLS004.T$PONO$C = WHINH431.T$WPON  " &
" LEFT JOIN BAANDB.TZNSLS401201@dLN01 ZNSLS401  " &
"        ON ZNSLS401.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS401.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS401.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS401.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
"       AND ZNSLS401.T$ENTR$C = ZNSLS004.T$ENTR$C  " &
"       AND ZNSLS401.T$SEQU$C = ZNSLS004.T$SEQU$C  " &
" LEFT JOIN BAANDB.TZNSLS400201@dLN01 ZNSLS400  " &
"        ON ZNSLS400.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS400.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS400.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS400.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
" LEFT JOIN ( SELECT A.T$NCIA$C, A.T$UNEG$C, A.T$PECL$C,  " &
"                    A.T$SQPD$C, A.T$ENTR$C,  " &
"                    MIN(A.T$DTOC$C) T$DTOC$C,  " &
"                    MIN(A.T$CONO$C) T$CONO$C  " &
"               FROM BAANDB.TZNSLS410201@dLN01 A  " &
"              WHERE A.T$POCO$C = 'ETR'  " &
"           GROUP BY A.T$NCIA$C, A.T$UNEG$C, A.T$PECL$C,  " &
"                    A.T$SQPD$C, A.T$ENTR$C) ZNSLS410  " &
"        ON ZNSLS410.T$NCIA$C = ZNSLS004.T$NCIA$C  " &
"       AND ZNSLS410.T$UNEG$C = ZNSLS004.T$UNEG$C  " &
"       AND ZNSLS410.T$PECL$C = ZNSLS004.T$PECL$C  " &
"       AND ZNSLS410.T$SQPD$C = ZNSLS004.T$SQPD$C  " &
"       AND ZNSLS410.T$ENTR$C = ZNSLS004.T$ENTR$C  " &
" LEFT JOIN BAANDB.TZNFMD630201@dLN01 ZNFMD630  " &
"        ON ZNFMD630.T$ORNO$C = WHINH431.T$WORN  " &
" LEFT JOIN BAANDB.TZNFMD001201@dLN01 ZNFMD001  " &
"        ON ZNFMD001.T$FILI$C = ZNFMD630.T$FILI$C  " &
" LEFT JOIN BAANDB.TZNINT002201@dLN01 ZNINT002  " &
"        ON ZNINT002.T$NCIA$C = ZNSLS401.T$NCIA$C  " &
"       AND ZNINT002.T$UNEG$C = ZNSLS401.T$UNEG$C  " &
" LEFT JOIN BAANDB.TZNSLS002201@dLN01 ZNSLS002  " &
"        ON ZNSLS002.T$TPEN$C = ZNSLS401.T$ITPE$C  " &
" LEFT JOIN BAANDB.TTCMCS080201@dLN01 TCMCS080  " &
"        ON TCMCS080.T$CFRW = ZNFMD630.T$CFRW$C  " &
"INNER JOIN ENTERPRISE.CODELKUP CL  " &   
"        ON UPPER(CL.UDF1) = SHO.WHSEID  " &    
"       AND CL.LISTNAME = 'SCHEMA'  " &        
"WHERE ZNSLS410.T$DTOC$C IS NOT NULL  " &
"  AND OXV.NOTES1 IS NOT NULL  " &
"AND NVL(TCMCS080.t$cfrw, 'N/A') IN (" + Replace(("'" + JOIN(Parameters!Transportadora.Value, "',") + "'"),",",",'") + ")  " &
"  AND Trunc(CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(ZNSLS410.T$DTOC$C,  " &
"              'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')  " &
"                AT time zone 'America/Sao_Paulo') AS DATE))  " &
"      Between '" + Parameters!DataETRDe.Value + "'  " &
"          And '" + Parameters!DataETRAte.Value + "'  " &
"ORDER BY DT_ETR, DESCR_UNEG  "
)