SELECT

		QWMS.ASN,		--	NR
		QWMS.ID_FILIAL,
		QWMS.DESCR_FILIAL,
		QWMS.OPERACAO,
		QWMS.DT_NR,
		CASE 	WHEN TDREC940.T$STAT$L = 1 THEN 'ABERTO'
				WHEN TDREC940.T$STAT$L = 3 THEN 'NÃO APROVADO'
				WHEN TDREC940.T$STAT$L = 4 THEN 'APROVADO'
				WHEN TDREC940.T$STAT$L = 5 THEN 'APROVADO COM PROBLEMA'
				WHEN TDREC940.T$STAT$L = 1 THEN 'ESTORNADO'
				WHEN TDREC940.T$STAT$L = 200 THEN 'AGURARDANDO WMS'
				WHEN TDREC940.T$STAT$L = 201 THEN 'PRONTO PARA ENVIAR WMS'
			ELSE 'NÃO APLICAVEL' END				SITUACAO_NOTA,
		QWMS.NF,

		CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(TDREC940.T$DATE$L, 
		  'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
			AT time zone sessiontimezone) AS DATE)	DATA_EMISSAO,
		TDREC940.T$FOVN$L							CNPJ_FORNCEDOR,
		TDREC940.T$OPFC$L							CFOP,
		TDREC940.T$OPOR$L							SEQ_CFOP,
		DEPART.ID_DEPART              ID_DEPARTAMENTO,
		DEPART.DEPART_NAME            DESCR_DEPARTAMENTO,
		TDREC941.T$ITEM								ID_ITEM,
		TCIBD001.T$DSCA							  DESCR_ITEM,
		TCIBD936.T$FRAT$L							NBM,
		TCIBD936.T$IFGC$L							SEQ_NBM,
		TDREC941.T$PRIC$L							CUSTO,
		TDREC941.T$QNTY$L							QTDE,
		TDREC941.T$GAMT$L							VALOR_MERCARIA,

		TDREC941.ICMS ICMSST_PROPRIO,
    
		TDREC941.ICMSST_ST_COM_CONV,
		TDREC941.ICMSST_ST_SEM_CONV
		


FROM
	BAANDB.TTDREC940301@PLN01 TDREC940
	
	
	INNER JOIN (SELECT 	L.T$FIRE$L,
						L.T$ITEM$L T$ITEM,
						SUM(L.T$PRIC$L) T$PRIC$L,
						SUM(L.T$QNTY$L) T$QNTY$L,
						SUM(L.T$GAMT$L) T$GAMT$L,
						SUM(NVL(ICMS.T$AMNT$L,0)) ICMS,
						SUM(CASE WHEN T$ISCO$C=1 THEN NVL(ICST.T$AMNT$L,0) ELSE 0 END) ICMSST_ST_COM_CONV,
						SUM(CASE WHEN T$ISCO$C!=1 THEN NVL(ICST.T$AMNT$L,0) ELSE 0 END) ICMSST_ST_SEM_CONV
				FROM	BAANDB.TTDREC941301@PLN01 L
				LEFT JOIN baandb.ttdrec942301@pln01 ICMS ON  ICMS.T$FIRE$L = L.T$FIRE$L
														 AND ICMS.T$LINE$L = L.T$LINE$L
														 AND ICMS.T$BRTY$L = 1
				LEFT JOIN baandb.ttdrec942301@pln01	ICST ON  ICST.T$FIRE$L = L.T$FIRE$L
				                                         AND ICST.T$LINE$L = L.T$LINE$L
	                                                     AND ICST.T$BRTY$L = 2
				LEFT JOIN baandb.ttdrec949301@pln01 ICCP ON  ICCP.T$FIRE$L = ICST.T$FIRE$L											
														 AND ICCP.T$BRTY$L = ICST.T$BRTY$L
				GROUP BY
						L.T$FIRE$L,
				        L.T$ITEM$L)	TDREC941	ON	TDREC941.T$FIRE$L	=	TDREC940.T$FIRE$L

	LEFT JOIN (SELECT DISTINCT b.ID_DEPART, b.DEPART_NAME, a.sku
            from  WMWHSE5.sku a
            inner join ENTERPRISE.DEPARTSECTORSKU b on to_char(b.ID_DEPART) = to_char(a.SKUGROUP)) DEPART                                           
														ON DEPART.sku = 	TRIM(TDREC941.T$ITEM)						
						
	INNER JOIN
		(SELECT 
			RC.RECEIPTKEY								ASN,		--	NR
			RC.WHSEID									ID_FILIAL,
			CL.UDF2										DESCR_FILIAL,
			TPNT.DESCRIPTION							OPERACAO,
			RD.SUSR1									NF,		
			--SK.SKUGROUP									ID_DEPARTAMENTO,
			--DEPART.DEPART_NAME							DESCR_DEPARTAMENTO,	
			RC.SUPPLIERCODE,	
			CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(RC.ADDDATE, 
			  'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
				AT time zone sessiontimezone) AS DATE) 	DT_NR		
			--RD.SKU										ID_ITEM,
			--SK.DESCR									DESCR_ITEM,
		 FROM			WMWHSE5.RECEIPT		RC
		 INNER JOIN	WMWHSE5.RECEIPTDETAIL	RD				ON	RD.RECEIPTKEY 			= 	RC.RECEIPTKEY
		 --INNER JOIN	WMWHSE5.SKU				SK				ON	SK.SKU					=	RD.SKU
		 INNER JOIN	ENTERPRISE.CODELKUP		CL				ON	UPPER(CL.UDF1)			=	RC.WHSEID

		 LEFT JOIN ( select clkp.code         COD, 
							trans.description
					   from WMWHSE5.codelkup clkp
					inner join WMWHSE5.translationlist trans 
						 on trans.code = clkp.code
						and trans.joinkey1 = clkp.listname
					  where clkp.listname = 'RECEIPTYPE'
						and trans.locale = 'pt'
						and trans.tblname = 'CODELKUP' 
						and Trim(clkp.code) is not null ) tpnt
															ON TO_CHAR(tpnt.COD) 		= 	TO_CHAR(rc.TYPE)
     WHERE RD.SUSR1 IS NOT NULL
		 GROUP BY
			RC.RECEIPTKEY,		
			RC.WHSEID,			
			CL.UDF2,		
			TPNT.DESCRIPTION,	
			RD.SUSR1,			
			RC.SUPPLIERCODE,
			CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(RC.ADDDATE, 
			  'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT')
				AT time zone sessiontimezone) AS DATE)
		 ) QWMS 				ON	QWMS.NF 				=	TDREC940.T$DOCN$L || '/' || TDREC940.T$SERI$L
														AND	QWMS.SUPPLIERCODE		=	TDREC940.T$BPID$L

	
	
	
	
	
	INNER JOIN	BAANDB.TTCIBD001301@PLN01 TCIBD001 		ON	TCIBD001.T$ITEM 		= 	TDREC941.T$ITEM
	INNER JOIN	BAANDB.TTCIBD936301@PLN01 TCIBD936 		ON 	TCIBD936.T$IFGC$L 		= 	TCIBD001.T$IFGC$L


WHERE TDREC940.T$RFDT$L IN (1,2,5,10,28)														
