SELECT
		TD.WHSEID							ID_PLANTA,
		CL.UDF2								DESCR_PLANTA,
		TD.ORDERKEY							ORDEM_MOV,
		TD.WAVEKEY							ONDA,
		OC.REFERENCEDOCUMENT				ORDEM_LN,
		(select a.t$pecl$c
		 from baandb.tznsls004301@pln01 a
		 where a.t$orno$c = OC.REFERENCEDOCUMENT
		 and rownum=1)						PEDIDO_SITE,
		TD.STARTTIME						INICIO_MOV,
		TD.SKU								ID_ITEM,
		SK.DESCR							DESCR_ITEM,
		TD.QTY								QUANTID,
		TD.FROMLOC							LOC_ORG,
		PO.DESCR							LOCAL_ORIG,
		LO.PUTAWAYZONE						ZONA_ORIG,
		TD.TOLOC							LOC_DEST,
		PD.DESCR							LOCAL_DEST,
		LD.PUTAWAYZONE						ZONA_DEST,
		OC.STATUS							ID_SITUACAO,
		SS.DESCRIPTION						DESCR_SITUACAO,
		OC.EDITDATE							DT_HR,
		TD.EDITWHO							ID_OPERADOR,
		subStr( tu.usr_name,4,
            inStr(tu.usr_name, ',')-4 )   	NOME_OP		
FROM
		WMWHSE5.TASKDETAIL						TD
		INNER JOIN 	ENTERPRISE.CODELKUP			CL	ON	UPPER(CL.UDF1)	=	TD.WHSEID
													AND	CL.LISTNAME 	=	'SCHEMA'
		INNER JOIN	WMWHSE5.ORDERS				OC	ON	OC.ORDERKEY		=	TD.ORDERKEY
		INNER JOIN	WMWHSE5.SKU					SK	ON	SK.SKU			=	TD.SKU
		INNER JOIN	WMWHSE5.LOC					LO	ON	LO.LOC			=	TD.FROMLOC
		INNER JOIN	WMWHSE5.PUTAWAYZONE 		PO	ON	PO.PUTAWAYZONE	=	LO.PUTAWAYZONE
		INNER JOIN	WMWHSE5.LOC					LD	ON	LD.LOC			=	TD.TOLOC
		INNER JOIN	WMWHSE5.PUTAWAYZONE 		PD	ON	PD.PUTAWAYZONE	=	LD.PUTAWAYZONE
		INNER JOIN	WMWHSE5.ORDERSTATUSSETUP	SS	ON	SS.CODE			=	OC.STATUS
		LEFT JOIN 	WMWHSE5.taskmanageruser 	tu 	ON 	tu.userkey 		= 	TD.EDITWHO
WHERE
				TD.TASKTYPE = 'PK'
		AND		TD.STATUS = 9