SELECT
		LNT.T$PECL$C			PEDIDO,
		LNT.T$ORNO$C			ORDEM_LN,
		ORC.ORDERKEY			ORDEM_WMS,
		LNP.t$DESC$C			NOME_EVENTO,
		ORD.SKU					ITEM,
		SKU.DESCR				DESCR_ITEM
FROM
		ORDERS								ORC
	INNER JOIN 	ORDERDETAIL					ORD	ON	ORD.ORDERKEY	=	ORC.ORDERKEY
	INNER JOIN 	SKU							SKU	ON	SKU.SKU			=	ORD.SKU
	LEFT JOIN  	(SELECT A1.T$PECL$C, A1.T$ORNO$C, B1.T$POCO$C  FROM
				(SELECT A.T$PECL$C, A.T$ORNO$C 
				 FROM BAANDB.TZNSLS004301@PLN01 A
				 GROUP BY A.T$PECL$C, A.T$ORNO$C) A1,
				(SELECT B.T$PECL$C,
					   B.T$POCO$C,
					   ROW_NUMBER() OVER (PARTITION BY B.T$PECL$C ORDER BY B.T$DTOC$C DESC, B.T$SEQN$C DESC) RN
										   FROM BAANDB.TZNSLS410301@PLN01 B) B1
				WHERE B1.T$PECL$C = A1.T$PECL$C 
				AND B1.RN=1) LNT

						   ON	LNT.T$ORNO$C	=	ORC.REFERENCEDOCUMENT
	LEFT JOIN 	BAANDB.TZNMCS002301@PLN01	LNP	ON	LNP.T$POCO$C	=	LNT.T$POCO$C
WHERE
		ORC.STATUS IN ('98','99')
--	AND ORC.EDITDATE IN -- FILTRO DE DATA