SELECT 
	Q1.ID_PLANTA,
	CL.UDF2	DESCR_PLANTA,
	Q1.INVENTARIO,
	Q1.LOCAIS,
	Q1.CONFERIDOS,
	Q1.RESOLVIDOS,
    Q1.ID_SITUACAO,
	CS.DESCRIPTION DESCR_SITUACAO,
    Q1.DT_SITUACAO
FROM

	(SELECT IV.WHSEID 										ID_PLANTA,
			IV.CCKEY 										INVENTARIO,
			COUNT(DISTINCT IV.LOC) 							LOCAIS,
			SUM(CASE WHEN IV.STATUS!=0 THEN 1 ELSE 0 END) 	CONFERIDOS,
			SUM(CASE WHEN IV.STATUS=9 THEN 1 ELSE 0 END) 	RESOLVIDOS,
			MIN(IV.STATUS) 									ID_SITUACAO,
			MAX(IV.EDITDATE) 								DT_SITUACAO
			FROM
			( SELECT
				CD.WHSEID,
				TO_CHAR(CD.CCKEY) CCKEY,
				CD.LOC,
				CD.STATUS,
				CD.EDITDATE
			  FROM WMWHSE4.CC CC
			  INNER JOIN WMWHSE4.CCDETAIL CD ON CD.CCKEY = CC.CCKEY
			  WHERE CC.STATUS!=9
			  UNION 
			  SELECT
				PH.WHSEID,
				' ' CCKEY,    -- PENDENTE DE CUSTOMIZAÇÃO
				PH.LOC,
				PH.STATUS,
				PH.EDITDATE
			  FROM WMWHSE4.PHYSICAL PH) IV
	 GROUP BY IV.WHSEID, IV.CCKEY) Q1
INNER JOIN	ENTERPRISE.CODELKUP	CL	ON	UPPER(CL.UDF1)	=	Q1.ID_PLANTA
									AND	CL.LISTNAME		=	'SCHEMA'
INNER JOIN	WMWHSE4.CODELKUP	CS	ON	CS.CODE			=	Q1.ID_SITUACAO
									AND CS.LISTNAME		=	'CCSTATUS'