SELECT
		LOC.PUTAWAYZONE 							ID_ZONA,
		PZ.DESCR									DESCR_ZONA,
		LOC.LOC                           			ID_LOCAL,
		LOC.LOGICALLOCATION							LOC_DESCR,
		SKU.DESCR									DESCR_ITEM,
		sum(LLID.QTY)								ESTO_QTY,
		LLID.EDITWHO								ID_OPERADOR,
		LLID.EDITDATE 								DT_MOV,
		CASE WHEN IH.STATUS IS NULL			
			THEN 'OK'			
			ELSE TO_CHAR(IH.STATUS) END				ID_RESTR,
		CL.UDF2										PLANTA

FROM
		WMWHSE5.LOTXLOCXID LLID
		INNER JOIN WMWHSE5.SKU SKU					ON	SKU.SKU = LLID.SKU
		INNER JOIN WMWHSE5.LOC LOC					ON	LOC.LOC = LLID.LOC
		LEFT JOIN (SELECT LOC, STATUS FROM WMWHSE5.INVENTORYHOLD where hold = 1 and loc <> ' ') IH
													ON 	IH.LOC=LLID.LOC
		LEFT JOIN WMWHSE5.PUTAWAYZONE PZ 			ON	PZ.PUTAWAYZONE = LOC.PUTAWAYZONE 
		LEFT JOIN ENTERPRISE.CODELKUP CL 			ON	UPPER(CL.UDF1) = LLID.WHSEID	
WHERE LLID.QTY>0
GROUP BY 
		LOC.PUTAWAYZONE, 			
		PZ.DESCR,	
		LOC.LOC,
		LOC.LOGICALLOCATION,			
		SKU.DESCR,									
		LLID.EDITWHO,				
		LLID.EDITDATE, 				
		CASE WHEN IH.STATUS IS NULL	
			THEN 'OK'			
			ELSE TO_CHAR(IH.STATUS) END,		
		CL.UDF2	