SELECT GCD.REQUESTNUMBER AS REQUISICAO,GCD.LOCATION AS LOCAL, GCD.NOOFCOUNTS AS CONT_SOLICITADA, 
	GCD.NOOFCOUNTED  AS CONT_REALIZADA, 'PENDENTE CONTAGEM SUPERVISOR' AS STATUS,
	CASE TO_CHAR(GRI.SIMULATION) 
	  WHEN '0' THEN 'NÃO'
	  WHEN '1' THEN 'SIM'
	  END
	  AS SIMULACAO
	FROM  WMWHSE5.GLOBALINVCOUNTDETAIL GCD, WMWHSE6.GLOBALINVREQUEST GRI
	WHERE GCD.STATUS = '07'
	AND GCD.NOOFCOUNTS = GCD.NOOFCOUNTED
	AND GCD.REQUESTNUMBER = GRI.REQUESTNUMBER
	AND CASE TO_CHAR(GRI.SIMULATION) 
	  WHEN '0' THEN 'NÃO'
	  WHEN '1' THEN 'SIM'
	  END IN (:Simulacao)