SELECT
		TD.WHSEID							ID_PLANTA,
		CL.UDF2                           	DESCR_PLANTA,
		TD.SKU								ID_ITEM,
		SK.DESCR							DESCR_ITEM,
		SK.SUSR5							ID_SKU,				-- SKU FORNECEDOR
		ST.COMPANY							FORNECEDOR,
		TD.FROMLOC							ID_LOCAL_ROM,
		LC.PUTAWAYZONE						CLASSE_LOCAL,
		PZ.DESCR							DESC_LOCAL,
		TD.TOLOC							ID_CLA_LOC,
		TD.ENDTIME							DT_SITUACAO
FROM
				WMWHSE5.TASKDETAIL 	TD
	INNER JOIN	ENTERPRISE.CODELKUP	CL	ON	UPPER(CL.UDF1)	=	TD.WHSEID
	INNER JOIN 	WMWHSE5.SKU			SK	ON	SK.SKU			=	TD.SKU
	LEFT JOIN	WMWHSE5.STORER		ST	ON 	ST.STORERKEY 	= 	SK.SUSR5
	                                    AND ST.WHSEID 		= 	SK.WHSEID 
	                                    AND ST.TYPE 		= 	5
	LEFT JOIN	WMWHSE5.LOC			LC	ON	LC.LOC			=	TD.FROMLOC
	LEFT JOIN	WMWHSE5.PUTAWAYZONE PZ	ON	PZ.PUTAWAYZONE 	=	LC.PUTAWAYZONE
WHERE	TD.TASKTYPE='PK'
AND		TD.STATUS='9'
