	SELECT DISTINCT GRD.REQUESTNUMBER, 
		GRD.LOCATION 							AS LOCAL,
		PTY.PUTAWAYZONE 						AS ZONA,
		TO_CHAR(GRD.SKU) 						AS ITEM, 
		TO_CHAR(SKU.DESCR) 						AS DESCRICAO, 
		TO_NUMBER(GRD.COUNTQTY) 				AS QTY_CONTADA, 
		TO_NUMBER(GRD.SYSTEMQTY) 				AS QTY_SISTEMA,
		
		abs(nvl(GRD.SYSTEMQTY, 0) - 
				nvl(GRD.COUNTQTY, 0))			AS VAR_QTDE,
		nvl(GRD.SYSTEMQTY, 0) * 
				nvl(maucLN.mauc, 0) 				AS VL_LOGICO,
		(nvl(GRD.COUNTQTY, 0) ) *
				nvl(maucLN.mauc, 0)				AS VL_FISICO,
		nvl(abs(nvl(GRD.SYSTEMQTY, 0) - nvl(GRD.COUNTQTY, 0)) * 
				maucLN.mauc , 0)				AS VL_DIVERGENCIA,
				
		TO_NUMBER(GRD.COUNTQTY-GRD.SYSTEMQTY) 	AS DIFERENCA,
		   CASE TO_CHAR (GRD.STATUS) 
			  WHEN '01' THEN 'NAO_CONTADO'
			  WHEN '02' THEN 'CONTADO'
			  WHEN '03' THEN 'LOCAL_VAZIO'
			  WHEN '04' THEN 'POSTADO'
			  WHEN '05' THEN 'CONTAGEM_SUPERVISOR'
			  WHEN '06' THEN 'RECONTAGEM'
			  WHEN '07' THEN 'EM CONTAGEM'
			  WHEN '08' THEN 'ITEM ENCONTRADO'
		   END 									AS STATUS_CONTAGEM,
		GRD.EDITWHO 							AS USUARIO_CONTAGEM, 
		TO_CHAR(GRD.EDITDATE ,'DD/MM/YYYY') 		AS DATAFECHALOCAL, 
		TO_CHAR(GRD.EDITDATE ,'HH24:MM:SS') 		AS HORAFECHAMENTOLOCAL,
		
		TO_CHAR(BOM.SKU) 						AS SKU_TIK, 
		CASE to_char(bom.primarycomponent)
		WHEN '0' THEN 'N'
			WHEN '1' THEN 'S'
			END 									AS PRIMARIO

	FROM  WMWHSE5.GLOBALINVREQUESTDETAIL GRD
		INNER JOIN  WMWHSE5.SKU SKU
			ON	SKU.SKU = GRD.SKU
		INNER JOIN  WMWHSE5.LOC LOC
			ON	LOC.LOC = GRD.LOCATION
		INNER JOIN  WMWHSE5.PUTAWAYZONE PTY
			ON	PTY.PUTAWAYZONE = LOC.PUTAWAYZONE
		LEFT JOIN  WMWHSE5.BILLOFMATERIAL BOM
			ON BOM.COMPONENTSKU = GRD.SKU
			
		LEFT JOIN	BAANDB.TTCIBD001301@PLN01 TCIBD001 
			ON	TRIM(TCIBD001.T$ITEM) = GRD.SKU
		
		LEFT JOIN ( SELECT 	trim(whwmd217.t$item) 	item,
						whwmd217.t$cwar		cwar,
						case when sum(nvl(whwmd217.t$mauc$1,0)) = 0                            
						then sum(whwmd217.t$ftpa$1)
						else round(sum(whwmd217.t$mauc$1) / sum(a.t$qhnd), 4)    
						end                  			mauc 
				FROM 	baandb.twhwmd217301@PLN01 whwmd217 
					LEFT JOIN baandb.twhinr140301@PLN01 a                             
						ON 	 trim(a.t$cwar) IN ('A01200') 
						AND 	 a.t$item = whwmd217.t$item
				GROUP BY whwmd217.t$item, whwmd217.t$cwar) 		maucLN  	
			ON	maucLN.cwar IN ('A01200')                         
			AND	maucLN.item = ( case when ( BOM.SKU = '' or BOM.SKU is null) then 
								  GRD.SKU 							
								when bom.primarycomponent = '0' then
								  GRD.SKU
								when bom.primarycomponent = '1' then
								  BOM.SKU
							end )
	WHERE GRD.SYSTEMQTY >=0

	UNION ALL

	SELECT DISTINCT GCD.REQUESTNUMBER, GCD.LOCATION AS LOCAL,PTY.PUTAWAYZONE AS ZONA,
		   TO_CHAR('') AS SKU, '' AS DESCRICAO, TO_NUMBER('0') AS QTY_CONTADA, TO_NUMBER('0') AS QTY_SISTEMA,
		TO_NUMBER('0') 				AS VAR_QTDE,
		TO_NUMBER('0') 				AS VL_LOGICO,
		TO_NUMBER('0') 				AS VL_FISICO,
		TO_NUMBER('0') 				AS VL_DIVERGENCIA,    
		   TO_NUMBER('0') AS DIFERENCA,
		   CASE TO_CHAR (GCD.STATUS) 
				WHEN '04' THEN 'LOCAL VAZIO'
				WHEN '06' THEN 'CONTAGEM SUPERVISOR'
		   END             
		   AS STATUS_CONTAGEM,
		   GCD.EDITWHO AS USUARIO_CONTAGEM, TO_CHAR(GCD.EDITDATE ,'DD/MM/YYYY') AS DATAFECHALOCAL, TO_CHAR(GCD.EDITDATE ,'HH24:MM:SS') AS HORAFECHAMENTOLOCAL,
		   TO_CHAR('') AS  SKU_TIK, TO_CHAR('') AS PRIMARIO
	  FROM  WMWHSE5.GLOBALINVCOUNTDETAIL GCD,  WMWHSE5.PUTAWAYZONE PTY,  WMWHSE5.LOC LOC
	 WHERE GCD.STATUS IN ('04','06') 
	   AND GCD.LOCATION = LOC.LOC
	   AND LOC.PUTAWAYZONE = PTY.PUTAWAYZONE
	   AND GCD.LOCATION NOT IN (SELECT LOCATION FROM  WMWHSE5.GLOBALINVREQUESTDETAIL GRD)

	ORDER BY 2, 3