SELECT
				rd.DATERECEIVED						REDO_DT_ENTRADA,
				rd.RECEIPTKEY						ASN,
				CASE WHEN SKU.SUSR8 = 'MINUCIOSO' 
					THEN 'SIM' 
					ELSE 'NÃO' END					IN_MINUCIOSO,
				tpnt.LONG_VALUE						TP_NOTA,
				stnt.DESCRIPTION					SITUACAO,
				rc.TRAILERNUMBER					ID_CAMINHAO,
				rc.TRAILERKEY						PLACA_VEICULO,
				rc.DOOR								LOCAL_DESCR,
				COUNT(DISTINCT rd.SUSR1)			NUM_NFS,
				sum(rd.QTYEXPECTED-rd.QTYRECEIVED)	QT_A_REC,
				SUM(rd.QTYRECEIVED)					QT_REC
FROM
					WMWHSE5.RECEIPTDETAIL rd
		INNER JOIN	WMWHSE5.SKU sku			ON 	sku.SKU = rd.SKU
		INNER JOIN	WMWHSE5.RECEIPT rc		ON 	rc.RECEIPTKEY = rd.RECEIPTKEY
		LEFT JOIN	WMWHSE5.CODELKUP tpnt	ON 	TO_CHAR(tpnt.CODE) = TO_CHAR(rc.TYPE)
											AND tpnt.LISTNAME='RECEIPTYPE'
		LEFT JOIN	WMWHSE5.CODELKUP stnt	ON 	TO_CHAR(stnt.CODE) = TO_CHAR(rc.STATUS)
											AND stnt.LISTNAME='RECSTATUS'
		INNER JOIN	ENTERPRISE.CODELKUP pl	ON	UPPER(pl.UDF1) = rd.WHSEID
											AND	pl.LISTNAME = 'SCHEMA'
WHERE	TO_NUMBER(rc.STATUS) < 9 
GROUP BY
	rd.DATERECEIVED,							
    rd.RECEIPTKEY,						
    CASE WHEN SKU.SUSR8 = 'MINUCIOSO' 
    	THEN 'SIM' 
    	ELSE 'NÃO' END,					
    tpnt.LONG_VALUE,					
    stnt.DESCRIPTION,					
    rc.TRAILERNUMBER,					
    rc.TRAILERKEY,						
    rc.DOOR								