SELECT
		TD.WHSEID							ID_PLANTA,
		CL.UDF2								DESCR_PLANTA,
		TRUNC(TD.STARTTIME, 'DD')			DATA_ARMAZ,
		TD.STARTTIME						HORA_INICIO,
		TD.ENDTIME							HORA_FIM,
		TD.EDITWHO							OPERADOR,
		SUBSTR( TU.USR_NAME,4,
			INSTR(TU.USR_NAME, ',')-4 )   	NOME_OP,
		TD.TASKDETAILKEY					ORDEM_MOV,
		TD.SKU								ID_ITEM,
		SK.DESCR							DESCR_ITEM,
		TD.QTY								QTD,
		TD.FROMLOC							ID_LOC_ORIG,
		FL.PUTAWAYZONE						LOCAL_ORIG,
		TD.TOLOC							ID_LOC_DEST,
		TL.PUTAWAYZONE						LOCAL_DEST
FROM
					WMWHSE5.TASKDETAIL		TD
		INNER JOIN	WMWHSE5.SKU				SK	ON	SK.SKU			=	TD.SKU
		INNER JOIN	ENTERPRISE.CODELKUP		CL	ON	UPPER(CL.UDF1)	=	TD.WHSEID
												AND	CL.LISTNAME		=	'SCHEMA'
		LEFT JOIN 	WMWHSE5.TASKMANAGERUSER TU	ON 	TU.USERKEY 		= 	TD.EDITWHO	
		LEFT JOIN	WMWHSE5.LOC				FL	ON	FL.LOC			=	TD.FROMLOC
		LEFT JOIN	WMWHSE5.LOC				TL	ON	TL.LOC			=	TD.TOLOC
WHERE
		TD.TASKTYPE='PA'
	AND	TD.STATUS='9'