SELECT
	CG.WHSEID										ID_FILIAL,
	CL.UDF2                     					DESCR_FILIAL,
	PZ.PUTAWAYZONE									ZONA,
	SUBSTR(CG.LOC,3,2) 								RUA,
	SUM(CASE WHEN CG.STATUS!=0 THEN 1 ELSE 0 END) 	QT_INVENTARIO,
	COUNT(CG.LOC) 									QT_HABILITADO
FROM  
	(	SELECT 	IV.WHSEID,
				IV.LOC,
				MAX(IV.STATUS) STATUS
		FROM
		( select
			CD.WHSEID,
			CD.LOC,
			CD.STATUS
		  from WMWHSE4.CC CC
		  inner join WMWHSE4.CCDETAIL CD on CD.CCKEY = CC.CCKEY
		  WHERE CC.STATUS!=9
		  union 
		  select
			PH.WHSEID,
			PH.LOC,
			PH.STATUS
		  FROM WMWHSE4.PHYSICAL PH) IV
		GROUP BY IV.WHSEID, IV.LOC) CG
	INNER JOIN WMWHSE4.LOC LC ON LC.LOC = CG.LOC
	INNER JOIN WMWHSE4.PUTAWAYZONE PZ ON PZ.PUTAWAYZONE = LC.PUTAWAYZONE
	INNER JOIN ENTERPRISE.CODELKUP CL ON  UPPER(CL.UDF1) = CG.WHSEID
									  AND CL.LISTNAME = 'SCHEMA'
GROUP BY 
	PZ.PUTAWAYZONE,
	SUBSTR(CG.LOC,3,2),
	CG.WHSEID,
    CL.UDF2   